/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s22 CASADI_PREFIX(s22)
#define casadi_s23 CASADI_PREFIX(s23)
#define casadi_s24 CASADI_PREFIX(s24)
#define casadi_s25 CASADI_PREFIX(s25)
#define casadi_s26 CASADI_PREFIX(s26)
#define casadi_s27 CASADI_PREFIX(s27)
#define casadi_s28 CASADI_PREFIX(s28)
#define casadi_s29 CASADI_PREFIX(s29)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s30 CASADI_PREFIX(s30)
#define casadi_s31 CASADI_PREFIX(s31)
#define casadi_s32 CASADI_PREFIX(s32)
#define casadi_s33 CASADI_PREFIX(s33)
#define casadi_s34 CASADI_PREFIX(s34)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s6[51] = {11, 4, 0, 11, 22, 33, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s9[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s10[5] = {11, 1, 0, 1, 0};
static const casadi_int casadi_s11[135] = {11, 11, 0, 11, 22, 33, 44, 55, 66, 77, 88, 99, 110, 121, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s12[5] = {11, 1, 0, 1, 1};
static const casadi_int casadi_s13[5] = {11, 1, 0, 1, 2};
static const casadi_int casadi_s14[5] = {11, 1, 0, 1, 3};
static const casadi_int casadi_s15[15] = {11, 3, 0, 3, 6, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9};
static const casadi_int casadi_s16[23] = {3, 11, 0, 0, 0, 0, 0, 0, 0, 0, 3, 6, 9, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s17[23] = {11, 11, 0, 0, 0, 0, 0, 0, 0, 0, 3, 6, 9, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s18[23] = {11, 11, 0, 3, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9};
static const casadi_int casadi_s19[5] = {11, 1, 0, 1, 4};
static const casadi_int casadi_s20[5] = {11, 1, 0, 1, 5};
static const casadi_int casadi_s21[5] = {11, 1, 0, 1, 6};
static const casadi_int casadi_s22[5] = {11, 1, 0, 1, 7};
static const casadi_int casadi_s23[5] = {11, 1, 0, 1, 8};
static const casadi_int casadi_s24[5] = {11, 1, 0, 1, 9};
static const casadi_int casadi_s25[5] = {11, 1, 0, 1, 10};
static const casadi_int casadi_s26[11] = {4, 4, 0, 1, 2, 3, 4, 3, 2, 1, 0};
static const casadi_int casadi_s27[11] = {11, 4, 0, 1, 2, 3, 4, 6, 5, 4, 3};
static const casadi_int casadi_s28[18] = {4, 11, 0, 0, 0, 0, 1, 2, 3, 4, 4, 4, 4, 4, 3, 2, 1, 0};
static const casadi_int casadi_s29[23] = {11, 4, 0, 4, 8, 12, 16, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10};
static const casadi_int casadi_s30[30] = {4, 11, 0, 0, 0, 0, 0, 0, 0, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s31[34] = {11, 11, 0, 0, 0, 0, 1, 2, 3, 4, 8, 12, 16, 20, 6, 5, 4, 3, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10, 7, 8, 9, 10};
static const casadi_int casadi_s32[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s33[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s34[179] = {15, 11, 0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_dyn_disc_phi_fun_jac:(i0[11],i1[4],i2[15])->(o0[11],o1[15x11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+11, *w1=w+22, *w2=w+43, *w3=w+52, *w4=w+61, *w5=w+70, w6, w7, w8, w9, *w10=w+85, *w11=w+89, *w12=w+93, *w13=w+102, *w14=w+105, *w15=w+138, *w16=w+171, w17, w18, w19, w20, *w21=w+187, *w22=w+191, *w23=w+195, *w24=w+199, *w25=w+203, *w26=w+219, *w27=w+235, *w28=w+279, *w29=w+323, *w30=w+351, *w31=w+367, *w32=w+383, *w33=w+427, *w34=w+548, *w35=w+669, *w36=w+680, *w41=w+845, *w42=w+854, *w44=w+863, *w45=w+883;
  /* #0: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #1: @1 = zeros(3x7) */
  casadi_clear(w1, 21);
  /* #2: @2 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w2);
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = zeros(3x3) */
  casadi_clear(w4, 9);
  /* #5: @5 = input[0][0] */
  casadi_copy(arg[0], 11, w5);
  /* #6: @6 = @5[3] */
  for (rr=(&w6), ss=w5+3; ss!=w5+4; ss+=1) *rr++ = *ss;
  /* #7: @7 = @5[4] */
  for (rr=(&w7), ss=w5+4; ss!=w5+5; ss+=1) *rr++ = *ss;
  /* #8: @8 = @5[5] */
  for (rr=(&w8), ss=w5+5; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #9: @9 = @5[6] */
  for (rr=(&w9), ss=w5+6; ss!=w5+7; ss+=1) *rr++ = *ss;
  /* #10: @10 = vertcat(@6, @7, @8, @9) */
  rr=w10;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #11: @6 = ||@10||_F */
  w6 = sqrt(casadi_dot(4, w10, w10));
  /* #12: @11 = (@10/@6) */
  for (i=0, rr=w11, cr=w10; i<4; ++i) (*rr++)  = ((*cr++)/w6);
  /* #13: @7 = @11[3] */
  for (rr=(&w7), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #14: @7 = (-@7) */
  w7 = (- w7 );
  /* #15: (@4[3] = @7) */
  for (rr=w4+3, ss=(&w7); rr!=w4+4; rr+=1) *rr = *ss++;
  /* #16: @7 = @11[2] */
  for (rr=(&w7), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #17: (@4[6] = @7) */
  for (rr=w4+6, ss=(&w7); rr!=w4+7; rr+=1) *rr = *ss++;
  /* #18: @7 = @11[1] */
  for (rr=(&w7), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #19: @7 = (-@7) */
  w7 = (- w7 );
  /* #20: (@4[7] = @7) */
  for (rr=w4+7, ss=(&w7); rr!=w4+8; rr+=1) *rr = *ss++;
  /* #21: @7 = @11[3] */
  for (rr=(&w7), ss=w11+3; ss!=w11+4; ss+=1) *rr++ = *ss;
  /* #22: (@4[1] = @7) */
  for (rr=w4+1, ss=(&w7); rr!=w4+2; rr+=1) *rr = *ss++;
  /* #23: @7 = @11[2] */
  for (rr=(&w7), ss=w11+2; ss!=w11+3; ss+=1) *rr++ = *ss;
  /* #24: @7 = (-@7) */
  w7 = (- w7 );
  /* #25: (@4[2] = @7) */
  for (rr=w4+2, ss=(&w7); rr!=w4+3; rr+=1) *rr = *ss++;
  /* #26: @7 = @11[1] */
  for (rr=(&w7), ss=w11+1; ss!=w11+2; ss+=1) *rr++ = *ss;
  /* #27: (@4[5] = @7) */
  for (rr=w4+5, ss=(&w7); rr!=w4+6; rr+=1) *rr = *ss++;
  /* #28: @12 = (2.*@4) */
  for (i=0, rr=w12, cs=w4; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #29: @3 = mac(@12,@4,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #30: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #31: @7 = @11[0] */
  for (rr=(&w7), ss=w11+0; ss!=w11+1; ss+=1) *rr++ = *ss;
  /* #32: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #33: @3 = (@7*@4) */
  for (i=0, rr=w3, cs=w4; i<9; ++i) (*rr++)  = (w7*(*cs++));
  /* #34: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #35: @13 = zeros(3x1) */
  casadi_clear(w13, 3);
  /* #36: @14 = horzcat(@1, @2, @13) */
  rr=w14;
  for (i=0, cs=w1; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  /* #37: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #38: @16 = zeros(4x3) */
  casadi_clear(w16, 12);
  /* #39: @8 = 0.5 */
  w8 = 5.0000000000000000e-01;
  /* #40: @9 = 0 */
  w9 = 0.;
  /* #41: @17 = 0 */
  w17 = 0.;
  /* #42: @18 = 0 */
  w18 = 0.;
  /* #43: @19 = @5[10] */
  for (rr=(&w19), ss=w5+10; ss!=w5+11; ss+=1) *rr++ = *ss;
  /* #44: @20 = (-@19) */
  w20 = (- w19 );
  /* #45: @21 = horzcat(@9, @17, @18, @20) */
  rr=w21;
  *rr++ = w9;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w20;
  /* #46: @21 = @21' */
  /* #47: @9 = 0 */
  w9 = 0.;
  /* #48: @17 = 0 */
  w17 = 0.;
  /* #49: @18 = 0 */
  w18 = 0.;
  /* #50: @22 = horzcat(@9, @17, @19, @18) */
  rr=w22;
  *rr++ = w9;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w18;
  /* #51: @22 = @22' */
  /* #52: @9 = 0 */
  w9 = 0.;
  /* #53: @17 = (-@19) */
  w17 = (- w19 );
  /* #54: @18 = 0 */
  w18 = 0.;
  /* #55: @20 = 0 */
  w20 = 0.;
  /* #56: @23 = horzcat(@9, @17, @18, @20) */
  rr=w23;
  *rr++ = w9;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w20;
  /* #57: @23 = @23' */
  /* #58: @9 = 0 */
  w9 = 0.;
  /* #59: @17 = 0 */
  w17 = 0.;
  /* #60: @18 = 0 */
  w18 = 0.;
  /* #61: @24 = horzcat(@19, @9, @17, @18) */
  rr=w24;
  *rr++ = w19;
  *rr++ = w9;
  *rr++ = w17;
  *rr++ = w18;
  /* #62: @24 = @24' */
  /* #63: @25 = horzcat(@21, @22, @23, @24) */
  rr=w25;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  /* #64: @26 = @25' */
  for (i=0, rr=w26, cs=w25; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #65: @26 = (@8*@26) */
  for (i=0, rr=w26, cs=w26; i<16; ++i) (*rr++)  = (w8*(*cs++));
  /* #66: @25 = zeros(4x4) */
  casadi_clear(w25, 16);
  /* #67: @27 = horzcat(@16, @26, @25) */
  rr=w27;
  for (i=0, cs=w16; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<16; ++i) *rr++ = *cs++;
  /* #68: @28 = @27' */
  for (i=0, rr=w28, cs=w27; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #69: @29 = zeros(4x7) */
  casadi_clear(w29, 28);
  /* #70: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #71: @25 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w25);
  /* #72: @30 = zeros(4x4) */
  casadi_clear(w30, 16);
  /* #73: @9 = 0.6756 */
  w9 = 6.7559999999999998e-01;
  /* #74: (@30[0] = @9) */
  for (rr=w30+0, ss=(&w9); rr!=w30+1; rr+=1) *rr = *ss++;
  /* #75: @9 = 0 */
  w9 = 0.;
  /* #76: (@30[4] = @9) */
  for (rr=w30+4, ss=(&w9); rr!=w30+5; rr+=1) *rr = *ss++;
  /* #77: @9 = 0 */
  w9 = 0.;
  /* #78: (@30[8] = @9) */
  for (rr=w30+8, ss=(&w9); rr!=w30+9; rr+=1) *rr = *ss++;
  /* #79: @9 = 0 */
  w9 = 0.;
  /* #80: (@30[12] = @9) */
  for (rr=w30+12, ss=(&w9); rr!=w30+13; rr+=1) *rr = *ss++;
  /* #81: @9 = 0 */
  w9 = 0.;
  /* #82: (@30[1] = @9) */
  for (rr=w30+1, ss=(&w9); rr!=w30+2; rr+=1) *rr = *ss++;
  /* #83: @9 = 0.6344 */
  w9 = 6.3439999999999996e-01;
  /* #84: (@30[5] = @9) */
  for (rr=w30+5, ss=(&w9); rr!=w30+6; rr+=1) *rr = *ss++;
  /* #85: @9 = 0 */
  w9 = 0.;
  /* #86: (@30[9] = @9) */
  for (rr=w30+9, ss=(&w9); rr!=w30+10; rr+=1) *rr = *ss++;
  /* #87: @9 = 0 */
  w9 = 0.;
  /* #88: (@30[13] = @9) */
  for (rr=w30+13, ss=(&w9); rr!=w30+14; rr+=1) *rr = *ss++;
  /* #89: @9 = 0 */
  w9 = 0.;
  /* #90: (@30[2] = @9) */
  for (rr=w30+2, ss=(&w9); rr!=w30+3; rr+=1) *rr = *ss++;
  /* #91: @9 = 0 */
  w9 = 0.;
  /* #92: (@30[6] = @9) */
  for (rr=w30+6, ss=(&w9); rr!=w30+7; rr+=1) *rr = *ss++;
  /* #93: @9 = 0.408 */
  w9 = 4.0799999999999997e-01;
  /* #94: (@30[10] = @9) */
  for (rr=w30+10, ss=(&w9); rr!=w30+11; rr+=1) *rr = *ss++;
  /* #95: @9 = 0 */
  w9 = 0.;
  /* #96: (@30[14] = @9) */
  for (rr=w30+14, ss=(&w9); rr!=w30+15; rr+=1) *rr = *ss++;
  /* #97: @9 = 0 */
  w9 = 0.;
  /* #98: (@30[3] = @9) */
  for (rr=w30+3, ss=(&w9); rr!=w30+4; rr+=1) *rr = *ss++;
  /* #99: @9 = 0 */
  w9 = 0.;
  /* #100: (@30[7] = @9) */
  for (rr=w30+7, ss=(&w9); rr!=w30+8; rr+=1) *rr = *ss++;
  /* #101: @9 = 0 */
  w9 = 0.;
  /* #102: (@30[11] = @9) */
  for (rr=w30+11, ss=(&w9); rr!=w30+12; rr+=1) *rr = *ss++;
  /* #103: @9 = 0.2953 */
  w9 = 2.9530000000000001e-01;
  /* #104: (@30[15] = @9) */
  for (rr=w30+15, ss=(&w9); rr!=w30+16; rr+=1) *rr = *ss++;
  /* #105: @25 = (@30\@25) */
  rr = w25;
  ss = w30;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #106: @31 = zeros(4x4) */
  casadi_clear(w31, 16);
  /* #107: @9 = 0.5941 */
  w9 = 5.9409999999999996e-01;
  /* #108: (@31[0] = @9) */
  for (rr=w31+0, ss=(&w9); rr!=w31+1; rr+=1) *rr = *ss++;
  /* #109: @9 = -0.8109 */
  w9 = -8.1089999999999995e-01;
  /* #110: @17 = (@9*@19) */
  w17  = (w9*w19);
  /* #111: (@31[4] = @17) */
  for (rr=w31+4, ss=(&w17); rr!=w31+5; rr+=1) *rr = *ss++;
  /* #112: @17 = 0 */
  w17 = 0.;
  /* #113: (@31[8] = @17) */
  for (rr=w31+8, ss=(&w17); rr!=w31+9; rr+=1) *rr = *ss++;
  /* #114: @17 = 0 */
  w17 = 0.;
  /* #115: (@31[12] = @17) */
  for (rr=w31+12, ss=(&w17); rr!=w31+13; rr+=1) *rr = *ss++;
  /* #116: @17 = 0.3984 */
  w17 = 3.9839999999999998e-01;
  /* #117: @19 = (@17*@19) */
  w19  = (w17*w19);
  /* #118: (@31[1] = @19) */
  for (rr=w31+1, ss=(&w19); rr!=w31+2; rr+=1) *rr = *ss++;
  /* #119: @19 = 0.704 */
  w19 = 7.0399999999999996e-01;
  /* #120: (@31[5] = @19) */
  for (rr=w31+5, ss=(&w19); rr!=w31+6; rr+=1) *rr = *ss++;
  /* #121: @19 = 0 */
  w19 = 0.;
  /* #122: (@31[9] = @19) */
  for (rr=w31+9, ss=(&w19); rr!=w31+10; rr+=1) *rr = *ss++;
  /* #123: @19 = 0 */
  w19 = 0.;
  /* #124: (@31[13] = @19) */
  for (rr=w31+13, ss=(&w19); rr!=w31+14; rr+=1) *rr = *ss++;
  /* #125: @19 = 0 */
  w19 = 0.;
  /* #126: (@31[2] = @19) */
  for (rr=w31+2, ss=(&w19); rr!=w31+3; rr+=1) *rr = *ss++;
  /* #127: @19 = 0 */
  w19 = 0.;
  /* #128: (@31[6] = @19) */
  for (rr=w31+6, ss=(&w19); rr!=w31+7; rr+=1) *rr = *ss++;
  /* #129: @19 = 0.9365 */
  w19 = 9.3650000000000000e-01;
  /* #130: (@31[10] = @19) */
  for (rr=w31+10, ss=(&w19); rr!=w31+11; rr+=1) *rr = *ss++;
  /* #131: @19 = 0 */
  w19 = 0.;
  /* #132: (@31[14] = @19) */
  for (rr=w31+14, ss=(&w19); rr!=w31+15; rr+=1) *rr = *ss++;
  /* #133: @19 = 0 */
  w19 = 0.;
  /* #134: (@31[3] = @19) */
  for (rr=w31+3, ss=(&w19); rr!=w31+4; rr+=1) *rr = *ss++;
  /* #135: @19 = 0 */
  w19 = 0.;
  /* #136: (@31[7] = @19) */
  for (rr=w31+7, ss=(&w19); rr!=w31+8; rr+=1) *rr = *ss++;
  /* #137: @19 = 0 */
  w19 = 0.;
  /* #138: (@31[11] = @19) */
  for (rr=w31+11, ss=(&w19); rr!=w31+12; rr+=1) *rr = *ss++;
  /* #139: @19 = 0.9752 */
  w19 = 9.7519999999999996e-01;
  /* #140: (@31[15] = @19) */
  for (rr=w31+15, ss=(&w19); rr!=w31+16; rr+=1) *rr = *ss++;
  /* #141: @26 = mac(@25,@31,@26) */
  for (i=0, rr=w26; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w25+j, tt=w31+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #142: @26 = (-@26) */
  for (i=0, rr=w26, cs=w26; i<16; ++i) *rr++ = (- *cs++ );
  /* #143: @27 = horzcat(@29, @26) */
  rr=w27;
  for (i=0, cs=w29; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<16; ++i) *rr++ = *cs++;
  /* #144: @32 = @27' */
  for (i=0, rr=w32, cs=w27; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #145: @33 = horzcat(@15, @28, @32) */
  rr=w33;
  for (i=0, cs=w15; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<44; ++i) *rr++ = *cs++;
  /* #146: @34 = @33' */
  for (i=0, rr=w34, cs=w33; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #147: @0 = mac(@34,@5,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w34+j, tt=w5+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #148: @35 = zeros(11x1) */
  casadi_clear(w35, 11);
  /* #149: @29 = zeros(4x7) */
  casadi_clear(w29, 28);
  /* #150: @26 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w26);
  /* #151: @26 = (@30\@26) */
  rr = w26;
  ss = w30;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #152: @30 = @26' */
  for (i=0, rr=w30, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #153: @28 = horzcat(@29, @30) */
  rr=w28;
  for (i=0, cs=w29; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<16; ++i) *rr++ = *cs++;
  /* #154: @32 = @28' */
  for (i=0, rr=w32, cs=w28; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #155: @21 = input[1][0] */
  casadi_copy(arg[1], 4, w21);
  /* #156: @35 = mac(@32,@21,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w32+j, tt=w21+i*4; k<4; ++k) *rr += ss[k*11]**tt++;
  /* #157: @0 = (@0+@35) */
  for (i=0, rr=w0, cs=w35; i<11; ++i) (*rr++) += (*cs++);
  /* #158: output[0][0] = @0 */
  casadi_copy(w0, 11, res[0]);
  /* #159: @36 = zeros(15x11) */
  casadi_clear(w36, 165);
  /* #160: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #161: @19 = ones(15x1,1nz) */
  w19 = 1.;
  /* #162: {@18, NULL} = vertsplit(@19) */
  w18 = w19;
  /* #163: @0 = mac(@32,@18,@0) */
  casadi_mtimes(w32, casadi_s6, (&w18), casadi_s5, w0, casadi_s4, w, 0);
  /* #164: (@36[:165:15] = @0) */
  for (rr=w36+0, ss=w0; rr!=w36+165; rr+=15) *rr = *ss++;
  /* #165: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #166: @18 = ones(15x1,1nz) */
  w18 = 1.;
  /* #167: {@19, NULL} = vertsplit(@18) */
  w19 = w18;
  /* #168: @0 = mac(@32,@19,@0) */
  casadi_mtimes(w32, casadi_s6, (&w19), casadi_s7, w0, casadi_s4, w, 0);
  /* #169: (@36[1:166:15] = @0) */
  for (rr=w36+1, ss=w0; rr!=w36+166; rr+=15) *rr = *ss++;
  /* #170: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #171: @19 = ones(15x1,1nz) */
  w19 = 1.;
  /* #172: {@18, NULL} = vertsplit(@19) */
  w18 = w19;
  /* #173: @0 = mac(@32,@18,@0) */
  casadi_mtimes(w32, casadi_s6, (&w18), casadi_s8, w0, casadi_s4, w, 0);
  /* #174: (@36[2:167:15] = @0) */
  for (rr=w36+2, ss=w0; rr!=w36+167; rr+=15) *rr = *ss++;
  /* #175: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #176: @18 = ones(15x1,1nz) */
  w18 = 1.;
  /* #177: {@19, NULL} = vertsplit(@18) */
  w19 = w18;
  /* #178: @0 = mac(@32,@19,@0) */
  casadi_mtimes(w32, casadi_s6, (&w19), casadi_s9, w0, casadi_s4, w, 0);
  /* #179: (@36[3:168:15] = @0) */
  for (rr=w36+3, ss=w0; rr!=w36+168; rr+=15) *rr = *ss++;
  /* #180: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #181: @19 = ones(15x1,1nz) */
  w19 = 1.;
  /* #182: {NULL, @18} = vertsplit(@19) */
  w18 = w19;
  /* #183: @0 = mac(@34,@18,@0) */
  casadi_mtimes(w34, casadi_s11, (&w18), casadi_s10, w0, casadi_s4, w, 0);
  /* #184: (@36[4:169:15] = @0) */
  for (rr=w36+4, ss=w0; rr!=w36+169; rr+=15) *rr = *ss++;
  /* #185: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #186: @18 = ones(15x1,1nz) */
  w18 = 1.;
  /* #187: {NULL, @19} = vertsplit(@18) */
  w19 = w18;
  /* #188: @0 = mac(@34,@19,@0) */
  casadi_mtimes(w34, casadi_s11, (&w19), casadi_s12, w0, casadi_s4, w, 0);
  /* #189: (@36[5:170:15] = @0) */
  for (rr=w36+5, ss=w0; rr!=w36+170; rr+=15) *rr = *ss++;
  /* #190: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #191: @19 = ones(15x1,1nz) */
  w19 = 1.;
  /* #192: {NULL, @18} = vertsplit(@19) */
  w18 = w19;
  /* #193: @0 = mac(@34,@18,@0) */
  casadi_mtimes(w34, casadi_s11, (&w18), casadi_s13, w0, casadi_s4, w, 0);
  /* #194: (@36[6:171:15] = @0) */
  for (rr=w36+6, ss=w0; rr!=w36+171; rr+=15) *rr = *ss++;
  /* #195: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #196: @18 = ones(15x1,1nz) */
  w18 = 1.;
  /* #197: {NULL, @19} = vertsplit(@18) */
  w19 = w18;
  /* #198: @0 = mac(@34,@19,@0) */
  casadi_mtimes(w34, casadi_s11, (&w19), casadi_s14, w0, casadi_s4, w, 0);
  /* #199: @35 = zeros(11x1) */
  casadi_clear(w35, 11);
  /* #200: @37 = zeros(3x7,0nz) */
  /* #201: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #202: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #203: @18 = @19[0] */
  for (rr=(&w18), ss=(&w19)+0; ss!=(&w19)+1; ss+=1) *rr++ = *ss;
  /* #204: @38 = 00 */
  /* #205: @39 = 00 */
  /* #206: @40 = 00 */
  /* #207: @19 = vertcat(@18, @38, @39, @40) */
  rr=(&w19);
  *rr++ = w18;
  /* #208: @18 = (@19/@6) */
  w18  = (w19/w6);
  /* #209: @21 = dense(@18) */
  casadi_densify((&w18), casadi_s5, w21, 0);
  /* #210: @11 = (@11/@6) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) /= w6;
  /* #211: @18 = project(@10) */
  casadi_sparsify(w10, (&w18), casadi_s5, 0);
  /* #212: @20 = dot(@18, @19) */
  w20 = casadi_dot(1, (&w18), (&w19));
  /* #213: @20 = (@20/@6) */
  w20 /= w6;
  /* #214: @22 = (@11*@20) */
  for (i=0, rr=w22, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w20);
  /* #215: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #216: @20 = @21[3] */
  for (rr=(&w20), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #217: @20 = (-@20) */
  w20 = (- w20 );
  /* #218: (@3[3] += @20) */
  for (rr=w3+3, ss=(&w20); rr!=w3+4; rr+=1) *rr += *ss++;
  /* #219: @20 = 0 */
  w20 = 0.;
  /* #220: (@3[6] = @20) */
  for (rr=w3+6, ss=(&w20); rr!=w3+7; rr+=1) *rr = *ss++;
  /* #221: @20 = @21[2] */
  for (rr=(&w20), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #222: (@3[6] += @20) */
  for (rr=w3+6, ss=(&w20); rr!=w3+7; rr+=1) *rr += *ss++;
  /* #223: @20 = 0 */
  w20 = 0.;
  /* #224: (@3[7] = @20) */
  for (rr=w3+7, ss=(&w20); rr!=w3+8; rr+=1) *rr = *ss++;
  /* #225: @20 = @21[1] */
  for (rr=(&w20), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #226: @20 = (-@20) */
  w20 = (- w20 );
  /* #227: (@3[7] += @20) */
  for (rr=w3+7, ss=(&w20); rr!=w3+8; rr+=1) *rr += *ss++;
  /* #228: @20 = 0 */
  w20 = 0.;
  /* #229: (@3[1] = @20) */
  for (rr=w3+1, ss=(&w20); rr!=w3+2; rr+=1) *rr = *ss++;
  /* #230: @20 = @21[3] */
  for (rr=(&w20), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #231: (@3[1] += @20) */
  for (rr=w3+1, ss=(&w20); rr!=w3+2; rr+=1) *rr += *ss++;
  /* #232: @20 = 0 */
  w20 = 0.;
  /* #233: (@3[2] = @20) */
  for (rr=w3+2, ss=(&w20); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #234: @20 = @21[2] */
  for (rr=(&w20), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #235: @20 = (-@20) */
  w20 = (- w20 );
  /* #236: (@3[2] += @20) */
  for (rr=w3+2, ss=(&w20); rr!=w3+3; rr+=1) *rr += *ss++;
  /* #237: @20 = 0 */
  w20 = 0.;
  /* #238: (@3[5] = @20) */
  for (rr=w3+5, ss=(&w20); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #239: @20 = @21[1] */
  for (rr=(&w20), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #240: (@3[5] += @20) */
  for (rr=w3+5, ss=(&w20); rr!=w3+6; rr+=1) *rr += *ss++;
  /* #241: @2 = mac(@12,@3,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #242: @41 = zeros(3x3) */
  casadi_clear(w41, 9);
  /* #243: @42 = (2.*@3) */
  for (i=0, rr=w42, cs=w3; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #244: @41 = mac(@42,@4,@41) */
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w42+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #245: @2 = (@2+@41) */
  for (i=0, rr=w2, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #246: @20 = @21[0] */
  for (rr=(&w20), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #247: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #248: @41 = (@4*@20) */
  for (i=0, rr=w41, cr=w4; i<9; ++i) (*rr++)  = ((*cr++)*w20);
  /* #249: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<9; ++i) (*rr++)  = (w7*(*cs++));
  /* #250: @41 = (@41+@3) */
  for (i=0, rr=w41, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #251: @2 = (@2+@41) */
  for (i=0, rr=w2, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #252: @38 = zeros(3x1,0nz) */
  /* #253: @41 = horzcat(@37, @2, @38) */
  rr=w41;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #254: @2 = @41' */
  casadi_trans(w41,casadi_s16, w2, casadi_s15, iw);
  /* #255: @37 = zeros(11x4,0nz) */
  /* #256: @38 = zeros(11x4,0nz) */
  /* #257: @41 = horzcat(@2, @37, @38) */
  rr=w41;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #258: @2 = @41' */
  casadi_trans(w41,casadi_s18, w2, casadi_s17, iw);
  /* #259: @35 = mac(@2,@5,@35) */
  casadi_mtimes(w2, casadi_s17, w5, casadi_s4, w35, casadi_s4, w, 0);
  /* #260: @0 = (@0+@35) */
  for (i=0, rr=w0, cs=w35; i<11; ++i) (*rr++) += (*cs++);
  /* #261: (@36[7:172:15] = @0) */
  for (rr=w36+7, ss=w0; rr!=w36+172; rr+=15) *rr = *ss++;
  /* #262: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #263: @20 = ones(15x1,1nz) */
  w20 = 1.;
  /* #264: {NULL, @18} = vertsplit(@20) */
  w18 = w20;
  /* #265: @0 = mac(@34,@18,@0) */
  casadi_mtimes(w34, casadi_s11, (&w18), casadi_s19, w0, casadi_s4, w, 0);
  /* #266: @35 = zeros(11x1) */
  casadi_clear(w35, 11);
  /* #267: @37 = zeros(3x7,0nz) */
  /* #268: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #269: @41 = zeros(3x3) */
  casadi_clear(w41, 9);
  /* #270: @38 = 00 */
  /* #271: @20 = @18[0] */
  for (rr=(&w20), ss=(&w18)+0; ss!=(&w18)+1; ss+=1) *rr++ = *ss;
  /* #272: @39 = 00 */
  /* #273: @40 = 00 */
  /* #274: @18 = vertcat(@38, @20, @39, @40) */
  rr=(&w18);
  *rr++ = w20;
  /* #275: @20 = (@18/@6) */
  w20  = (w18/w6);
  /* #276: @21 = dense(@20) */
  casadi_densify((&w20), casadi_s7, w21, 0);
  /* #277: @20 = project(@10) */
  casadi_sparsify(w10, (&w20), casadi_s7, 0);
  /* #278: @19 = dot(@20, @18) */
  w19 = casadi_dot(1, (&w20), (&w18));
  /* #279: @19 = (@19/@6) */
  w19 /= w6;
  /* #280: @22 = (@11*@19) */
  for (i=0, rr=w22, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w19);
  /* #281: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #282: @19 = @21[3] */
  for (rr=(&w19), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #283: @19 = (-@19) */
  w19 = (- w19 );
  /* #284: (@41[3] += @19) */
  for (rr=w41+3, ss=(&w19); rr!=w41+4; rr+=1) *rr += *ss++;
  /* #285: @19 = 0 */
  w19 = 0.;
  /* #286: (@41[6] = @19) */
  for (rr=w41+6, ss=(&w19); rr!=w41+7; rr+=1) *rr = *ss++;
  /* #287: @19 = @21[2] */
  for (rr=(&w19), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #288: (@41[6] += @19) */
  for (rr=w41+6, ss=(&w19); rr!=w41+7; rr+=1) *rr += *ss++;
  /* #289: @19 = 0 */
  w19 = 0.;
  /* #290: (@41[7] = @19) */
  for (rr=w41+7, ss=(&w19); rr!=w41+8; rr+=1) *rr = *ss++;
  /* #291: @19 = @21[1] */
  for (rr=(&w19), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #292: @19 = (-@19) */
  w19 = (- w19 );
  /* #293: (@41[7] += @19) */
  for (rr=w41+7, ss=(&w19); rr!=w41+8; rr+=1) *rr += *ss++;
  /* #294: @19 = 0 */
  w19 = 0.;
  /* #295: (@41[1] = @19) */
  for (rr=w41+1, ss=(&w19); rr!=w41+2; rr+=1) *rr = *ss++;
  /* #296: @19 = @21[3] */
  for (rr=(&w19), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #297: (@41[1] += @19) */
  for (rr=w41+1, ss=(&w19); rr!=w41+2; rr+=1) *rr += *ss++;
  /* #298: @19 = 0 */
  w19 = 0.;
  /* #299: (@41[2] = @19) */
  for (rr=w41+2, ss=(&w19); rr!=w41+3; rr+=1) *rr = *ss++;
  /* #300: @19 = @21[2] */
  for (rr=(&w19), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #301: @19 = (-@19) */
  w19 = (- w19 );
  /* #302: (@41[2] += @19) */
  for (rr=w41+2, ss=(&w19); rr!=w41+3; rr+=1) *rr += *ss++;
  /* #303: @19 = 0 */
  w19 = 0.;
  /* #304: (@41[5] = @19) */
  for (rr=w41+5, ss=(&w19); rr!=w41+6; rr+=1) *rr = *ss++;
  /* #305: @19 = @21[1] */
  for (rr=(&w19), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #306: (@41[5] += @19) */
  for (rr=w41+5, ss=(&w19); rr!=w41+6; rr+=1) *rr += *ss++;
  /* #307: @2 = mac(@12,@41,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #308: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #309: @42 = (2.*@41) */
  for (i=0, rr=w42, cs=w41; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #310: @3 = mac(@42,@4,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w42+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #311: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #312: @19 = @21[0] */
  for (rr=(&w19), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #313: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #314: @3 = (@4*@19) */
  for (i=0, rr=w3, cr=w4; i<9; ++i) (*rr++)  = ((*cr++)*w19);
  /* #315: @41 = (@7*@41) */
  for (i=0, rr=w41, cs=w41; i<9; ++i) (*rr++)  = (w7*(*cs++));
  /* #316: @3 = (@3+@41) */
  for (i=0, rr=w3, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #317: @2 = (@2+@3) */
  for (i=0, rr=w2, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #318: @38 = zeros(3x1,0nz) */
  /* #319: @3 = horzcat(@37, @2, @38) */
  rr=w3;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #320: @2 = @3' */
  casadi_trans(w3,casadi_s16, w2, casadi_s15, iw);
  /* #321: @37 = zeros(11x4,0nz) */
  /* #322: @38 = zeros(11x4,0nz) */
  /* #323: @3 = horzcat(@2, @37, @38) */
  rr=w3;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #324: @2 = @3' */
  casadi_trans(w3,casadi_s18, w2, casadi_s17, iw);
  /* #325: @35 = mac(@2,@5,@35) */
  casadi_mtimes(w2, casadi_s17, w5, casadi_s4, w35, casadi_s4, w, 0);
  /* #326: @0 = (@0+@35) */
  for (i=0, rr=w0, cs=w35; i<11; ++i) (*rr++) += (*cs++);
  /* #327: (@36[8:173:15] = @0) */
  for (rr=w36+8, ss=w0; rr!=w36+173; rr+=15) *rr = *ss++;
  /* #328: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #329: @19 = ones(15x1,1nz) */
  w19 = 1.;
  /* #330: {NULL, @20} = vertsplit(@19) */
  w20 = w19;
  /* #331: @0 = mac(@34,@20,@0) */
  casadi_mtimes(w34, casadi_s11, (&w20), casadi_s20, w0, casadi_s4, w, 0);
  /* #332: @35 = zeros(11x1) */
  casadi_clear(w35, 11);
  /* #333: @37 = zeros(3x7,0nz) */
  /* #334: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #335: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #336: @38 = 00 */
  /* #337: @39 = 00 */
  /* #338: @19 = @20[0] */
  for (rr=(&w19), ss=(&w20)+0; ss!=(&w20)+1; ss+=1) *rr++ = *ss;
  /* #339: @40 = 00 */
  /* #340: @20 = vertcat(@38, @39, @19, @40) */
  rr=(&w20);
  *rr++ = w19;
  /* #341: @19 = (@20/@6) */
  w19  = (w20/w6);
  /* #342: @21 = dense(@19) */
  casadi_densify((&w19), casadi_s8, w21, 0);
  /* #343: @19 = project(@10) */
  casadi_sparsify(w10, (&w19), casadi_s8, 0);
  /* #344: @18 = dot(@19, @20) */
  w18 = casadi_dot(1, (&w19), (&w20));
  /* #345: @18 = (@18/@6) */
  w18 /= w6;
  /* #346: @22 = (@11*@18) */
  for (i=0, rr=w22, cr=w11; i<4; ++i) (*rr++)  = ((*cr++)*w18);
  /* #347: @21 = (@21-@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) -= (*cs++);
  /* #348: @18 = @21[3] */
  for (rr=(&w18), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #349: @18 = (-@18) */
  w18 = (- w18 );
  /* #350: (@3[3] += @18) */
  for (rr=w3+3, ss=(&w18); rr!=w3+4; rr+=1) *rr += *ss++;
  /* #351: @18 = 0 */
  w18 = 0.;
  /* #352: (@3[6] = @18) */
  for (rr=w3+6, ss=(&w18); rr!=w3+7; rr+=1) *rr = *ss++;
  /* #353: @18 = @21[2] */
  for (rr=(&w18), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #354: (@3[6] += @18) */
  for (rr=w3+6, ss=(&w18); rr!=w3+7; rr+=1) *rr += *ss++;
  /* #355: @18 = 0 */
  w18 = 0.;
  /* #356: (@3[7] = @18) */
  for (rr=w3+7, ss=(&w18); rr!=w3+8; rr+=1) *rr = *ss++;
  /* #357: @18 = @21[1] */
  for (rr=(&w18), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #358: @18 = (-@18) */
  w18 = (- w18 );
  /* #359: (@3[7] += @18) */
  for (rr=w3+7, ss=(&w18); rr!=w3+8; rr+=1) *rr += *ss++;
  /* #360: @18 = 0 */
  w18 = 0.;
  /* #361: (@3[1] = @18) */
  for (rr=w3+1, ss=(&w18); rr!=w3+2; rr+=1) *rr = *ss++;
  /* #362: @18 = @21[3] */
  for (rr=(&w18), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #363: (@3[1] += @18) */
  for (rr=w3+1, ss=(&w18); rr!=w3+2; rr+=1) *rr += *ss++;
  /* #364: @18 = 0 */
  w18 = 0.;
  /* #365: (@3[2] = @18) */
  for (rr=w3+2, ss=(&w18); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #366: @18 = @21[2] */
  for (rr=(&w18), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #367: @18 = (-@18) */
  w18 = (- w18 );
  /* #368: (@3[2] += @18) */
  for (rr=w3+2, ss=(&w18); rr!=w3+3; rr+=1) *rr += *ss++;
  /* #369: @18 = 0 */
  w18 = 0.;
  /* #370: (@3[5] = @18) */
  for (rr=w3+5, ss=(&w18); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #371: @18 = @21[1] */
  for (rr=(&w18), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #372: (@3[5] += @18) */
  for (rr=w3+5, ss=(&w18); rr!=w3+6; rr+=1) *rr += *ss++;
  /* #373: @2 = mac(@12,@3,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #374: @41 = zeros(3x3) */
  casadi_clear(w41, 9);
  /* #375: @42 = (2.*@3) */
  for (i=0, rr=w42, cs=w3; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #376: @41 = mac(@42,@4,@41) */
  for (i=0, rr=w41; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w42+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #377: @2 = (@2+@41) */
  for (i=0, rr=w2, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #378: @18 = @21[0] */
  for (rr=(&w18), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #379: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #380: @41 = (@4*@18) */
  for (i=0, rr=w41, cr=w4; i<9; ++i) (*rr++)  = ((*cr++)*w18);
  /* #381: @3 = (@7*@3) */
  for (i=0, rr=w3, cs=w3; i<9; ++i) (*rr++)  = (w7*(*cs++));
  /* #382: @41 = (@41+@3) */
  for (i=0, rr=w41, cs=w3; i<9; ++i) (*rr++) += (*cs++);
  /* #383: @2 = (@2+@41) */
  for (i=0, rr=w2, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #384: @38 = zeros(3x1,0nz) */
  /* #385: @41 = horzcat(@37, @2, @38) */
  rr=w41;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #386: @2 = @41' */
  casadi_trans(w41,casadi_s16, w2, casadi_s15, iw);
  /* #387: @37 = zeros(11x4,0nz) */
  /* #388: @38 = zeros(11x4,0nz) */
  /* #389: @41 = horzcat(@2, @37, @38) */
  rr=w41;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #390: @2 = @41' */
  casadi_trans(w41,casadi_s18, w2, casadi_s17, iw);
  /* #391: @35 = mac(@2,@5,@35) */
  casadi_mtimes(w2, casadi_s17, w5, casadi_s4, w35, casadi_s4, w, 0);
  /* #392: @0 = (@0+@35) */
  for (i=0, rr=w0, cs=w35; i<11; ++i) (*rr++) += (*cs++);
  /* #393: (@36[9:174:15] = @0) */
  for (rr=w36+9, ss=w0; rr!=w36+174; rr+=15) *rr = *ss++;
  /* #394: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #395: @18 = ones(15x1,1nz) */
  w18 = 1.;
  /* #396: {NULL, @19} = vertsplit(@18) */
  w19 = w18;
  /* #397: @0 = mac(@34,@19,@0) */
  casadi_mtimes(w34, casadi_s11, (&w19), casadi_s21, w0, casadi_s4, w, 0);
  /* #398: @35 = zeros(11x1) */
  casadi_clear(w35, 11);
  /* #399: @37 = zeros(3x7,0nz) */
  /* #400: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #401: @41 = zeros(3x3) */
  casadi_clear(w41, 9);
  /* #402: @38 = 00 */
  /* #403: @39 = 00 */
  /* #404: @40 = 00 */
  /* #405: @18 = @19[0] */
  for (rr=(&w18), ss=(&w19)+0; ss!=(&w19)+1; ss+=1) *rr++ = *ss;
  /* #406: @19 = vertcat(@38, @39, @40, @18) */
  rr=(&w19);
  *rr++ = w18;
  /* #407: @18 = (@19/@6) */
  w18  = (w19/w6);
  /* #408: @21 = dense(@18) */
  casadi_densify((&w18), casadi_s9, w21, 0);
  /* #409: @18 = project(@10) */
  casadi_sparsify(w10, (&w18), casadi_s9, 0);
  /* #410: @20 = dot(@18, @19) */
  w20 = casadi_dot(1, (&w18), (&w19));
  /* #411: @20 = (@20/@6) */
  w20 /= w6;
  /* #412: @11 = (@11*@20) */
  for (i=0, rr=w11; i<4; ++i) (*rr++) *= w20;
  /* #413: @21 = (@21-@11) */
  for (i=0, rr=w21, cs=w11; i<4; ++i) (*rr++) -= (*cs++);
  /* #414: @20 = @21[3] */
  for (rr=(&w20), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #415: @20 = (-@20) */
  w20 = (- w20 );
  /* #416: (@41[3] += @20) */
  for (rr=w41+3, ss=(&w20); rr!=w41+4; rr+=1) *rr += *ss++;
  /* #417: @20 = 0 */
  w20 = 0.;
  /* #418: (@41[6] = @20) */
  for (rr=w41+6, ss=(&w20); rr!=w41+7; rr+=1) *rr = *ss++;
  /* #419: @20 = @21[2] */
  for (rr=(&w20), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #420: (@41[6] += @20) */
  for (rr=w41+6, ss=(&w20); rr!=w41+7; rr+=1) *rr += *ss++;
  /* #421: @20 = 0 */
  w20 = 0.;
  /* #422: (@41[7] = @20) */
  for (rr=w41+7, ss=(&w20); rr!=w41+8; rr+=1) *rr = *ss++;
  /* #423: @20 = @21[1] */
  for (rr=(&w20), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #424: @20 = (-@20) */
  w20 = (- w20 );
  /* #425: (@41[7] += @20) */
  for (rr=w41+7, ss=(&w20); rr!=w41+8; rr+=1) *rr += *ss++;
  /* #426: @20 = 0 */
  w20 = 0.;
  /* #427: (@41[1] = @20) */
  for (rr=w41+1, ss=(&w20); rr!=w41+2; rr+=1) *rr = *ss++;
  /* #428: @20 = @21[3] */
  for (rr=(&w20), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #429: (@41[1] += @20) */
  for (rr=w41+1, ss=(&w20); rr!=w41+2; rr+=1) *rr += *ss++;
  /* #430: @20 = 0 */
  w20 = 0.;
  /* #431: (@41[2] = @20) */
  for (rr=w41+2, ss=(&w20); rr!=w41+3; rr+=1) *rr = *ss++;
  /* #432: @20 = @21[2] */
  for (rr=(&w20), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #433: @20 = (-@20) */
  w20 = (- w20 );
  /* #434: (@41[2] += @20) */
  for (rr=w41+2, ss=(&w20); rr!=w41+3; rr+=1) *rr += *ss++;
  /* #435: @20 = 0 */
  w20 = 0.;
  /* #436: (@41[5] = @20) */
  for (rr=w41+5, ss=(&w20); rr!=w41+6; rr+=1) *rr = *ss++;
  /* #437: @20 = @21[1] */
  for (rr=(&w20), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #438: (@41[5] += @20) */
  for (rr=w41+5, ss=(&w20); rr!=w41+6; rr+=1) *rr += *ss++;
  /* #439: @2 = mac(@12,@41,@2) */
  for (i=0, rr=w2; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w41+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #440: @12 = zeros(3x3) */
  casadi_clear(w12, 9);
  /* #441: @3 = (2.*@41) */
  for (i=0, rr=w3, cs=w41; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #442: @12 = mac(@3,@4,@12) */
  for (i=0, rr=w12; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #443: @2 = (@2+@12) */
  for (i=0, rr=w2, cs=w12; i<9; ++i) (*rr++) += (*cs++);
  /* #444: @20 = @21[0] */
  for (rr=(&w20), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #445: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #446: @4 = (@4*@20) */
  for (i=0, rr=w4; i<9; ++i) (*rr++) *= w20;
  /* #447: @41 = (@7*@41) */
  for (i=0, rr=w41, cs=w41; i<9; ++i) (*rr++)  = (w7*(*cs++));
  /* #448: @4 = (@4+@41) */
  for (i=0, rr=w4, cs=w41; i<9; ++i) (*rr++) += (*cs++);
  /* #449: @2 = (@2+@4) */
  for (i=0, rr=w2, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #450: @38 = zeros(3x1,0nz) */
  /* #451: @4 = horzcat(@37, @2, @38) */
  rr=w4;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #452: @2 = @4' */
  casadi_trans(w4,casadi_s16, w2, casadi_s15, iw);
  /* #453: @37 = zeros(11x4,0nz) */
  /* #454: @38 = zeros(11x4,0nz) */
  /* #455: @4 = horzcat(@2, @37, @38) */
  rr=w4;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #456: @2 = @4' */
  casadi_trans(w4,casadi_s18, w2, casadi_s17, iw);
  /* #457: @35 = mac(@2,@5,@35) */
  casadi_mtimes(w2, casadi_s17, w5, casadi_s4, w35, casadi_s4, w, 0);
  /* #458: @0 = (@0+@35) */
  for (i=0, rr=w0, cs=w35; i<11; ++i) (*rr++) += (*cs++);
  /* #459: (@36[10:175:15] = @0) */
  for (rr=w36+10, ss=w0; rr!=w36+175; rr+=15) *rr = *ss++;
  /* #460: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #461: @7 = ones(15x1,1nz) */
  w7 = 1.;
  /* #462: {NULL, @20} = vertsplit(@7) */
  w20 = w7;
  /* #463: @0 = mac(@34,@20,@0) */
  casadi_mtimes(w34, casadi_s11, (&w20), casadi_s22, w0, casadi_s4, w, 0);
  /* #464: (@36[11:176:15] = @0) */
  for (rr=w36+11, ss=w0; rr!=w36+176; rr+=15) *rr = *ss++;
  /* #465: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #466: @20 = ones(15x1,1nz) */
  w20 = 1.;
  /* #467: {NULL, @7} = vertsplit(@20) */
  w7 = w20;
  /* #468: @0 = mac(@34,@7,@0) */
  casadi_mtimes(w34, casadi_s11, (&w7), casadi_s23, w0, casadi_s4, w, 0);
  /* #469: (@36[12:177:15] = @0) */
  for (rr=w36+12, ss=w0; rr!=w36+177; rr+=15) *rr = *ss++;
  /* #470: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #471: @7 = ones(15x1,1nz) */
  w7 = 1.;
  /* #472: {NULL, @20} = vertsplit(@7) */
  w20 = w7;
  /* #473: @0 = mac(@34,@20,@0) */
  casadi_mtimes(w34, casadi_s11, (&w20), casadi_s24, w0, casadi_s4, w, 0);
  /* #474: (@36[13:178:15] = @0) */
  for (rr=w36+13, ss=w0; rr!=w36+178; rr+=15) *rr = *ss++;
  /* #475: @0 = zeros(11x1) */
  casadi_clear(w0, 11);
  /* #476: @20 = ones(15x1,1nz) */
  w20 = 1.;
  /* #477: {NULL, @7} = vertsplit(@20) */
  w7 = w20;
  /* #478: @0 = mac(@34,@7,@0) */
  casadi_mtimes(w34, casadi_s11, (&w7), casadi_s25, w0, casadi_s4, w, 0);
  /* #479: @35 = zeros(11x1) */
  casadi_clear(w35, 11);
  /* #480: @37 = zeros(11x3,0nz) */
  /* #481: @38 = zeros(4x3,0nz) */
  /* #482: @39 = 00 */
  /* #483: @40 = 00 */
  /* #484: @43 = 00 */
  /* #485: @20 = @7[0] */
  for (rr=(&w20), ss=(&w7)+0; ss!=(&w7)+1; ss+=1) *rr++ = *ss;
  /* #486: @7 = (-@20) */
  w7 = (- w20 );
  /* #487: @6 = horzcat(@39, @40, @43, @7) */
  rr=(&w6);
  *rr++ = w7;
  /* #488: @6 = @6' */
  /* #489: @39 = 00 */
  /* #490: @40 = 00 */
  /* #491: @43 = 00 */
  /* #492: @7 = horzcat(@39, @40, @20, @43) */
  rr=(&w7);
  *rr++ = w20;
  /* #493: @7 = @7' */
  /* #494: @39 = 00 */
  /* #495: @18 = (-@20) */
  w18 = (- w20 );
  /* #496: @40 = 00 */
  /* #497: @43 = 00 */
  /* #498: @19 = horzcat(@39, @18, @40, @43) */
  rr=(&w19);
  *rr++ = w18;
  /* #499: @19 = @19' */
  /* #500: @39 = 00 */
  /* #501: @40 = 00 */
  /* #502: @43 = 00 */
  /* #503: @18 = horzcat(@20, @39, @40, @43) */
  rr=(&w18);
  *rr++ = w20;
  /* #504: @18 = @18' */
  /* #505: @21 = horzcat(@6, @7, @19, @18) */
  rr=w21;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w19;
  *rr++ = w18;
  /* #506: @11 = @21' */
  casadi_trans(w21,casadi_s26, w11, casadi_s26, iw);
  /* #507: @11 = (@8*@11) */
  for (i=0, rr=w11, cs=w11; i<4; ++i) (*rr++)  = (w8*(*cs++));
  /* #508: @39 = zeros(4x4,0nz) */
  /* #509: @21 = horzcat(@38, @11, @39) */
  rr=w21;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #510: @11 = @21' */
  casadi_trans(w21,casadi_s28, w11, casadi_s27, iw);
  /* #511: @38 = zeros(4x7,0nz) */
  /* #512: @30 = zeros(4x4) */
  casadi_clear(w30, 16);
  /* #513: @26 = zeros(4x4) */
  casadi_clear(w26, 16);
  /* #514: @9 = (@9*@20) */
  w9 *= w20;
  /* #515: (@26[4] += @9) */
  for (rr=w26+4, ss=(&w9); rr!=w26+5; rr+=1) *rr += *ss++;
  /* #516: @9 = 0 */
  w9 = 0.;
  /* #517: (@26[8] = @9) */
  for (rr=w26+8, ss=(&w9); rr!=w26+9; rr+=1) *rr = *ss++;
  /* #518: @9 = 0 */
  w9 = 0.;
  /* #519: (@26[12] = @9) */
  for (rr=w26+12, ss=(&w9); rr!=w26+13; rr+=1) *rr = *ss++;
  /* #520: @9 = 0 */
  w9 = 0.;
  /* #521: (@26[1] = @9) */
  for (rr=w26+1, ss=(&w9); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #522: @17 = (@17*@20) */
  w17 *= w20;
  /* #523: (@26[1] += @17) */
  for (rr=w26+1, ss=(&w17); rr!=w26+2; rr+=1) *rr += *ss++;
  /* #524: @17 = 0 */
  w17 = 0.;
  /* #525: (@26[5] = @17) */
  for (rr=w26+5, ss=(&w17); rr!=w26+6; rr+=1) *rr = *ss++;
  /* #526: @17 = 0 */
  w17 = 0.;
  /* #527: (@26[9] = @17) */
  for (rr=w26+9, ss=(&w17); rr!=w26+10; rr+=1) *rr = *ss++;
  /* #528: @17 = 0 */
  w17 = 0.;
  /* #529: (@26[13] = @17) */
  for (rr=w26+13, ss=(&w17); rr!=w26+14; rr+=1) *rr = *ss++;
  /* #530: @17 = 0 */
  w17 = 0.;
  /* #531: (@26[2] = @17) */
  for (rr=w26+2, ss=(&w17); rr!=w26+3; rr+=1) *rr = *ss++;
  /* #532: @17 = 0 */
  w17 = 0.;
  /* #533: (@26[6] = @17) */
  for (rr=w26+6, ss=(&w17); rr!=w26+7; rr+=1) *rr = *ss++;
  /* #534: @17 = 0 */
  w17 = 0.;
  /* #535: (@26[10] = @17) */
  for (rr=w26+10, ss=(&w17); rr!=w26+11; rr+=1) *rr = *ss++;
  /* #536: @17 = 0 */
  w17 = 0.;
  /* #537: (@26[14] = @17) */
  for (rr=w26+14, ss=(&w17); rr!=w26+15; rr+=1) *rr = *ss++;
  /* #538: @17 = 0 */
  w17 = 0.;
  /* #539: (@26[3] = @17) */
  for (rr=w26+3, ss=(&w17); rr!=w26+4; rr+=1) *rr = *ss++;
  /* #540: @17 = 0 */
  w17 = 0.;
  /* #541: (@26[7] = @17) */
  for (rr=w26+7, ss=(&w17); rr!=w26+8; rr+=1) *rr = *ss++;
  /* #542: @17 = 0 */
  w17 = 0.;
  /* #543: (@26[11] = @17) */
  for (rr=w26+11, ss=(&w17); rr!=w26+12; rr+=1) *rr = *ss++;
  /* #544: @17 = 0 */
  w17 = 0.;
  /* #545: (@26[15] = @17) */
  for (rr=w26+15, ss=(&w17); rr!=w26+16; rr+=1) *rr = *ss++;
  /* #546: @30 = mac(@25,@26,@30) */
  for (i=0, rr=w30; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w25+j, tt=w26+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #547: @30 = (-@30) */
  for (i=0, rr=w30, cs=w30; i<16; ++i) *rr++ = (- *cs++ );
  /* #548: @25 = horzcat(@38, @30) */
  rr=w25;
  for (i=0, cs=w30; i<16; ++i) *rr++ = *cs++;
  /* #549: @30 = @25' */
  casadi_trans(w25,casadi_s30, w30, casadi_s29, iw);
  /* #550: @44 = horzcat(@37, @11, @30) */
  rr=w44;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<16; ++i) *rr++ = *cs++;
  /* #551: @45 = @44' */
  casadi_trans(w44,casadi_s31, w45, casadi_s31, iw);
  /* #552: @35 = mac(@45,@5,@35) */
  casadi_mtimes(w45, casadi_s31, w5, casadi_s4, w35, casadi_s4, w, 0);
  /* #553: @0 = (@0+@35) */
  for (i=0, rr=w0, cs=w35; i<11; ++i) (*rr++) += (*cs++);
  /* #554: (@36[14:179:15] = @0) */
  for (rr=w36+14, ss=w0; rr!=w36+179; rr+=15) *rr = *ss++;
  /* #555: output[1][0] = @36 */
  casadi_copy(w36, 165, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_dyn_disc_phi_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_dyn_disc_phi_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_dyn_disc_phi_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s32;
    case 2: return casadi_s33;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s34;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 12;
  if (sz_w) *sz_w = 903;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
