/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c10 CASADI_PREFIX(c10)
#define casadi_c11 CASADI_PREFIX(c11)
#define casadi_c12 CASADI_PREFIX(c12)
#define casadi_c13 CASADI_PREFIX(c13)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_c9 CASADI_PREFIX(c9)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[8] = {3, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s1[7] = {3, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s2[9] = {3, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s3[10] = {3, 3, 0, 2, 3, 4, 0, 1, 0, 0};
static const casadi_int casadi_s4[11] = {3, 3, 0, 2, 4, 5, 0, 1, 0, 1, 0};
static const casadi_int casadi_s5[12] = {3, 3, 0, 2, 4, 6, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s6[13] = {3, 3, 0, 3, 5, 7, 0, 1, 2, 0, 1, 0, 1};
static const casadi_int casadi_s7[14] = {3, 3, 0, 3, 6, 8, 0, 1, 2, 0, 1, 2, 0, 1};
static const casadi_int casadi_s8[24] = {7, 7, 0, 2, 4, 6, 8, 10, 12, 14, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s9[17] = {7, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s10[31] = {7, 7, 0, 3, 6, 9, 12, 15, 18, 21, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s11[38] = {7, 7, 0, 4, 8, 12, 16, 20, 24, 28, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s12[45] = {7, 7, 0, 5, 10, 15, 20, 25, 30, 35, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s13[52] = {7, 7, 0, 6, 12, 18, 24, 30, 36, 42, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s14[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s15[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s16[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};

static const casadi_real casadi_c0[7] = {-4.6620000000000000e-01, 2.8700000000000000e-02, -9.5999999999999992e-03, 5.1999999999999998e-02, -2.7310000000000001e-01, 3.8279999999999997e-01, -8.3900000000000002e-02};
static const casadi_real casadi_c1[7] = {-9.9099999999999994e-02, -1.8609999999999999e-01, 5.4139999999999999e-01, -6.4899999999999999e-02, -2.9580000000000001e-01, 1.6000000000000001e-03, -7.7999999999999996e-03};
static const casadi_real casadi_c2[7] = {5.1999999999999998e-03, 8.6000000000000000e-03, -3.4996000000000000e+00, 8.3999999999999995e-03, -6.1999999999999998e-03, 1.3700000000000000e-02, 9.2999999999999992e-03};
static const casadi_real casadi_c3[7] = {-5.5100000000000003e-02, 1.2559999999999999e-01, -7.5449999999999995e-01, -8.8798999999999992e+00, -5.0400000000000000e-02, -4.0810000000000002e-01, 2.0480000000000001e-01};
static const casadi_real casadi_c4[7] = {8.8700000000000001e-02, -6.7000000000000004e-02, -9.1300000000000006e-02, -3.4599999999999999e-02, -6.2092000000000001e+00, -2.6750000000000002e-01, 1.4610000000000001e-01};
static const casadi_real casadi_c5[7] = {2.2600000000000001e-01, -3.1150000000000000e-01, 1.1240000000000001e+00, 1.2000000000000000e-01, -9.0899999999999995e-02, -9.4261999999999997e+00, 9.6870000000000001e-01};
static const casadi_real casadi_c6[7] = {-7.9699999999999993e-02, -1.2039999999999999e-01, 1.0320000000000000e-01, -6.5199999999999994e-02, -3.5510000000000003e-01, 4.7720000000000001e-01, -1.1037300000000000e+01};
static const casadi_real casadi_c7[7] = {5.9689999999999999e-01, 8.7900000000000006e-02, -6.6199999999999995e-02, -4.2299999999999997e-02, 2.2270000000000001e-01, -3.0880000000000002e-01, 3.5499999999999997e-02};
static const casadi_real casadi_c8[7] = {9.7600000000000006e-02, 4.0410000000000001e-01, -5.1049999999999995e-01, 6.9800000000000001e-02, 2.4859999999999999e-01, -6.8999999999999999e-03, 2.5800000000000000e-02};
static const casadi_real casadi_c9[7] = {-1.3599999999999999e-02, -1.0699999999999999e-02, 3.5091999999999999e+00, -9.7000000000000003e-03, 8.0000000000000002e-03, -1.0699999999999999e-02, -1.1200000000000000e-02};
static const casadi_real casadi_c10[7] = {6.7500000000000004e-02, -1.4749999999999999e-01, 8.5770000000000002e-01, 8.9286999999999992e+00, 1.3519999999999999e-01, 4.2259999999999998e-01, -1.5359999999999999e-01};
static const casadi_real casadi_c11[7] = {-6.5699999999999995e-02, 4.2200000000000001e-02, -5.7200000000000001e-02, 5.1400000000000001e-02, 6.3037999999999998e+00, 3.0330000000000001e-01, -1.5790000000000001e-01};
static const casadi_real casadi_c12[7] = {-1.0580000000000001e-01, 7.4300000000000005e-02, -8.7739999999999996e-01, -1.2780000000000000e-01, 2.4520000000000000e-01, 8.9981000000000009e+00, -9.9360000000000004e-01};
static const casadi_real casadi_c13[7] = {-1.8200000000000000e-01, 8.1199999999999994e-02, -2.0880000000000001e-01, 7.2999999999999995e-02, 3.0070000000000002e-01, -5.0670000000000004e-01, 1.0965999999999999e+01};

/* Drone_ode_expl_ode_fun:(i0[21],i1[7],i2[30])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+7, *w1=w+11, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+51, w15, w16, w17, w18, *w19=w+62, *w20=w+66, *w21=w+70, *w22=w+74, *w23=w+78, *w24=w+94, *w25=w+110, *w26=w+113, *w27=w+115, *w28=w+118, *w29=w+123, *w30=w+129, *w31=w+137, *w32=w+146, *w33=w+153, *w34=w+160, *w35=w+174, *w36=w+195, *w37=w+230, *w38=w+272, *w39=w+321;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = zeros(4x7) */
  casadi_clear(w1, 28);
  /* #2: @2 = input[0][4] */
  w2 = arg[0] ? arg[0][4] : 0;
  /* #3: @3 = input[0][7] */
  w3 = arg[0] ? arg[0][7] : 0;
  /* #4: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #5: @5 = input[0][5] */
  w5 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w6 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = (@5*@6) */
  w7  = (w5*w6);
  /* #8: @4 = (@4+@7) */
  w4 += w7;
  /* #9: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #10: @7 = 1 */
  w7 = 1.;
  /* #11: @8 = sq(@6) */
  w8 = casadi_sq( w6 );
  /* #12: @9 = sq(@3) */
  w9 = casadi_sq( w3 );
  /* #13: @8 = (@8+@9) */
  w8 += w9;
  /* #14: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #15: @7 = (@7-@8) */
  w7 -= w8;
  /* #16: @4 = atan2(@4,@7) */
  w4  = atan2(w4,w7);
  /* #17: @7 = cos(@4) */
  w7 = cos( w4 );
  /* #18: (@1[0] = @7) */
  for (rr=w1+0, ss=(&w7); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #19: @7 = sin(@4) */
  w7 = sin( w4 );
  /* #20: @7 = (-@7) */
  w7 = (- w7 );
  /* #21: (@1[4] = @7) */
  for (rr=w1+4, ss=(&w7); rr!=w1+5; rr+=1) *rr = *ss++;
  /* #22: @7 = 0 */
  w7 = 0.;
  /* #23: (@1[8] = @7) */
  for (rr=w1+8, ss=(&w7); rr!=w1+9; rr+=1) *rr = *ss++;
  /* #24: @7 = input[0][11] */
  w7 = arg[0] ? arg[0][11] : 0;
  /* #25: @8 = (@4+@7) */
  w8  = (w4+w7);
  /* #26: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #27: @9 = 0.45 */
  w9 = 4.5000000000000001e-01;
  /* #28: @10 = input[0][12] */
  w10 = arg[0] ? arg[0][12] : 0;
  /* #29: @11 = input[0][13] */
  w11 = arg[0] ? arg[0][13] : 0;
  /* #30: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #31: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #32: @9 = (@9*@12) */
  w9 *= w12;
  /* #33: @12 = 0.44 */
  w12 = 4.4000000000000000e-01;
  /* #34: @13 = cos(@10) */
  w13 = cos( w10 );
  /* #35: @12 = (@12*@13) */
  w12 *= w13;
  /* #36: @9 = (@9+@12) */
  w9 += w12;
  /* #37: @8 = (@8*@9) */
  w8 *= w9;
  /* #38: @8 = (-@8) */
  w8 = (- w8 );
  /* #39: (@1[12] = @8) */
  for (rr=w1+12, ss=(&w8); rr!=w1+13; rr+=1) *rr = *ss++;
  /* #40: @8 = (@4+@7) */
  w8  = (w4+w7);
  /* #41: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #42: @9 = 0.45 */
  w9 = 4.5000000000000001e-01;
  /* #43: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #44: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #45: @9 = (@9*@12) */
  w9 *= w12;
  /* #46: @12 = 0.44 */
  w12 = 4.4000000000000000e-01;
  /* #47: @13 = cos(@10) */
  w13 = cos( w10 );
  /* #48: @12 = (@12*@13) */
  w12 *= w13;
  /* #49: @9 = (@9+@12) */
  w9 += w12;
  /* #50: @8 = (@8*@9) */
  w8 *= w9;
  /* #51: @8 = (-@8) */
  w8 = (- w8 );
  /* #52: (@1[16] = @8) */
  for (rr=w1+16, ss=(&w8); rr!=w1+17; rr+=1) *rr = *ss++;
  /* #53: @8 = (@4+@7) */
  w8  = (w4+w7);
  /* #54: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #55: @9 = 0.45 */
  w9 = 4.5000000000000001e-01;
  /* #56: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #57: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #58: @9 = (@9*@12) */
  w9 *= w12;
  /* #59: @12 = 0.44 */
  w12 = 4.4000000000000000e-01;
  /* #60: @13 = sin(@10) */
  w13 = sin( w10 );
  /* #61: @12 = (@12*@13) */
  w12 *= w13;
  /* #62: @9 = (@9+@12) */
  w9 += w12;
  /* #63: @8 = (@8*@9) */
  w8 *= w9;
  /* #64: @8 = (-@8) */
  w8 = (- w8 );
  /* #65: (@1[20] = @8) */
  for (rr=w1+20, ss=(&w8); rr!=w1+21; rr+=1) *rr = *ss++;
  /* #66: @8 = -0.45 */
  w8 = -4.5000000000000001e-01;
  /* #67: @9 = (@4+@7) */
  w9  = (w4+w7);
  /* #68: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #69: @8 = (@8*@9) */
  w8 *= w9;
  /* #70: @9 = (@10+@11) */
  w9  = (w10+w11);
  /* #71: @9 = sin(@9) */
  w9 = sin( w9 );
  /* #72: @8 = (@8*@9) */
  w8 *= w9;
  /* #73: (@1[24] = @8) */
  for (rr=w1+24, ss=(&w8); rr!=w1+25; rr+=1) *rr = *ss++;
  /* #74: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #75: (@1[1] = @8) */
  for (rr=w1+1, ss=(&w8); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #76: @8 = cos(@4) */
  w8 = cos( w4 );
  /* #77: (@1[5] = @8) */
  for (rr=w1+5, ss=(&w8); rr!=w1+6; rr+=1) *rr = *ss++;
  /* #78: @8 = 0 */
  w8 = 0.;
  /* #79: (@1[9] = @8) */
  for (rr=w1+9, ss=(&w8); rr!=w1+10; rr+=1) *rr = *ss++;
  /* #80: @8 = (@4+@7) */
  w8  = (w4+w7);
  /* #81: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #82: @9 = 0.45 */
  w9 = 4.5000000000000001e-01;
  /* #83: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #84: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #85: @9 = (@9*@12) */
  w9 *= w12;
  /* #86: @12 = 0.44 */
  w12 = 4.4000000000000000e-01;
  /* #87: @13 = cos(@10) */
  w13 = cos( w10 );
  /* #88: @12 = (@12*@13) */
  w12 *= w13;
  /* #89: @9 = (@9+@12) */
  w9 += w12;
  /* #90: @8 = (@8*@9) */
  w8 *= w9;
  /* #91: (@1[13] = @8) */
  for (rr=w1+13, ss=(&w8); rr!=w1+14; rr+=1) *rr = *ss++;
  /* #92: @8 = (@4+@7) */
  w8  = (w4+w7);
  /* #93: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #94: @9 = 0.45 */
  w9 = 4.5000000000000001e-01;
  /* #95: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #96: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #97: @9 = (@9*@12) */
  w9 *= w12;
  /* #98: @12 = 0.44 */
  w12 = 4.4000000000000000e-01;
  /* #99: @13 = cos(@10) */
  w13 = cos( w10 );
  /* #100: @12 = (@12*@13) */
  w12 *= w13;
  /* #101: @9 = (@9+@12) */
  w9 += w12;
  /* #102: @8 = (@8*@9) */
  w8 *= w9;
  /* #103: (@1[17] = @8) */
  for (rr=w1+17, ss=(&w8); rr!=w1+18; rr+=1) *rr = *ss++;
  /* #104: @8 = (@4+@7) */
  w8  = (w4+w7);
  /* #105: @8 = sin(@8) */
  w8 = sin( w8 );
  /* #106: @9 = 0.45 */
  w9 = 4.5000000000000001e-01;
  /* #107: @12 = (@10+@11) */
  w12  = (w10+w11);
  /* #108: @12 = sin(@12) */
  w12 = sin( w12 );
  /* #109: @9 = (@9*@12) */
  w9 *= w12;
  /* #110: @12 = 0.44 */
  w12 = 4.4000000000000000e-01;
  /* #111: @13 = sin(@10) */
  w13 = sin( w10 );
  /* #112: @12 = (@12*@13) */
  w12 *= w13;
  /* #113: @9 = (@9+@12) */
  w9 += w12;
  /* #114: @8 = (@8*@9) */
  w8 *= w9;
  /* #115: @8 = (-@8) */
  w8 = (- w8 );
  /* #116: (@1[21] = @8) */
  for (rr=w1+21, ss=(&w8); rr!=w1+22; rr+=1) *rr = *ss++;
  /* #117: @8 = -0.45 */
  w8 = -4.5000000000000001e-01;
  /* #118: @4 = (@4+@7) */
  w4 += w7;
  /* #119: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #120: @8 = (@8*@4) */
  w8 *= w4;
  /* #121: @4 = (@10+@11) */
  w4  = (w10+w11);
  /* #122: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #123: @8 = (@8*@4) */
  w8 *= w4;
  /* #124: (@1[25] = @8) */
  for (rr=w1+25, ss=(&w8); rr!=w1+26; rr+=1) *rr = *ss++;
  /* #125: @8 = 0 */
  w8 = 0.;
  /* #126: (@1[2] = @8) */
  for (rr=w1+2, ss=(&w8); rr!=w1+3; rr+=1) *rr = *ss++;
  /* #127: @8 = 0 */
  w8 = 0.;
  /* #128: (@1[6] = @8) */
  for (rr=w1+6, ss=(&w8); rr!=w1+7; rr+=1) *rr = *ss++;
  /* #129: @8 = 1 */
  w8 = 1.;
  /* #130: (@1[10] = @8) */
  for (rr=w1+10, ss=(&w8); rr!=w1+11; rr+=1) *rr = *ss++;
  /* #131: @8 = 0 */
  w8 = 0.;
  /* #132: (@1[14] = @8) */
  for (rr=w1+14, ss=(&w8); rr!=w1+15; rr+=1) *rr = *ss++;
  /* #133: @8 = 0 */
  w8 = 0.;
  /* #134: (@1[18] = @8) */
  for (rr=w1+18, ss=(&w8); rr!=w1+19; rr+=1) *rr = *ss++;
  /* #135: @8 = -0.45 */
  w8 = -4.5000000000000001e-01;
  /* #136: @4 = (@10+@11) */
  w4  = (w10+w11);
  /* #137: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #138: @8 = (@8*@4) */
  w8 *= w4;
  /* #139: @4 = 0.44 */
  w4 = 4.4000000000000000e-01;
  /* #140: @7 = cos(@10) */
  w7 = cos( w10 );
  /* #141: @4 = (@4*@7) */
  w4 *= w7;
  /* #142: @8 = (@8-@4) */
  w8 -= w4;
  /* #143: (@1[22] = @8) */
  for (rr=w1+22, ss=(&w8); rr!=w1+23; rr+=1) *rr = *ss++;
  /* #144: @8 = -0.45 */
  w8 = -4.5000000000000001e-01;
  /* #145: @10 = (@10+@11) */
  w10 += w11;
  /* #146: @10 = cos(@10) */
  w10 = cos( w10 );
  /* #147: @8 = (@8*@10) */
  w8 *= w10;
  /* #148: (@1[26] = @8) */
  for (rr=w1+26, ss=(&w8); rr!=w1+27; rr+=1) *rr = *ss++;
  /* #149: @8 = 0 */
  w8 = 0.;
  /* #150: (@1[3] = @8) */
  for (rr=w1+3, ss=(&w8); rr!=w1+4; rr+=1) *rr = *ss++;
  /* #151: @8 = 0 */
  w8 = 0.;
  /* #152: (@1[7] = @8) */
  for (rr=w1+7, ss=(&w8); rr!=w1+8; rr+=1) *rr = *ss++;
  /* #153: @8 = 0 */
  w8 = 0.;
  /* #154: (@1[11] = @8) */
  for (rr=w1+11, ss=(&w8); rr!=w1+12; rr+=1) *rr = *ss++;
  /* #155: @8 = 1 */
  w8 = 1.;
  /* #156: (@1[15] = @8) */
  for (rr=w1+15, ss=(&w8); rr!=w1+16; rr+=1) *rr = *ss++;
  /* #157: @8 = 0 */
  w8 = 0.;
  /* #158: (@1[19] = @8) */
  for (rr=w1+19, ss=(&w8); rr!=w1+20; rr+=1) *rr = *ss++;
  /* #159: @8 = 0 */
  w8 = 0.;
  /* #160: (@1[23] = @8) */
  for (rr=w1+23, ss=(&w8); rr!=w1+24; rr+=1) *rr = *ss++;
  /* #161: @8 = 0 */
  w8 = 0.;
  /* #162: (@1[27] = @8) */
  for (rr=w1+27, ss=(&w8); rr!=w1+28; rr+=1) *rr = *ss++;
  /* #163: @8 = input[0][14] */
  w8 = arg[0] ? arg[0][14] : 0;
  /* #164: @10 = input[0][15] */
  w10 = arg[0] ? arg[0][15] : 0;
  /* #165: @11 = input[0][16] */
  w11 = arg[0] ? arg[0][16] : 0;
  /* #166: @4 = input[0][17] */
  w4 = arg[0] ? arg[0][17] : 0;
  /* #167: @7 = input[0][18] */
  w7 = arg[0] ? arg[0][18] : 0;
  /* #168: @9 = input[0][19] */
  w9 = arg[0] ? arg[0][19] : 0;
  /* #169: @12 = input[0][20] */
  w12 = arg[0] ? arg[0][20] : 0;
  /* #170: @14 = vertcat(@8, @10, @11, @4, @7, @9, @12) */
  rr=w14;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w12;
  /* #171: @0 = mac(@1,@14,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w1+j, tt=w14+i*7; k<7; ++k) *rr += ss[k*4]**tt++;
  /* #172: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #173: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #174: @13 = 0.5 */
  w13 = 5.0000000000000000e-01;
  /* #175: @15 = 0 */
  w15 = 0.;
  /* #176: @16 = 0 */
  w16 = 0.;
  /* #177: @17 = 0 */
  w17 = 0.;
  /* #178: @18 = (-@4) */
  w18 = (- w4 );
  /* #179: @19 = horzcat(@15, @16, @17, @18) */
  rr=w19;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #180: @19 = @19' */
  /* #181: @15 = 0 */
  w15 = 0.;
  /* #182: @16 = 0 */
  w16 = 0.;
  /* #183: @17 = 0 */
  w17 = 0.;
  /* #184: @20 = horzcat(@15, @16, @4, @17) */
  rr=w20;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w4;
  *rr++ = w17;
  /* #185: @20 = @20' */
  /* #186: @15 = 0 */
  w15 = 0.;
  /* #187: @16 = (-@4) */
  w16 = (- w4 );
  /* #188: @17 = 0 */
  w17 = 0.;
  /* #189: @18 = 0 */
  w18 = 0.;
  /* #190: @21 = horzcat(@15, @16, @17, @18) */
  rr=w21;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #191: @21 = @21' */
  /* #192: @15 = 0 */
  w15 = 0.;
  /* #193: @16 = 0 */
  w16 = 0.;
  /* #194: @17 = 0 */
  w17 = 0.;
  /* #195: @22 = horzcat(@4, @15, @16, @17) */
  rr=w22;
  *rr++ = w4;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #196: @22 = @22' */
  /* #197: @23 = horzcat(@19, @20, @21, @22) */
  rr=w23;
  for (i=0, cs=w19; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<4; ++i) *rr++ = *cs++;
  /* #198: @24 = @23' */
  for (i=0, rr=w24, cs=w23; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #199: @24 = (@13*@24) */
  for (i=0, rr=w24, cs=w24; i<16; ++i) (*rr++)  = (w13*(*cs++));
  /* #200: @19 = vertcat(@2, @5, @6, @3) */
  rr=w19;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w3;
  /* #201: @0 = mac(@24,@19,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w24+j, tt=w19+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #202: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 4, res[0]+4);
  /* #203: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #204: @13 = zeros(3x3,1nz) */
  w13 = 0.;
  /* #205: @2 = (@2*@3) */
  w2 *= w3;
  /* #206: @5 = (@5*@6) */
  w5 *= w6;
  /* #207: @2 = (@2+@5) */
  w2 += w5;
  /* #208: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #209: @5 = 1 */
  w5 = 1.;
  /* #210: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #211: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #212: @6 = (@6+@3) */
  w6 += w3;
  /* #213: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #214: @5 = (@5-@6) */
  w5 -= w6;
  /* #215: @2 = atan2(@2,@5) */
  w2  = atan2(w2,w5);
  /* #216: @5 = cos(@2) */
  w5 = cos( w2 );
  /* #217: (@13[0] = @5) */
  for (rr=(&w13)+0, ss=(&w5); rr!=(&w13)+1; rr+=1) *rr = *ss++;
  /* #218: @26 = project(@13) */
  casadi_project((&w13), casadi_s1, w26, casadi_s0, w);
  /* #219: @13 = sin(@2) */
  w13 = sin( w2 );
  /* #220: @13 = (-@13) */
  w13 = (- w13 );
  /* #221: (@26[1] = @13) */
  for (rr=w26+1, ss=(&w13); rr!=w26+2; rr+=1) *rr = *ss++;
  /* #222: @27 = project(@26) */
  casadi_project(w26, casadi_s0, w27, casadi_s2, w);
  /* #223: @13 = 0 */
  w13 = 0.;
  /* #224: (@27[2] = @13) */
  for (rr=w27+2, ss=(&w13); rr!=w27+3; rr+=1) *rr = *ss++;
  /* #225: @0 = project(@27) */
  casadi_project(w27, casadi_s2, w0, casadi_s3, w);
  /* #226: @13 = sin(@2) */
  w13 = sin( w2 );
  /* #227: (@0[1] = @13) */
  for (rr=w0+1, ss=(&w13); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #228: @28 = project(@0) */
  casadi_project(w0, casadi_s3, w28, casadi_s4, w);
  /* #229: @2 = cos(@2) */
  w2 = cos( w2 );
  /* #230: (@28[3] = @2) */
  for (rr=w28+3, ss=(&w2); rr!=w28+4; rr+=1) *rr = *ss++;
  /* #231: @29 = project(@28) */
  casadi_project(w28, casadi_s4, w29, casadi_s5, w);
  /* #232: @2 = 0 */
  w2 = 0.;
  /* #233: (@29[5] = @2) */
  for (rr=w29+5, ss=(&w2); rr!=w29+6; rr+=1) *rr = *ss++;
  /* #234: @14 = project(@29) */
  casadi_project(w29, casadi_s5, w14, casadi_s6, w);
  /* #235: @2 = 0 */
  w2 = 0.;
  /* #236: (@14[2] = @2) */
  for (rr=w14+2, ss=(&w2); rr!=w14+3; rr+=1) *rr = *ss++;
  /* #237: @30 = project(@14) */
  casadi_project(w14, casadi_s6, w30, casadi_s7, w);
  /* #238: @2 = 0 */
  w2 = 0.;
  /* #239: (@30[5] = @2) */
  for (rr=w30+5, ss=(&w2); rr!=w30+6; rr+=1) *rr = *ss++;
  /* #240: @31 = dense(@30) */
  casadi_densify(w30, casadi_s7, w31, 0);
  /* #241: @2 = 1 */
  w2 = 1.;
  /* #242: (@31[8] = @2) */
  for (rr=w31+8, ss=(&w2); rr!=w31+9; rr+=1) *rr = *ss++;
  /* #243: @27 = vertcat(@8, @10, @11) */
  rr=w27;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  /* #244: @25 = mac(@31,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w31+j, tt=w27+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #245: output[0][2] = @25 */
  if (res[0]) casadi_copy(w25, 3, res[0]+8);
  /* #246: output[0][3] = @7 */
  if (res[0]) res[0][11] = w7;
  /* #247: output[0][4] = @9 */
  if (res[0]) res[0][12] = w9;
  /* #248: output[0][5] = @12 */
  if (res[0]) res[0][13] = w12;
  /* #249: @14 = zeros(7x1) */
  casadi_clear(w14, 7);
  /* #250: @32 = zeros(7x7,7nz) */
  casadi_clear(w32, 7);
  /* #251: @33 = [-0.4662, 0.0287, -0.0096, 0.052, -0.2731, 0.3828, -0.0839] */
  casadi_copy(casadi_c0, 7, w33);
  /* #252: @33 = @33' */
  /* #253: (@32[:7] = @33) */
  for (rr=w32+0, ss=w33; rr!=w32+7; rr+=1) *rr = *ss++;
  /* #254: @34 = project(@32) */
  casadi_project(w32, casadi_s9, w34, casadi_s8, w);
  /* #255: @32 = [-0.0991, -0.1861, 0.5414, -0.0649, -0.2958, 0.0016, -0.0078] */
  casadi_copy(casadi_c1, 7, w32);
  /* #256: @32 = @32' */
  /* #257: (@34[1:15:2] = @32) */
  for (rr=w34+1, ss=w32; rr!=w34+15; rr+=2) *rr = *ss++;
  /* #258: @35 = project(@34) */
  casadi_project(w34, casadi_s8, w35, casadi_s10, w);
  /* #259: @32 = [0.0052, 0.0086, -3.4996, 0.0084, -0.0062, 0.0137, 0.0093] */
  casadi_copy(casadi_c2, 7, w32);
  /* #260: @32 = @32' */
  /* #261: (@35[2:23:3] = @32) */
  for (rr=w35+2, ss=w32; rr!=w35+23; rr+=3) *rr = *ss++;
  /* #262: @1 = project(@35) */
  casadi_project(w35, casadi_s10, w1, casadi_s11, w);
  /* #263: @32 = [-0.0551, 0.1256, -0.7545, -8.8799, -0.0504, -0.4081, 0.2048] */
  casadi_copy(casadi_c3, 7, w32);
  /* #264: @32 = @32' */
  /* #265: (@1[3:31:4] = @32) */
  for (rr=w1+3, ss=w32; rr!=w1+31; rr+=4) *rr = *ss++;
  /* #266: @36 = project(@1) */
  casadi_project(w1, casadi_s11, w36, casadi_s12, w);
  /* #267: @32 = [0.0887, -0.067, -0.0913, -0.0346, -6.2092, -0.2675, 0.1461] */
  casadi_copy(casadi_c4, 7, w32);
  /* #268: @32 = @32' */
  /* #269: (@36[4:39:5] = @32) */
  for (rr=w36+4, ss=w32; rr!=w36+39; rr+=5) *rr = *ss++;
  /* #270: @37 = project(@36) */
  casadi_project(w36, casadi_s12, w37, casadi_s13, w);
  /* #271: @32 = [0.226, -0.3115, 1.124, 0.12, -0.0909, -9.4262, 0.9687] */
  casadi_copy(casadi_c5, 7, w32);
  /* #272: @32 = @32' */
  /* #273: (@37[5:47:6] = @32) */
  for (rr=w37+5, ss=w32; rr!=w37+47; rr+=6) *rr = *ss++;
  /* #274: @38 = dense(@37) */
  casadi_densify(w37, casadi_s13, w38, 0);
  /* #275: @32 = [-0.0797, -0.1204, 0.1032, -0.0652, -0.3551, 0.4772, -11.0373] */
  casadi_copy(casadi_c6, 7, w32);
  /* #276: @32 = @32' */
  /* #277: (@38[6:55:7] = @32) */
  for (rr=w38+6, ss=w32; rr!=w38+55; rr+=7) *rr = *ss++;
  /* #278: @32 = vertcat(@8, @10, @11, @4, @7, @9, @12) */
  rr=w32;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w12;
  /* #279: @14 = mac(@38,@32,@14) */
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<7; ++j, ++rr) for (k=0, ss=w38+j, tt=w32+i*7; k<7; ++k) *rr += ss[k*7]**tt++;
  /* #280: @32 = zeros(7x1) */
  casadi_clear(w32, 7);
  /* #281: @33 = zeros(7x7,7nz) */
  casadi_clear(w33, 7);
  /* #282: @39 = [0.5969, 0.0879, -0.0662, -0.0423, 0.2227, -0.3088, 0.0355] */
  casadi_copy(casadi_c7, 7, w39);
  /* #283: @39 = @39' */
  /* #284: (@33[:7] = @39) */
  for (rr=w33+0, ss=w39; rr!=w33+7; rr+=1) *rr = *ss++;
  /* #285: @34 = project(@33) */
  casadi_project(w33, casadi_s9, w34, casadi_s8, w);
  /* #286: @33 = [0.0976, 0.4041, -0.5105, 0.0698, 0.2486, -0.0069, 0.0258] */
  casadi_copy(casadi_c8, 7, w33);
  /* #287: @33 = @33' */
  /* #288: (@34[1:15:2] = @33) */
  for (rr=w34+1, ss=w33; rr!=w34+15; rr+=2) *rr = *ss++;
  /* #289: @35 = project(@34) */
  casadi_project(w34, casadi_s8, w35, casadi_s10, w);
  /* #290: @33 = [-0.0136, -0.0107, 3.5092, -0.0097, 0.008, -0.0107, -0.0112] */
  casadi_copy(casadi_c9, 7, w33);
  /* #291: @33 = @33' */
  /* #292: (@35[2:23:3] = @33) */
  for (rr=w35+2, ss=w33; rr!=w35+23; rr+=3) *rr = *ss++;
  /* #293: @1 = project(@35) */
  casadi_project(w35, casadi_s10, w1, casadi_s11, w);
  /* #294: @33 = [0.0675, -0.1475, 0.8577, 8.9287, 0.1352, 0.4226, -0.1536] */
  casadi_copy(casadi_c10, 7, w33);
  /* #295: @33 = @33' */
  /* #296: (@1[3:31:4] = @33) */
  for (rr=w1+3, ss=w33; rr!=w1+31; rr+=4) *rr = *ss++;
  /* #297: @36 = project(@1) */
  casadi_project(w1, casadi_s11, w36, casadi_s12, w);
  /* #298: @33 = [-0.0657, 0.0422, -0.0572, 0.0514, 6.3038, 0.3033, -0.1579] */
  casadi_copy(casadi_c11, 7, w33);
  /* #299: @33 = @33' */
  /* #300: (@36[4:39:5] = @33) */
  for (rr=w36+4, ss=w33; rr!=w36+39; rr+=5) *rr = *ss++;
  /* #301: @37 = project(@36) */
  casadi_project(w36, casadi_s12, w37, casadi_s13, w);
  /* #302: @33 = [-0.1058, 0.0743, -0.8774, -0.1278, 0.2452, 8.9981, -0.9936] */
  casadi_copy(casadi_c12, 7, w33);
  /* #303: @33 = @33' */
  /* #304: (@37[5:47:6] = @33) */
  for (rr=w37+5, ss=w33; rr!=w37+47; rr+=6) *rr = *ss++;
  /* #305: @38 = dense(@37) */
  casadi_densify(w37, casadi_s13, w38, 0);
  /* #306: @33 = [-0.182, 0.0812, -0.2088, 0.073, 0.3007, -0.5067, 10.966] */
  casadi_copy(casadi_c13, 7, w33);
  /* #307: @33 = @33' */
  /* #308: (@38[6:55:7] = @33) */
  for (rr=w38+6, ss=w33; rr!=w38+55; rr+=7) *rr = *ss++;
  /* #309: @8 = input[1][0] */
  w8 = arg[1] ? arg[1][0] : 0;
  /* #310: @10 = input[1][1] */
  w10 = arg[1] ? arg[1][1] : 0;
  /* #311: @11 = input[1][2] */
  w11 = arg[1] ? arg[1][2] : 0;
  /* #312: @4 = input[1][3] */
  w4 = arg[1] ? arg[1][3] : 0;
  /* #313: @7 = input[1][4] */
  w7 = arg[1] ? arg[1][4] : 0;
  /* #314: @9 = input[1][5] */
  w9 = arg[1] ? arg[1][5] : 0;
  /* #315: @12 = input[1][6] */
  w12 = arg[1] ? arg[1][6] : 0;
  /* #316: @33 = vertcat(@8, @10, @11, @4, @7, @9, @12) */
  rr=w33;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w4;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w12;
  /* #317: @32 = mac(@38,@33,@32) */
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<7; ++j, ++rr) for (k=0, ss=w38+j, tt=w33+i*7; k<7; ++k) *rr += ss[k*7]**tt++;
  /* #318: @14 = (@14+@32) */
  for (i=0, rr=w14, cs=w32; i<7; ++i) (*rr++) += (*cs++);
  /* #319: output[0][6] = @14 */
  if (res[0]) casadi_copy(w14, 7, res[0]+14);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_expl_ode_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_expl_ode_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    case 1: return casadi_s15;
    case 2: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s14;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 328;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
