/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

static const casadi_int casadi_s0[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s1[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};

/* Drone_ode_cost_ext_cost_0_fun:(i0[21],i1[7],i2[0],i3[30])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+35, *w33=w+65, *w34=w+68, *w35=w+89, *w36=w+92, *w37=w+101, *w38=w+108, *w39=w+115, *w40=w+122, *w41=w+171, *w42=w+175;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][28] */
  w2 = arg[3] ? arg[3][28] : 0;
  /* #3: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #4: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #5: @5 = input[3][2] */
  w5 = arg[3] ? arg[3][2] : 0;
  /* #6: @6 = input[3][3] */
  w6 = arg[3] ? arg[3][3] : 0;
  /* #7: @7 = input[3][4] */
  w7 = arg[3] ? arg[3][4] : 0;
  /* #8: @8 = input[3][5] */
  w8 = arg[3] ? arg[3][5] : 0;
  /* #9: @9 = input[3][6] */
  w9 = arg[3] ? arg[3][6] : 0;
  /* #10: @10 = input[3][7] */
  w10 = arg[3] ? arg[3][7] : 0;
  /* #11: @11 = input[3][8] */
  w11 = arg[3] ? arg[3][8] : 0;
  /* #12: @12 = input[3][9] */
  w12 = arg[3] ? arg[3][9] : 0;
  /* #13: @13 = input[3][10] */
  w13 = arg[3] ? arg[3][10] : 0;
  /* #14: @14 = input[3][11] */
  w14 = arg[3] ? arg[3][11] : 0;
  /* #15: @15 = input[3][12] */
  w15 = arg[3] ? arg[3][12] : 0;
  /* #16: @16 = input[3][13] */
  w16 = arg[3] ? arg[3][13] : 0;
  /* #17: @17 = input[3][14] */
  w17 = arg[3] ? arg[3][14] : 0;
  /* #18: @18 = input[3][15] */
  w18 = arg[3] ? arg[3][15] : 0;
  /* #19: @19 = input[3][16] */
  w19 = arg[3] ? arg[3][16] : 0;
  /* #20: @20 = input[3][17] */
  w20 = arg[3] ? arg[3][17] : 0;
  /* #21: @21 = input[3][18] */
  w21 = arg[3] ? arg[3][18] : 0;
  /* #22: @22 = input[3][19] */
  w22 = arg[3] ? arg[3][19] : 0;
  /* #23: @23 = input[3][20] */
  w23 = arg[3] ? arg[3][20] : 0;
  /* #24: @24 = input[3][21] */
  w24 = arg[3] ? arg[3][21] : 0;
  /* #25: @25 = input[3][22] */
  w25 = arg[3] ? arg[3][22] : 0;
  /* #26: @26 = input[3][23] */
  w26 = arg[3] ? arg[3][23] : 0;
  /* #27: @27 = input[3][24] */
  w27 = arg[3] ? arg[3][24] : 0;
  /* #28: @28 = input[3][25] */
  w28 = arg[3] ? arg[3][25] : 0;
  /* #29: @29 = input[3][26] */
  w29 = arg[3] ? arg[3][26] : 0;
  /* #30: @30 = input[3][27] */
  w30 = arg[3] ? arg[3][27] : 0;
  /* #31: @31 = input[3][29] */
  w31 = arg[3] ? arg[3][29] : 0;
  /* #32: @32 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @2, @31) */
  rr=w32;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w2;
  *rr++ = w31;
  /* #33: @33 = @32[:3] */
  for (rr=w33, ss=w32+0; ss!=w32+3; ss+=1) *rr++ = *ss;
  /* #34: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #35: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #36: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #37: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #38: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #39: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #40: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #41: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #42: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #43: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #44: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #45: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #46: @19 = input[0][12] */
  w19 = arg[0] ? arg[0][12] : 0;
  /* #47: @20 = input[0][13] */
  w20 = arg[0] ? arg[0][13] : 0;
  /* #48: @21 = input[0][14] */
  w21 = arg[0] ? arg[0][14] : 0;
  /* #49: @22 = input[0][15] */
  w22 = arg[0] ? arg[0][15] : 0;
  /* #50: @23 = input[0][16] */
  w23 = arg[0] ? arg[0][16] : 0;
  /* #51: @24 = input[0][17] */
  w24 = arg[0] ? arg[0][17] : 0;
  /* #52: @25 = input[0][18] */
  w25 = arg[0] ? arg[0][18] : 0;
  /* #53: @26 = input[0][19] */
  w26 = arg[0] ? arg[0][19] : 0;
  /* #54: @27 = input[0][20] */
  w27 = arg[0] ? arg[0][20] : 0;
  /* #55: @34 = vertcat(@3, @4, @5, @6, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27) */
  rr=w34;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #56: @35 = @34[:3] */
  for (rr=w35, ss=w34+0; ss!=w34+3; ss+=1) *rr++ = *ss;
  /* #57: @33 = (@33-@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #58: @35 = @33' */
  casadi_copy(w33, 3, w35);
  /* #59: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #60: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #61: @2 = 1 */
  w2 = 1.;
  /* #62: (@36[0] = @2) */
  for (rr=w36+0, ss=(&w2); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #63: @2 = 1 */
  w2 = 1.;
  /* #64: (@36[4] = @2) */
  for (rr=w36+4, ss=(&w2); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #65: @2 = 1 */
  w2 = 1.;
  /* #66: (@36[8] = @2) */
  for (rr=w36+8, ss=(&w2); rr!=w36+9; rr+=1) *rr = *ss++;
  /* #67: @1 = mac(@35,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = mac(@1,@33,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #69: @2 = 0 */
  w2 = 0.;
  /* #70: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #71: @33 = @32[11:14] */
  for (rr=w33, ss=w32+11; ss!=w32+14; ss+=1) *rr++ = *ss;
  /* #72: @35 = @34[11:14] */
  for (rr=w35, ss=w34+11; ss!=w34+14; ss+=1) *rr++ = *ss;
  /* #73: @33 = (@33-@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #74: @35 = @33' */
  casadi_copy(w33, 3, w35);
  /* #75: @35 = (@31*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #76: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #77: @31 = 1 */
  w31 = 1.;
  /* #78: (@36[4] = @31) */
  for (rr=w36+4, ss=(&w31); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #79: @31 = 1 */
  w31 = 1.;
  /* #80: (@36[8] = @31) */
  for (rr=w36+8, ss=(&w31); rr!=w36+9; rr+=1) *rr = *ss++;
  /* #81: @1 = mac(@35,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #82: @2 = mac(@1,@33,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #83: @0 = (@0+@2) */
  w0 += w2;
  /* #84: @2 = 0 */
  w2 = 0.;
  /* #85: @37 = zeros(1x7) */
  casadi_clear(w37, 7);
  /* #86: @31 = input[1][0] */
  w31 = arg[1] ? arg[1][0] : 0;
  /* #87: @3 = input[1][1] */
  w3 = arg[1] ? arg[1][1] : 0;
  /* #88: @4 = input[1][2] */
  w4 = arg[1] ? arg[1][2] : 0;
  /* #89: @5 = input[1][3] */
  w5 = arg[1] ? arg[1][3] : 0;
  /* #90: @6 = input[1][4] */
  w6 = arg[1] ? arg[1][4] : 0;
  /* #91: @15 = input[1][5] */
  w15 = arg[1] ? arg[1][5] : 0;
  /* #92: @16 = input[1][6] */
  w16 = arg[1] ? arg[1][6] : 0;
  /* #93: @38 = vertcat(@31, @3, @4, @5, @6, @15, @16) */
  rr=w38;
  *rr++ = w31;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  /* #94: @39 = @38' */
  casadi_copy(w38, 7, w39);
  /* #95: @40 = zeros(7x7) */
  casadi_clear(w40, 49);
  /* #96: @31 = 0.05 */
  w31 = 5.0000000000000003e-02;
  /* #97: (@40[0] = @31) */
  for (rr=w40+0, ss=(&w31); rr!=w40+1; rr+=1) *rr = *ss++;
  /* #98: @31 = 0.05 */
  w31 = 5.0000000000000003e-02;
  /* #99: (@40[8] = @31) */
  for (rr=w40+8, ss=(&w31); rr!=w40+9; rr+=1) *rr = *ss++;
  /* #100: @31 = 0.05 */
  w31 = 5.0000000000000003e-02;
  /* #101: (@40[16] = @31) */
  for (rr=w40+16, ss=(&w31); rr!=w40+17; rr+=1) *rr = *ss++;
  /* #102: @31 = 0.05 */
  w31 = 5.0000000000000003e-02;
  /* #103: (@40[24] = @31) */
  for (rr=w40+24, ss=(&w31); rr!=w40+25; rr+=1) *rr = *ss++;
  /* #104: @31 = 0.5 */
  w31 = 5.0000000000000000e-01;
  /* #105: (@40[32] = @31) */
  for (rr=w40+32, ss=(&w31); rr!=w40+33; rr+=1) *rr = *ss++;
  /* #106: @31 = 1 */
  w31 = 1.;
  /* #107: (@40[40] = @31) */
  for (rr=w40+40, ss=(&w31); rr!=w40+41; rr+=1) *rr = *ss++;
  /* #108: @31 = 1 */
  w31 = 1.;
  /* #109: (@40[48] = @31) */
  for (rr=w40+48, ss=(&w31); rr!=w40+49; rr+=1) *rr = *ss++;
  /* #110: @37 = mac(@39,@40,@37) */
  for (i=0, rr=w37; i<7; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w39+j, tt=w40+i*7; k<7; ++k) *rr += ss[k*1]**tt++;
  /* #111: @2 = mac(@37,@38,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w38+i*7; k<7; ++k) *rr += ss[k*1]**tt++;
  /* #112: @0 = (@0+@2) */
  w0 += w2;
  /* #113: @2 = 0 */
  w2 = 0.;
  /* #114: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #115: @12 = (-@12) */
  w12 = (- w12 );
  /* #116: @13 = (-@13) */
  w13 = (- w13 );
  /* #117: @14 = (-@14) */
  w14 = (- w14 );
  /* #118: @41 = vertcat(@11, @12, @13, @14) */
  rr=w41;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #119: @42 = @34[4:8] */
  for (rr=w42, ss=w34+4; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #120: @11 = ||@42||_F */
  w11 = sqrt(casadi_dot(4, w42, w42));
  /* #121: @41 = (@41/@11) */
  for (i=0, rr=w41; i<4; ++i) (*rr++) /= w11;
  /* #122: @11 = @41[0] */
  for (rr=(&w11), ss=w41+0; ss!=w41+1; ss+=1) *rr++ = *ss;
  /* #123: @12 = (@11*@7) */
  w12  = (w11*w7);
  /* #124: @13 = @41[1] */
  for (rr=(&w13), ss=w41+1; ss!=w41+2; ss+=1) *rr++ = *ss;
  /* #125: @14 = (@13*@8) */
  w14  = (w13*w8);
  /* #126: @12 = (@12-@14) */
  w12 -= w14;
  /* #127: @14 = @41[2] */
  for (rr=(&w14), ss=w41+2; ss!=w41+3; ss+=1) *rr++ = *ss;
  /* #128: @31 = (@14*@9) */
  w31  = (w14*w9);
  /* #129: @12 = (@12-@31) */
  w12 -= w31;
  /* #130: @31 = @41[3] */
  for (rr=(&w31), ss=w41+3; ss!=w41+4; ss+=1) *rr++ = *ss;
  /* #131: @3 = (@31*@10) */
  w3  = (w31*w10);
  /* #132: @12 = (@12-@3) */
  w12 -= w3;
  /* #133: @3 = 0 */
  w3 = 0.;
  /* #134: @3 = (@12<@3) */
  w3  = (w12<w3);
  /* #135: @4 = (@11*@8) */
  w4  = (w11*w8);
  /* #136: @5 = (@13*@7) */
  w5  = (w13*w7);
  /* #137: @4 = (@4+@5) */
  w4 += w5;
  /* #138: @5 = (@14*@10) */
  w5  = (w14*w10);
  /* #139: @4 = (@4+@5) */
  w4 += w5;
  /* #140: @5 = (@31*@9) */
  w5  = (w31*w9);
  /* #141: @4 = (@4-@5) */
  w4 -= w5;
  /* #142: @5 = (@11*@9) */
  w5  = (w11*w9);
  /* #143: @6 = (@13*@10) */
  w6  = (w13*w10);
  /* #144: @5 = (@5-@6) */
  w5 -= w6;
  /* #145: @6 = (@14*@7) */
  w6  = (w14*w7);
  /* #146: @5 = (@5+@6) */
  w5 += w6;
  /* #147: @6 = (@31*@8) */
  w6  = (w31*w8);
  /* #148: @5 = (@5+@6) */
  w5 += w6;
  /* #149: @11 = (@11*@10) */
  w11 *= w10;
  /* #150: @13 = (@13*@9) */
  w13 *= w9;
  /* #151: @11 = (@11+@13) */
  w11 += w13;
  /* #152: @14 = (@14*@8) */
  w14 *= w8;
  /* #153: @11 = (@11-@14) */
  w11 -= w14;
  /* #154: @31 = (@31*@7) */
  w31 *= w7;
  /* #155: @11 = (@11+@31) */
  w11 += w31;
  /* #156: @41 = vertcat(@12, @4, @5, @11) */
  rr=w41;
  *rr++ = w12;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w11;
  /* #157: @42 = (-@41) */
  for (i=0, rr=w42, cs=w41; i<4; ++i) *rr++ = (- *cs++ );
  /* #158: @42 = (@3?@42:0) */
  for (i=0, rr=w42, cs=w42; i<4; ++i) (*rr++)  = (w3?(*cs++):0);
  /* #159: @3 = (!@3) */
  w3 = (! w3 );
  /* #160: @41 = (@3?@41:0) */
  for (i=0, rr=w41, cs=w41; i<4; ++i) (*rr++)  = (w3?(*cs++):0);
  /* #161: @42 = (@42+@41) */
  for (i=0, rr=w42, cs=w41; i<4; ++i) (*rr++) += (*cs++);
  /* #162: @33 = @42[1:4] */
  for (rr=w33, ss=w42+1; ss!=w42+4; ss+=1) *rr++ = *ss;
  /* #163: @35 = (2.*@33) */
  for (i=0, rr=w35, cs=w33; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #164: @3 = ||@33||_F */
  w3 = sqrt(casadi_dot(3, w33, w33));
  /* #165: @12 = @42[0] */
  for (rr=(&w12), ss=w42+0; ss!=w42+1; ss+=1) *rr++ = *ss;
  /* #166: @12 = atan2(@3,@12) */
  w12  = atan2(w3,w12);
  /* #167: @35 = (@35*@12) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) *= w12;
  /* #168: @35 = (@35/@3) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w3;
  /* #169: @33 = @35' */
  casadi_copy(w35, 3, w33);
  /* #170: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #171: @3 = 1 */
  w3 = 1.;
  /* #172: (@36[0] = @3) */
  for (rr=w36+0, ss=(&w3); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #173: @3 = 1 */
  w3 = 1.;
  /* #174: (@36[4] = @3) */
  for (rr=w36+4, ss=(&w3); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #175: @3 = 1 */
  w3 = 1.;
  /* #176: (@36[8] = @3) */
  for (rr=w36+8, ss=(&w3); rr!=w36+9; rr+=1) *rr = *ss++;
  /* #177: @1 = mac(@33,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #178: @2 = mac(@1,@35,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w35+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #179: @0 = (@0+@2) */
  w0 += w2;
  /* #180: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 179;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
