/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s1[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[32] = {28, 1, 0, 28, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27};

/* Drone_ode_cost_ext_cost_0_fun_jac:(i0[21],i1[7],i2[0],i3[30])->(o0,o1[28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+35, *w33=w+65, *w34=w+68, *w35=w+89, *w36=w+92, *w37=w+101, *w38=w+104, *w39=w+107, *w40=w+116, *w41=w+123, *w42=w+130, *w43=w+137, *w44=w+186, *w45=w+190, *w46=w+194, *w47=w+198, *w48=w+202, *w49=w+205, *w50=w+208, *w51=w+211, *w52=w+214, *w53=w+223, *w54=w+272, *w55=w+275, *w56=w+284;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][28] */
  w2 = arg[3] ? arg[3][28] : 0;
  /* #3: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #4: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #5: @5 = input[3][2] */
  w5 = arg[3] ? arg[3][2] : 0;
  /* #6: @6 = input[3][3] */
  w6 = arg[3] ? arg[3][3] : 0;
  /* #7: @7 = input[3][4] */
  w7 = arg[3] ? arg[3][4] : 0;
  /* #8: @8 = input[3][5] */
  w8 = arg[3] ? arg[3][5] : 0;
  /* #9: @9 = input[3][6] */
  w9 = arg[3] ? arg[3][6] : 0;
  /* #10: @10 = input[3][7] */
  w10 = arg[3] ? arg[3][7] : 0;
  /* #11: @11 = input[3][8] */
  w11 = arg[3] ? arg[3][8] : 0;
  /* #12: @12 = input[3][9] */
  w12 = arg[3] ? arg[3][9] : 0;
  /* #13: @13 = input[3][10] */
  w13 = arg[3] ? arg[3][10] : 0;
  /* #14: @14 = input[3][11] */
  w14 = arg[3] ? arg[3][11] : 0;
  /* #15: @15 = input[3][12] */
  w15 = arg[3] ? arg[3][12] : 0;
  /* #16: @16 = input[3][13] */
  w16 = arg[3] ? arg[3][13] : 0;
  /* #17: @17 = input[3][14] */
  w17 = arg[3] ? arg[3][14] : 0;
  /* #18: @18 = input[3][15] */
  w18 = arg[3] ? arg[3][15] : 0;
  /* #19: @19 = input[3][16] */
  w19 = arg[3] ? arg[3][16] : 0;
  /* #20: @20 = input[3][17] */
  w20 = arg[3] ? arg[3][17] : 0;
  /* #21: @21 = input[3][18] */
  w21 = arg[3] ? arg[3][18] : 0;
  /* #22: @22 = input[3][19] */
  w22 = arg[3] ? arg[3][19] : 0;
  /* #23: @23 = input[3][20] */
  w23 = arg[3] ? arg[3][20] : 0;
  /* #24: @24 = input[3][21] */
  w24 = arg[3] ? arg[3][21] : 0;
  /* #25: @25 = input[3][22] */
  w25 = arg[3] ? arg[3][22] : 0;
  /* #26: @26 = input[3][23] */
  w26 = arg[3] ? arg[3][23] : 0;
  /* #27: @27 = input[3][24] */
  w27 = arg[3] ? arg[3][24] : 0;
  /* #28: @28 = input[3][25] */
  w28 = arg[3] ? arg[3][25] : 0;
  /* #29: @29 = input[3][26] */
  w29 = arg[3] ? arg[3][26] : 0;
  /* #30: @30 = input[3][27] */
  w30 = arg[3] ? arg[3][27] : 0;
  /* #31: @31 = input[3][29] */
  w31 = arg[3] ? arg[3][29] : 0;
  /* #32: @32 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @2, @31) */
  rr=w32;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w2;
  *rr++ = w31;
  /* #33: @33 = @32[:3] */
  for (rr=w33, ss=w32+0; ss!=w32+3; ss+=1) *rr++ = *ss;
  /* #34: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #35: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #36: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #37: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #38: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #39: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #40: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #41: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #42: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #43: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #44: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #45: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #46: @19 = input[0][12] */
  w19 = arg[0] ? arg[0][12] : 0;
  /* #47: @20 = input[0][13] */
  w20 = arg[0] ? arg[0][13] : 0;
  /* #48: @21 = input[0][14] */
  w21 = arg[0] ? arg[0][14] : 0;
  /* #49: @22 = input[0][15] */
  w22 = arg[0] ? arg[0][15] : 0;
  /* #50: @23 = input[0][16] */
  w23 = arg[0] ? arg[0][16] : 0;
  /* #51: @24 = input[0][17] */
  w24 = arg[0] ? arg[0][17] : 0;
  /* #52: @25 = input[0][18] */
  w25 = arg[0] ? arg[0][18] : 0;
  /* #53: @26 = input[0][19] */
  w26 = arg[0] ? arg[0][19] : 0;
  /* #54: @27 = input[0][20] */
  w27 = arg[0] ? arg[0][20] : 0;
  /* #55: @34 = vertcat(@3, @4, @5, @6, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27) */
  rr=w34;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #56: @35 = @34[:3] */
  for (rr=w35, ss=w34+0; ss!=w34+3; ss+=1) *rr++ = *ss;
  /* #57: @33 = (@33-@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #58: @35 = @33' */
  casadi_copy(w33, 3, w35);
  /* #59: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #60: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #61: @3 = 1 */
  w3 = 1.;
  /* #62: (@36[0] = @3) */
  for (rr=w36+0, ss=(&w3); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #63: @3 = 1 */
  w3 = 1.;
  /* #64: (@36[4] = @3) */
  for (rr=w36+4, ss=(&w3); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #65: @3 = 1 */
  w3 = 1.;
  /* #66: (@36[8] = @3) */
  for (rr=w36+8, ss=(&w3); rr!=w36+9; rr+=1) *rr = *ss++;
  /* #67: @1 = mac(@35,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = mac(@1,@33,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #69: @3 = 0 */
  w3 = 0.;
  /* #70: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #71: @37 = @32[11:14] */
  for (rr=w37, ss=w32+11; ss!=w32+14; ss+=1) *rr++ = *ss;
  /* #72: @38 = @34[11:14] */
  for (rr=w38, ss=w34+11; ss!=w34+14; ss+=1) *rr++ = *ss;
  /* #73: @37 = (@37-@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #74: @38 = @37' */
  casadi_copy(w37, 3, w38);
  /* #75: @38 = (@31*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #76: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #77: @4 = 1 */
  w4 = 1.;
  /* #78: (@39[4] = @4) */
  for (rr=w39+4, ss=(&w4); rr!=w39+5; rr+=1) *rr = *ss++;
  /* #79: @4 = 1 */
  w4 = 1.;
  /* #80: (@39[8] = @4) */
  for (rr=w39+8, ss=(&w4); rr!=w39+9; rr+=1) *rr = *ss++;
  /* #81: @35 = mac(@38,@39,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #82: @3 = mac(@35,@37,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #83: @0 = (@0+@3) */
  w0 += w3;
  /* #84: @3 = 0 */
  w3 = 0.;
  /* #85: @40 = zeros(1x7) */
  casadi_clear(w40, 7);
  /* #86: @4 = input[1][0] */
  w4 = arg[1] ? arg[1][0] : 0;
  /* #87: @5 = input[1][1] */
  w5 = arg[1] ? arg[1][1] : 0;
  /* #88: @6 = input[1][2] */
  w6 = arg[1] ? arg[1][2] : 0;
  /* #89: @15 = input[1][3] */
  w15 = arg[1] ? arg[1][3] : 0;
  /* #90: @16 = input[1][4] */
  w16 = arg[1] ? arg[1][4] : 0;
  /* #91: @17 = input[1][5] */
  w17 = arg[1] ? arg[1][5] : 0;
  /* #92: @18 = input[1][6] */
  w18 = arg[1] ? arg[1][6] : 0;
  /* #93: @41 = vertcat(@4, @5, @6, @15, @16, @17, @18) */
  rr=w41;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #94: @42 = @41' */
  casadi_copy(w41, 7, w42);
  /* #95: @43 = zeros(7x7) */
  casadi_clear(w43, 49);
  /* #96: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #97: (@43[0] = @4) */
  for (rr=w43+0, ss=(&w4); rr!=w43+1; rr+=1) *rr = *ss++;
  /* #98: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #99: (@43[8] = @4) */
  for (rr=w43+8, ss=(&w4); rr!=w43+9; rr+=1) *rr = *ss++;
  /* #100: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #101: (@43[16] = @4) */
  for (rr=w43+16, ss=(&w4); rr!=w43+17; rr+=1) *rr = *ss++;
  /* #102: @4 = 0.05 */
  w4 = 5.0000000000000003e-02;
  /* #103: (@43[24] = @4) */
  for (rr=w43+24, ss=(&w4); rr!=w43+25; rr+=1) *rr = *ss++;
  /* #104: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #105: (@43[32] = @4) */
  for (rr=w43+32, ss=(&w4); rr!=w43+33; rr+=1) *rr = *ss++;
  /* #106: @4 = 1 */
  w4 = 1.;
  /* #107: (@43[40] = @4) */
  for (rr=w43+40, ss=(&w4); rr!=w43+41; rr+=1) *rr = *ss++;
  /* #108: @4 = 1 */
  w4 = 1.;
  /* #109: (@43[48] = @4) */
  for (rr=w43+48, ss=(&w4); rr!=w43+49; rr+=1) *rr = *ss++;
  /* #110: @40 = mac(@42,@43,@40) */
  for (i=0, rr=w40; i<7; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w43+i*7; k<7; ++k) *rr += ss[k*1]**tt++;
  /* #111: @3 = mac(@40,@41,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w40+j, tt=w41+i*7; k<7; ++k) *rr += ss[k*1]**tt++;
  /* #112: @0 = (@0+@3) */
  w0 += w3;
  /* #113: @3 = 0 */
  w3 = 0.;
  /* #114: @38 = zeros(1x3) */
  casadi_clear(w38, 3);
  /* #115: @12 = (-@12) */
  w12 = (- w12 );
  /* #116: @13 = (-@13) */
  w13 = (- w13 );
  /* #117: @14 = (-@14) */
  w14 = (- w14 );
  /* #118: @44 = vertcat(@11, @12, @13, @14) */
  rr=w44;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #119: @45 = @34[4:8] */
  for (rr=w45, ss=w34+4; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #120: @11 = ||@45||_F */
  w11 = sqrt(casadi_dot(4, w45, w45));
  /* #121: @44 = (@44/@11) */
  for (i=0, rr=w44; i<4; ++i) (*rr++) /= w11;
  /* #122: @12 = @44[0] */
  for (rr=(&w12), ss=w44+0; ss!=w44+1; ss+=1) *rr++ = *ss;
  /* #123: @13 = (@12*@7) */
  w13  = (w12*w7);
  /* #124: @14 = @44[1] */
  for (rr=(&w14), ss=w44+1; ss!=w44+2; ss+=1) *rr++ = *ss;
  /* #125: @4 = (@14*@8) */
  w4  = (w14*w8);
  /* #126: @13 = (@13-@4) */
  w13 -= w4;
  /* #127: @4 = @44[2] */
  for (rr=(&w4), ss=w44+2; ss!=w44+3; ss+=1) *rr++ = *ss;
  /* #128: @5 = (@4*@9) */
  w5  = (w4*w9);
  /* #129: @13 = (@13-@5) */
  w13 -= w5;
  /* #130: @5 = @44[3] */
  for (rr=(&w5), ss=w44+3; ss!=w44+4; ss+=1) *rr++ = *ss;
  /* #131: @6 = (@5*@10) */
  w6  = (w5*w10);
  /* #132: @13 = (@13-@6) */
  w13 -= w6;
  /* #133: @6 = 0 */
  w6 = 0.;
  /* #134: @6 = (@13<@6) */
  w6  = (w13<w6);
  /* #135: @15 = (@12*@8) */
  w15  = (w12*w8);
  /* #136: @16 = (@14*@7) */
  w16  = (w14*w7);
  /* #137: @15 = (@15+@16) */
  w15 += w16;
  /* #138: @16 = (@4*@10) */
  w16  = (w4*w10);
  /* #139: @15 = (@15+@16) */
  w15 += w16;
  /* #140: @16 = (@5*@9) */
  w16  = (w5*w9);
  /* #141: @15 = (@15-@16) */
  w15 -= w16;
  /* #142: @16 = (@12*@9) */
  w16  = (w12*w9);
  /* #143: @17 = (@14*@10) */
  w17  = (w14*w10);
  /* #144: @16 = (@16-@17) */
  w16 -= w17;
  /* #145: @17 = (@4*@7) */
  w17  = (w4*w7);
  /* #146: @16 = (@16+@17) */
  w16 += w17;
  /* #147: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #148: @16 = (@16+@17) */
  w16 += w17;
  /* #149: @12 = (@12*@10) */
  w12 *= w10;
  /* #150: @14 = (@14*@9) */
  w14 *= w9;
  /* #151: @12 = (@12+@14) */
  w12 += w14;
  /* #152: @4 = (@4*@8) */
  w4 *= w8;
  /* #153: @12 = (@12-@4) */
  w12 -= w4;
  /* #154: @5 = (@5*@7) */
  w5 *= w7;
  /* #155: @12 = (@12+@5) */
  w12 += w5;
  /* #156: @46 = vertcat(@13, @15, @16, @12) */
  rr=w46;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w12;
  /* #157: @47 = (-@46) */
  for (i=0, rr=w47, cs=w46; i<4; ++i) *rr++ = (- *cs++ );
  /* #158: @47 = (@6?@47:0) */
  for (i=0, rr=w47, cs=w47; i<4; ++i) (*rr++)  = (w6?(*cs++):0);
  /* #159: @13 = (!@6) */
  w13 = (! w6 );
  /* #160: @46 = (@13?@46:0) */
  for (i=0, rr=w46, cs=w46; i<4; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #161: @47 = (@47+@46) */
  for (i=0, rr=w47, cs=w46; i<4; ++i) (*rr++) += (*cs++);
  /* #162: @48 = @47[1:4] */
  for (rr=w48, ss=w47+1; ss!=w47+4; ss+=1) *rr++ = *ss;
  /* #163: @49 = (2.*@48) */
  for (i=0, rr=w49, cs=w48; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #164: @15 = ||@48||_F */
  w15 = sqrt(casadi_dot(3, w48, w48));
  /* #165: @16 = @47[0] */
  for (rr=(&w16), ss=w47+0; ss!=w47+1; ss+=1) *rr++ = *ss;
  /* #166: @12 = atan2(@15,@16) */
  w12  = atan2(w15,w16);
  /* #167: @50 = (@49*@12) */
  for (i=0, rr=w50, cr=w49; i<3; ++i) (*rr++)  = ((*cr++)*w12);
  /* #168: @50 = (@50/@15) */
  for (i=0, rr=w50; i<3; ++i) (*rr++) /= w15;
  /* #169: @51 = @50' */
  casadi_copy(w50, 3, w51);
  /* #170: @52 = zeros(3x3) */
  casadi_clear(w52, 9);
  /* #171: @5 = 1 */
  w5 = 1.;
  /* #172: (@52[0] = @5) */
  for (rr=w52+0, ss=(&w5); rr!=w52+1; rr+=1) *rr = *ss++;
  /* #173: @5 = 1 */
  w5 = 1.;
  /* #174: (@52[4] = @5) */
  for (rr=w52+4, ss=(&w5); rr!=w52+5; rr+=1) *rr = *ss++;
  /* #175: @5 = 1 */
  w5 = 1.;
  /* #176: (@52[8] = @5) */
  for (rr=w52+8, ss=(&w5); rr!=w52+9; rr+=1) *rr = *ss++;
  /* #177: @38 = mac(@51,@52,@38) */
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w51+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #178: @3 = mac(@38,@50,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #179: @0 = (@0+@3) */
  w0 += w3;
  /* #180: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #181: @40 = @40' */
  /* #182: @42 = zeros(1x7) */
  casadi_clear(w42, 7);
  /* #183: @41 = @41' */
  /* #184: @53 = @43' */
  for (i=0, rr=w53, cs=w43; i<7; ++i) for (j=0; j<7; ++j) rr[i+j*7] = *cs++;
  /* #185: @42 = mac(@41,@53,@42) */
  for (i=0, rr=w42; i<7; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w41+j, tt=w53+i*7; k<7; ++k) *rr += ss[k*1]**tt++;
  /* #186: @42 = @42' */
  /* #187: @40 = (@40+@42) */
  for (i=0, rr=w40, cs=w42; i<7; ++i) (*rr++) += (*cs++);
  /* #188: {@0, @3, @5, @4, @14, @17, @18} = vertsplit(@40) */
  w0 = w40[0];
  w3 = w40[1];
  w5 = w40[2];
  w4 = w40[3];
  w14 = w40[4];
  w17 = w40[5];
  w18 = w40[6];
  /* #189: output[1][0] = @0 */
  if (res[1]) res[1][0] = w0;
  /* #190: output[1][1] = @3 */
  if (res[1]) res[1][1] = w3;
  /* #191: output[1][2] = @5 */
  if (res[1]) res[1][2] = w5;
  /* #192: output[1][3] = @4 */
  if (res[1]) res[1][3] = w4;
  /* #193: output[1][4] = @14 */
  if (res[1]) res[1][4] = w14;
  /* #194: output[1][5] = @17 */
  if (res[1]) res[1][5] = w17;
  /* #195: output[1][6] = @18 */
  if (res[1]) res[1][6] = w18;
  /* #196: @34 = zeros(21x1) */
  casadi_clear(w34, 21);
  /* #197: @44 = (@44/@11) */
  for (i=0, rr=w44; i<4; ++i) (*rr++) /= w11;
  /* #198: @44 = (-@44) */
  for (i=0, rr=w44, cs=w44; i<4; ++i) *rr++ = (- *cs++ );
  /* #199: @47 = zeros(4x1) */
  casadi_clear(w47, 4);
  /* #200: @18 = 1 */
  w18 = 1.;
  /* #201: @13 = (@13?@18:0) */
  w13  = (w13?w18:0);
  /* #202: @46 = zeros(4x1) */
  casadi_clear(w46, 4);
  /* #203: @18 = sq(@15) */
  w18 = casadi_sq( w15 );
  /* #204: @17 = sq(@16) */
  w17 = casadi_sq( w16 );
  /* #205: @18 = (@18+@17) */
  w18 += w17;
  /* #206: @17 = (@15/@18) */
  w17  = (w15/w18);
  /* #207: @38 = @38' */
  /* #208: @51 = zeros(1x3) */
  casadi_clear(w51, 3);
  /* #209: @54 = @50' */
  casadi_copy(w50, 3, w54);
  /* #210: @55 = @52' */
  for (i=0, rr=w55, cs=w52; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #211: @51 = mac(@54,@55,@51) */
  for (i=0, rr=w51; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w54+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #212: @51 = @51' */
  /* #213: @38 = (@38+@51) */
  for (i=0, rr=w38, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #214: @51 = (@38/@15) */
  for (i=0, rr=w51, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #215: @14 = dot(@49, @51) */
  w14 = casadi_dot(3, w49, w51);
  /* #216: @17 = (@17*@14) */
  w17 *= w14;
  /* #217: @17 = (-@17) */
  w17 = (- w17 );
  /* #218: (@46[0] += @17) */
  for (rr=w46+0, ss=(&w17); rr!=w46+1; rr+=1) *rr += *ss++;
  /* #219: @50 = (@50/@15) */
  for (i=0, rr=w50; i<3; ++i) (*rr++) /= w15;
  /* #220: @50 = (-@50) */
  for (i=0, rr=w50, cs=w50; i<3; ++i) *rr++ = (- *cs++ );
  /* #221: @17 = dot(@50, @38) */
  w17 = casadi_dot(3, w50, w38);
  /* #222: @16 = (@16/@18) */
  w16 /= w18;
  /* #223: @16 = (@16*@14) */
  w16 *= w14;
  /* #224: @17 = (@17+@16) */
  w17 += w16;
  /* #225: @17 = (@17/@15) */
  w17 /= w15;
  /* #226: @48 = (@17*@48) */
  for (i=0, rr=w48, cs=w48; i<3; ++i) (*rr++)  = (w17*(*cs++));
  /* #227: @51 = (@12*@51) */
  for (i=0, rr=w51, cs=w51; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #228: @51 = (2.*@51) */
  for (i=0, rr=w51, cs=w51; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #229: @48 = (@48+@51) */
  for (i=0, rr=w48, cs=w51; i<3; ++i) (*rr++) += (*cs++);
  /* #230: (@46[1:4] += @48) */
  for (rr=w46+1, ss=w48; rr!=w46+4; rr+=1) *rr += *ss++;
  /* #231: @56 = (@13*@46) */
  for (i=0, rr=w56, cs=w46; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #232: @13 = 1 */
  w13 = 1.;
  /* #233: @6 = (@6?@13:0) */
  w6  = (w6?w13:0);
  /* #234: @46 = (@6*@46) */
  for (i=0, rr=w46, cs=w46; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #235: @56 = (@56-@46) */
  for (i=0, rr=w56, cs=w46; i<4; ++i) (*rr++) -= (*cs++);
  /* #236: {@6, @13, @12, @17} = vertsplit(@56) */
  w6 = w56[0];
  w13 = w56[1];
  w12 = w56[2];
  w17 = w56[3];
  /* #237: @15 = (@7*@17) */
  w15  = (w7*w17);
  /* #238: @16 = (@8*@12) */
  w16  = (w8*w12);
  /* #239: @15 = (@15+@16) */
  w15 += w16;
  /* #240: @16 = (@9*@13) */
  w16  = (w9*w13);
  /* #241: @15 = (@15-@16) */
  w15 -= w16;
  /* #242: @16 = (@10*@6) */
  w16  = (w10*w6);
  /* #243: @15 = (@15-@16) */
  w15 -= w16;
  /* #244: (@47[3] += @15) */
  for (rr=w47+3, ss=(&w15); rr!=w47+4; rr+=1) *rr += *ss++;
  /* #245: @15 = (@7*@12) */
  w15  = (w7*w12);
  /* #246: @16 = (@8*@17) */
  w16  = (w8*w17);
  /* #247: @15 = (@15-@16) */
  w15 -= w16;
  /* #248: @16 = (@10*@13) */
  w16  = (w10*w13);
  /* #249: @15 = (@15+@16) */
  w15 += w16;
  /* #250: @16 = (@9*@6) */
  w16  = (w9*w6);
  /* #251: @15 = (@15-@16) */
  w15 -= w16;
  /* #252: (@47[2] += @15) */
  for (rr=w47+2, ss=(&w15); rr!=w47+3; rr+=1) *rr += *ss++;
  /* #253: @15 = (@9*@17) */
  w15  = (w9*w17);
  /* #254: @16 = (@10*@12) */
  w16  = (w10*w12);
  /* #255: @15 = (@15-@16) */
  w15 -= w16;
  /* #256: @16 = (@7*@13) */
  w16  = (w7*w13);
  /* #257: @15 = (@15+@16) */
  w15 += w16;
  /* #258: @16 = (@8*@6) */
  w16  = (w8*w6);
  /* #259: @15 = (@15-@16) */
  w15 -= w16;
  /* #260: (@47[1] += @15) */
  for (rr=w47+1, ss=(&w15); rr!=w47+2; rr+=1) *rr += *ss++;
  /* #261: @10 = (@10*@17) */
  w10 *= w17;
  /* #262: @9 = (@9*@12) */
  w9 *= w12;
  /* #263: @10 = (@10+@9) */
  w10 += w9;
  /* #264: @8 = (@8*@13) */
  w8 *= w13;
  /* #265: @10 = (@10+@8) */
  w10 += w8;
  /* #266: @7 = (@7*@6) */
  w7 *= w6;
  /* #267: @10 = (@10+@7) */
  w10 += w7;
  /* #268: (@47[0] += @10) */
  for (rr=w47+0, ss=(&w10); rr!=w47+1; rr+=1) *rr += *ss++;
  /* #269: @10 = dot(@44, @47) */
  w10 = casadi_dot(4, w44, w47);
  /* #270: @10 = (@10/@11) */
  w10 /= w11;
  /* #271: @45 = (@10*@45) */
  for (i=0, rr=w45, cs=w45; i<4; ++i) (*rr++)  = (w10*(*cs++));
  /* #272: (@34[4:8] += @45) */
  for (rr=w34+4, ss=w45; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #273: @35 = @35' */
  /* #274: @48 = zeros(1x3) */
  casadi_clear(w48, 3);
  /* #275: @37 = @37' */
  /* #276: @55 = @39' */
  for (i=0, rr=w55, cs=w39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #277: @48 = mac(@37,@55,@48) */
  for (i=0, rr=w48; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #278: @48 = (@31*@48) */
  for (i=0, rr=w48, cs=w48; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #279: @48 = @48' */
  /* #280: @35 = (@35+@48) */
  for (i=0, rr=w35, cs=w48; i<3; ++i) (*rr++) += (*cs++);
  /* #281: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #282: (@34[11:14] += @35) */
  for (rr=w34+11, ss=w35; rr!=w34+14; rr+=1) *rr += *ss++;
  /* #283: @1 = @1' */
  /* #284: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #285: @33 = @33' */
  /* #286: @55 = @36' */
  for (i=0, rr=w55, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #287: @35 = mac(@33,@55,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w55+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #288: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #289: @35 = @35' */
  /* #290: @1 = (@1+@35) */
  for (i=0, rr=w1, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #291: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #292: (@34[:3] += @1) */
  for (rr=w34+0, ss=w1; rr!=w34+3; rr+=1) *rr += *ss++;
  /* #293: {@2, @31, @10, @7, @6, @8, @13, @9, @12, @17, @15, @16, @14, @18, @4, @5, @3, @0, @19, @20, @21} = vertsplit(@34) */
  w2 = w34[0];
  w31 = w34[1];
  w10 = w34[2];
  w7 = w34[3];
  w6 = w34[4];
  w8 = w34[5];
  w13 = w34[6];
  w9 = w34[7];
  w12 = w34[8];
  w17 = w34[9];
  w15 = w34[10];
  w16 = w34[11];
  w14 = w34[12];
  w18 = w34[13];
  w4 = w34[14];
  w5 = w34[15];
  w3 = w34[16];
  w0 = w34[17];
  w19 = w34[18];
  w20 = w34[19];
  w21 = w34[20];
  /* #294: output[1][7] = @2 */
  if (res[1]) res[1][7] = w2;
  /* #295: output[1][8] = @31 */
  if (res[1]) res[1][8] = w31;
  /* #296: output[1][9] = @10 */
  if (res[1]) res[1][9] = w10;
  /* #297: output[1][10] = @7 */
  if (res[1]) res[1][10] = w7;
  /* #298: @47 = (@47/@11) */
  for (i=0, rr=w47; i<4; ++i) (*rr++) /= w11;
  /* #299: {@11, @7, @10, @31} = vertsplit(@47) */
  w11 = w47[0];
  w7 = w47[1];
  w10 = w47[2];
  w31 = w47[3];
  /* #300: @11 = (@11+@6) */
  w11 += w6;
  /* #301: output[1][11] = @11 */
  if (res[1]) res[1][11] = w11;
  /* #302: @8 = (@8-@7) */
  w8 -= w7;
  /* #303: output[1][12] = @8 */
  if (res[1]) res[1][12] = w8;
  /* #304: @13 = (@13-@10) */
  w13 -= w10;
  /* #305: output[1][13] = @13 */
  if (res[1]) res[1][13] = w13;
  /* #306: @9 = (@9-@31) */
  w9 -= w31;
  /* #307: output[1][14] = @9 */
  if (res[1]) res[1][14] = w9;
  /* #308: output[1][15] = @12 */
  if (res[1]) res[1][15] = w12;
  /* #309: output[1][16] = @17 */
  if (res[1]) res[1][16] = w17;
  /* #310: output[1][17] = @15 */
  if (res[1]) res[1][17] = w15;
  /* #311: output[1][18] = @16 */
  if (res[1]) res[1][18] = w16;
  /* #312: output[1][19] = @14 */
  if (res[1]) res[1][19] = w14;
  /* #313: output[1][20] = @18 */
  if (res[1]) res[1][20] = w18;
  /* #314: output[1][21] = @4 */
  if (res[1]) res[1][21] = w4;
  /* #315: output[1][22] = @5 */
  if (res[1]) res[1][22] = w5;
  /* #316: output[1][23] = @3 */
  if (res[1]) res[1][23] = w3;
  /* #317: output[1][24] = @0 */
  if (res[1]) res[1][24] = w0;
  /* #318: output[1][25] = @19 */
  if (res[1]) res[1][25] = w19;
  /* #319: output[1][26] = @20 */
  if (res[1]) res[1][26] = w20;
  /* #320: output[1][27] = @21 */
  if (res[1]) res[1][27] = w21;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_0_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_0_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34;
  if (sz_res) *sz_res = 23;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 288;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
