/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sparsify CASADI_PREFIX(sparsify)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

void casadi_sparsify(const casadi_real* x, casadi_real* y, const casadi_int* sp_y, casadi_int tr) {
  casadi_int nrow_y, ncol_y, i, el;
  const casadi_int *colind_y, *row_y;
  nrow_y = sp_y[0];
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y+ncol_y+3;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[i + row_y[el]*ncol_y]);
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (el=colind_y[i]; el!=colind_y[i+1]; ++el) {
        *y++ = CASADI_CAST(casadi_real, x[row_y[el]]);
      }
      x += nrow_y;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {4, 1, 0, 1, 0};
static const casadi_int casadi_s1[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s2[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[7] = {1, 3, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[10] = {0, 1, 2, 4, 5, 6, 7, 11, 12, 13};
static const casadi_int casadi_s5[10] = {0, 1, 2, 9, 10, 11, 12, 25, 26, 27};
static const casadi_int casadi_s6[10] = {0, 3, 6, 9, 13, 17, 21, 25, 28, 31};
static const casadi_int casadi_s7[5] = {4, 1, 0, 1, 1};
static const casadi_int casadi_s8[7] = {1, 3, 0, 0, 1, 1, 0};
static const casadi_int casadi_s9[10] = {3, 4, 5, 13, 14, 15, 16, 28, 29, 30};
static const casadi_int casadi_s10[10] = {1, 4, 7, 10, 14, 18, 22, 26, 29, 32};
static const casadi_int casadi_s11[5] = {4, 1, 0, 1, 2};
static const casadi_int casadi_s12[7] = {1, 3, 0, 0, 0, 1, 0};
static const casadi_int casadi_s13[10] = {6, 7, 8, 17, 18, 19, 20, 31, 32, 33};
static const casadi_int casadi_s14[10] = {2, 5, 8, 11, 15, 19, 23, 27, 30, 33};
static const casadi_int casadi_s15[5] = {4, 1, 0, 1, 3};
static const casadi_int casadi_s16[58] = {21, 21, 0, 3, 6, 9, 9, 13, 17, 21, 25, 25, 25, 25, 28, 31, 34, 34, 34, 34, 34, 34, 34, 34, 0, 1, 2, 0, 1, 2, 0, 1, 2, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 11, 12, 13, 11, 12, 13, 11, 12, 13};
static const casadi_int casadi_s17[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s18[3] = {0, 0, 0};
static const casadi_int casadi_s19[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s20[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s21[24] = {0, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* Drone_ode_cost_ext_cost_e_fun_jac_hess:(i0[21],i1[],i2[],i3[30])->(o0,o1[21],o2[21x21,34nz],o3[],o4[0x21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+35, *w33=w+65, *w34=w+68, *w35=w+89, *w36=w+92, *w37=w+101, *w38=w+104, *w39=w+107, *w40=w+116, *w41=w+120, *w42=w+124, *w43=w+128, *w44=w+132, *w45=w+135, *w46=w+138, *w47=w+141, *w48=w+144, *w49=w+153, *w50=w+157, *w51=w+161, *w52=w+164, *w53=w+173, *w54=w+176, *w55=w+179, *w56=w+182, *w57=w+186, *w58=w+195, w59, w60, w61, w62, w63, w64, w65, w66, w67, w68, *w69=w+214, *w70=w+248, *w71=w+252, *w75=w+266, *w76=w+270, *w77=w+274, *w78=w+278, w79, w80, w81, w82, w83, w84, w85, w86, w87, w88, w89, *w90=w+292, *w91=w+302;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][28] */
  w2 = arg[3] ? arg[3][28] : 0;
  /* #3: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #4: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #5: @5 = input[3][2] */
  w5 = arg[3] ? arg[3][2] : 0;
  /* #6: @6 = input[3][3] */
  w6 = arg[3] ? arg[3][3] : 0;
  /* #7: @7 = input[3][4] */
  w7 = arg[3] ? arg[3][4] : 0;
  /* #8: @8 = input[3][5] */
  w8 = arg[3] ? arg[3][5] : 0;
  /* #9: @9 = input[3][6] */
  w9 = arg[3] ? arg[3][6] : 0;
  /* #10: @10 = input[3][7] */
  w10 = arg[3] ? arg[3][7] : 0;
  /* #11: @11 = input[3][8] */
  w11 = arg[3] ? arg[3][8] : 0;
  /* #12: @12 = input[3][9] */
  w12 = arg[3] ? arg[3][9] : 0;
  /* #13: @13 = input[3][10] */
  w13 = arg[3] ? arg[3][10] : 0;
  /* #14: @14 = input[3][11] */
  w14 = arg[3] ? arg[3][11] : 0;
  /* #15: @15 = input[3][12] */
  w15 = arg[3] ? arg[3][12] : 0;
  /* #16: @16 = input[3][13] */
  w16 = arg[3] ? arg[3][13] : 0;
  /* #17: @17 = input[3][14] */
  w17 = arg[3] ? arg[3][14] : 0;
  /* #18: @18 = input[3][15] */
  w18 = arg[3] ? arg[3][15] : 0;
  /* #19: @19 = input[3][16] */
  w19 = arg[3] ? arg[3][16] : 0;
  /* #20: @20 = input[3][17] */
  w20 = arg[3] ? arg[3][17] : 0;
  /* #21: @21 = input[3][18] */
  w21 = arg[3] ? arg[3][18] : 0;
  /* #22: @22 = input[3][19] */
  w22 = arg[3] ? arg[3][19] : 0;
  /* #23: @23 = input[3][20] */
  w23 = arg[3] ? arg[3][20] : 0;
  /* #24: @24 = input[3][21] */
  w24 = arg[3] ? arg[3][21] : 0;
  /* #25: @25 = input[3][22] */
  w25 = arg[3] ? arg[3][22] : 0;
  /* #26: @26 = input[3][23] */
  w26 = arg[3] ? arg[3][23] : 0;
  /* #27: @27 = input[3][24] */
  w27 = arg[3] ? arg[3][24] : 0;
  /* #28: @28 = input[3][25] */
  w28 = arg[3] ? arg[3][25] : 0;
  /* #29: @29 = input[3][26] */
  w29 = arg[3] ? arg[3][26] : 0;
  /* #30: @30 = input[3][27] */
  w30 = arg[3] ? arg[3][27] : 0;
  /* #31: @31 = input[3][29] */
  w31 = arg[3] ? arg[3][29] : 0;
  /* #32: @32 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @2, @31) */
  rr=w32;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w2;
  *rr++ = w31;
  /* #33: @33 = @32[:3] */
  for (rr=w33, ss=w32+0; ss!=w32+3; ss+=1) *rr++ = *ss;
  /* #34: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #35: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #36: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #37: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #38: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #39: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #40: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #41: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #42: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #43: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #44: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #45: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #46: @19 = input[0][12] */
  w19 = arg[0] ? arg[0][12] : 0;
  /* #47: @20 = input[0][13] */
  w20 = arg[0] ? arg[0][13] : 0;
  /* #48: @21 = input[0][14] */
  w21 = arg[0] ? arg[0][14] : 0;
  /* #49: @22 = input[0][15] */
  w22 = arg[0] ? arg[0][15] : 0;
  /* #50: @23 = input[0][16] */
  w23 = arg[0] ? arg[0][16] : 0;
  /* #51: @24 = input[0][17] */
  w24 = arg[0] ? arg[0][17] : 0;
  /* #52: @25 = input[0][18] */
  w25 = arg[0] ? arg[0][18] : 0;
  /* #53: @26 = input[0][19] */
  w26 = arg[0] ? arg[0][19] : 0;
  /* #54: @27 = input[0][20] */
  w27 = arg[0] ? arg[0][20] : 0;
  /* #55: @34 = vertcat(@3, @4, @5, @6, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27) */
  rr=w34;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #56: @35 = @34[:3] */
  for (rr=w35, ss=w34+0; ss!=w34+3; ss+=1) *rr++ = *ss;
  /* #57: @33 = (@33-@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #58: @35 = @33' */
  casadi_copy(w33, 3, w35);
  /* #59: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #60: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #61: @3 = 1 */
  w3 = 1.;
  /* #62: (@36[0] = @3) */
  for (rr=w36+0, ss=(&w3); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #63: @3 = 1 */
  w3 = 1.;
  /* #64: (@36[4] = @3) */
  for (rr=w36+4, ss=(&w3); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #65: @3 = 1 */
  w3 = 1.;
  /* #66: (@36[8] = @3) */
  for (rr=w36+8, ss=(&w3); rr!=w36+9; rr+=1) *rr = *ss++;
  /* #67: @1 = mac(@35,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = mac(@1,@33,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #69: @3 = 0 */
  w3 = 0.;
  /* #70: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #71: @37 = @32[11:14] */
  for (rr=w37, ss=w32+11; ss!=w32+14; ss+=1) *rr++ = *ss;
  /* #72: @38 = @34[11:14] */
  for (rr=w38, ss=w34+11; ss!=w34+14; ss+=1) *rr++ = *ss;
  /* #73: @37 = (@37-@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #74: @38 = @37' */
  casadi_copy(w37, 3, w38);
  /* #75: @38 = (@31*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #76: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #77: @4 = 1 */
  w4 = 1.;
  /* #78: (@39[4] = @4) */
  for (rr=w39+4, ss=(&w4); rr!=w39+5; rr+=1) *rr = *ss++;
  /* #79: @4 = 1 */
  w4 = 1.;
  /* #80: (@39[8] = @4) */
  for (rr=w39+8, ss=(&w4); rr!=w39+9; rr+=1) *rr = *ss++;
  /* #81: @35 = mac(@38,@39,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #82: @3 = mac(@35,@37,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #83: @0 = (@0+@3) */
  w0 += w3;
  /* #84: @3 = 0 */
  w3 = 0.;
  /* #85: @38 = zeros(1x3) */
  casadi_clear(w38, 3);
  /* #86: @12 = (-@12) */
  w12 = (- w12 );
  /* #87: @13 = (-@13) */
  w13 = (- w13 );
  /* #88: @14 = (-@14) */
  w14 = (- w14 );
  /* #89: @40 = vertcat(@11, @12, @13, @14) */
  rr=w40;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #90: @41 = @34[4:8] */
  for (rr=w41, ss=w34+4; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #91: @11 = ||@41||_F */
  w11 = sqrt(casadi_dot(4, w41, w41));
  /* #92: @40 = (@40/@11) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w11;
  /* #93: @12 = @40[0] */
  for (rr=(&w12), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #94: @13 = (@12*@7) */
  w13  = (w12*w7);
  /* #95: @14 = @40[1] */
  for (rr=(&w14), ss=w40+1; ss!=w40+2; ss+=1) *rr++ = *ss;
  /* #96: @4 = (@14*@8) */
  w4  = (w14*w8);
  /* #97: @13 = (@13-@4) */
  w13 -= w4;
  /* #98: @4 = @40[2] */
  for (rr=(&w4), ss=w40+2; ss!=w40+3; ss+=1) *rr++ = *ss;
  /* #99: @5 = (@4*@9) */
  w5  = (w4*w9);
  /* #100: @13 = (@13-@5) */
  w13 -= w5;
  /* #101: @5 = @40[3] */
  for (rr=(&w5), ss=w40+3; ss!=w40+4; ss+=1) *rr++ = *ss;
  /* #102: @6 = (@5*@10) */
  w6  = (w5*w10);
  /* #103: @13 = (@13-@6) */
  w13 -= w6;
  /* #104: @6 = 0 */
  w6 = 0.;
  /* #105: @6 = (@13<@6) */
  w6  = (w13<w6);
  /* #106: @15 = (@12*@8) */
  w15  = (w12*w8);
  /* #107: @16 = (@14*@7) */
  w16  = (w14*w7);
  /* #108: @15 = (@15+@16) */
  w15 += w16;
  /* #109: @16 = (@4*@10) */
  w16  = (w4*w10);
  /* #110: @15 = (@15+@16) */
  w15 += w16;
  /* #111: @16 = (@5*@9) */
  w16  = (w5*w9);
  /* #112: @15 = (@15-@16) */
  w15 -= w16;
  /* #113: @16 = (@12*@9) */
  w16  = (w12*w9);
  /* #114: @17 = (@14*@10) */
  w17  = (w14*w10);
  /* #115: @16 = (@16-@17) */
  w16 -= w17;
  /* #116: @17 = (@4*@7) */
  w17  = (w4*w7);
  /* #117: @16 = (@16+@17) */
  w16 += w17;
  /* #118: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #119: @16 = (@16+@17) */
  w16 += w17;
  /* #120: @12 = (@12*@10) */
  w12 *= w10;
  /* #121: @14 = (@14*@9) */
  w14 *= w9;
  /* #122: @12 = (@12+@14) */
  w12 += w14;
  /* #123: @4 = (@4*@8) */
  w4 *= w8;
  /* #124: @12 = (@12-@4) */
  w12 -= w4;
  /* #125: @5 = (@5*@7) */
  w5 *= w7;
  /* #126: @12 = (@12+@5) */
  w12 += w5;
  /* #127: @42 = vertcat(@13, @15, @16, @12) */
  rr=w42;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w12;
  /* #128: @43 = (-@42) */
  for (i=0, rr=w43, cs=w42; i<4; ++i) *rr++ = (- *cs++ );
  /* #129: @43 = (@6?@43:0) */
  for (i=0, rr=w43, cs=w43; i<4; ++i) (*rr++)  = (w6?(*cs++):0);
  /* #130: @13 = (!@6) */
  w13 = (! w6 );
  /* #131: @42 = (@13?@42:0) */
  for (i=0, rr=w42, cs=w42; i<4; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #132: @43 = (@43+@42) */
  for (i=0, rr=w43, cs=w42; i<4; ++i) (*rr++) += (*cs++);
  /* #133: @44 = @43[1:4] */
  for (rr=w44, ss=w43+1; ss!=w43+4; ss+=1) *rr++ = *ss;
  /* #134: @45 = (2.*@44) */
  for (i=0, rr=w45, cs=w44; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #135: @15 = ||@44||_F */
  w15 = sqrt(casadi_dot(3, w44, w44));
  /* #136: @16 = @43[0] */
  for (rr=(&w16), ss=w43+0; ss!=w43+1; ss+=1) *rr++ = *ss;
  /* #137: @12 = atan2(@15,@16) */
  w12  = atan2(w15,w16);
  /* #138: @46 = (@45*@12) */
  for (i=0, rr=w46, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w12);
  /* #139: @46 = (@46/@15) */
  for (i=0, rr=w46; i<3; ++i) (*rr++) /= w15;
  /* #140: @47 = @46' */
  casadi_copy(w46, 3, w47);
  /* #141: @48 = zeros(3x3) */
  casadi_clear(w48, 9);
  /* #142: @5 = 1 */
  w5 = 1.;
  /* #143: (@48[0] = @5) */
  for (rr=w48+0, ss=(&w5); rr!=w48+1; rr+=1) *rr = *ss++;
  /* #144: @5 = 1 */
  w5 = 1.;
  /* #145: (@48[4] = @5) */
  for (rr=w48+4, ss=(&w5); rr!=w48+5; rr+=1) *rr = *ss++;
  /* #146: @5 = 1 */
  w5 = 1.;
  /* #147: (@48[8] = @5) */
  for (rr=w48+8, ss=(&w5); rr!=w48+9; rr+=1) *rr = *ss++;
  /* #148: @38 = mac(@47,@48,@38) */
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #149: @3 = mac(@38,@46,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #150: @0 = (@0+@3) */
  w0 += w3;
  /* #151: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #152: @34 = zeros(21x1) */
  casadi_clear(w34, 21);
  /* #153: @43 = (@40/@11) */
  for (i=0, rr=w43, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)/w11);
  /* #154: @42 = (-@43) */
  for (i=0, rr=w42, cs=w43; i<4; ++i) *rr++ = (- *cs++ );
  /* #155: @49 = zeros(4x1) */
  casadi_clear(w49, 4);
  /* #156: @0 = 1 */
  w0 = 1.;
  /* #157: @0 = (@13?@0:0) */
  w0  = (w13?w0:0);
  /* #158: @50 = zeros(4x1) */
  casadi_clear(w50, 4);
  /* #159: @3 = sq(@15) */
  w3 = casadi_sq( w15 );
  /* #160: @5 = sq(@16) */
  w5 = casadi_sq( w16 );
  /* #161: @3 = (@3+@5) */
  w3 += w5;
  /* #162: @5 = (@15/@3) */
  w5  = (w15/w3);
  /* #163: @38 = @38' */
  /* #164: @47 = zeros(1x3) */
  casadi_clear(w47, 3);
  /* #165: @51 = @46' */
  casadi_copy(w46, 3, w51);
  /* #166: @52 = @48' */
  for (i=0, rr=w52, cs=w48; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #167: @47 = mac(@51,@52,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w51+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #168: @47 = @47' */
  /* #169: @38 = (@38+@47) */
  for (i=0, rr=w38, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #170: @47 = (@38/@15) */
  for (i=0, rr=w47, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #171: @4 = dot(@45, @47) */
  w4 = casadi_dot(3, w45, w47);
  /* #172: @14 = (@5*@4) */
  w14  = (w5*w4);
  /* #173: @14 = (-@14) */
  w14 = (- w14 );
  /* #174: (@50[0] += @14) */
  for (rr=w50+0, ss=(&w14); rr!=w50+1; rr+=1) *rr += *ss++;
  /* #175: @51 = (@46/@15) */
  for (i=0, rr=w51, cr=w46; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #176: @53 = (-@51) */
  for (i=0, rr=w53, cs=w51; i<3; ++i) *rr++ = (- *cs++ );
  /* #177: @14 = dot(@53, @38) */
  w14 = casadi_dot(3, w53, w38);
  /* #178: @17 = (@16/@3) */
  w17  = (w16/w3);
  /* #179: @18 = (@17*@4) */
  w18  = (w17*w4);
  /* #180: @14 = (@14+@18) */
  w14 += w18;
  /* #181: @14 = (@14/@15) */
  w14 /= w15;
  /* #182: @54 = (@14*@44) */
  for (i=0, rr=w54, cs=w44; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #183: @55 = (@12*@47) */
  for (i=0, rr=w55, cs=w47; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #184: @55 = (2.*@55) */
  for (i=0, rr=w55, cs=w55; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #185: @54 = (@54+@55) */
  for (i=0, rr=w54, cs=w55; i<3; ++i) (*rr++) += (*cs++);
  /* #186: (@50[1:4] += @54) */
  for (rr=w50+1, ss=w54; rr!=w50+4; rr+=1) *rr += *ss++;
  /* #187: @56 = (@0*@50) */
  for (i=0, rr=w56, cs=w50; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #188: @18 = 1 */
  w18 = 1.;
  /* #189: @18 = (@6?@18:0) */
  w18  = (w6?w18:0);
  /* #190: @50 = (@18*@50) */
  for (i=0, rr=w50, cs=w50; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #191: @56 = (@56-@50) */
  for (i=0, rr=w56, cs=w50; i<4; ++i) (*rr++) -= (*cs++);
  /* #192: {@19, @20, @21, @22} = vertsplit(@56) */
  w19 = w56[0];
  w20 = w56[1];
  w21 = w56[2];
  w22 = w56[3];
  /* #193: @23 = (@7*@22) */
  w23  = (w7*w22);
  /* #194: @24 = (@8*@21) */
  w24  = (w8*w21);
  /* #195: @23 = (@23+@24) */
  w23 += w24;
  /* #196: @24 = (@9*@20) */
  w24  = (w9*w20);
  /* #197: @23 = (@23-@24) */
  w23 -= w24;
  /* #198: @24 = (@10*@19) */
  w24  = (w10*w19);
  /* #199: @23 = (@23-@24) */
  w23 -= w24;
  /* #200: (@49[3] += @23) */
  for (rr=w49+3, ss=(&w23); rr!=w49+4; rr+=1) *rr += *ss++;
  /* #201: @23 = (@7*@21) */
  w23  = (w7*w21);
  /* #202: @24 = (@8*@22) */
  w24  = (w8*w22);
  /* #203: @23 = (@23-@24) */
  w23 -= w24;
  /* #204: @24 = (@10*@20) */
  w24  = (w10*w20);
  /* #205: @23 = (@23+@24) */
  w23 += w24;
  /* #206: @24 = (@9*@19) */
  w24  = (w9*w19);
  /* #207: @23 = (@23-@24) */
  w23 -= w24;
  /* #208: (@49[2] += @23) */
  for (rr=w49+2, ss=(&w23); rr!=w49+3; rr+=1) *rr += *ss++;
  /* #209: @23 = (@9*@22) */
  w23  = (w9*w22);
  /* #210: @24 = (@10*@21) */
  w24  = (w10*w21);
  /* #211: @23 = (@23-@24) */
  w23 -= w24;
  /* #212: @24 = (@7*@20) */
  w24  = (w7*w20);
  /* #213: @23 = (@23+@24) */
  w23 += w24;
  /* #214: @24 = (@8*@19) */
  w24  = (w8*w19);
  /* #215: @23 = (@23-@24) */
  w23 -= w24;
  /* #216: (@49[1] += @23) */
  for (rr=w49+1, ss=(&w23); rr!=w49+2; rr+=1) *rr += *ss++;
  /* #217: @22 = (@10*@22) */
  w22  = (w10*w22);
  /* #218: @21 = (@9*@21) */
  w21  = (w9*w21);
  /* #219: @22 = (@22+@21) */
  w22 += w21;
  /* #220: @20 = (@8*@20) */
  w20  = (w8*w20);
  /* #221: @22 = (@22+@20) */
  w22 += w20;
  /* #222: @19 = (@7*@19) */
  w19  = (w7*w19);
  /* #223: @22 = (@22+@19) */
  w22 += w19;
  /* #224: (@49[0] += @22) */
  for (rr=w49+0, ss=(&w22); rr!=w49+1; rr+=1) *rr += *ss++;
  /* #225: @22 = dot(@42, @49) */
  w22 = casadi_dot(4, w42, w49);
  /* #226: @22 = (@22/@11) */
  w22 /= w11;
  /* #227: @56 = (@22*@41) */
  for (i=0, rr=w56, cs=w41; i<4; ++i) (*rr++)  = (w22*(*cs++));
  /* #228: (@34[4:8] += @56) */
  for (rr=w34+4, ss=w56; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #229: @35 = @35' */
  /* #230: @54 = zeros(1x3) */
  casadi_clear(w54, 3);
  /* #231: @37 = @37' */
  /* #232: @57 = @39' */
  for (i=0, rr=w57, cs=w39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #233: @54 = mac(@37,@57,@54) */
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w57+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #234: @54 = (@31*@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #235: @54 = @54' */
  /* #236: @35 = (@35+@54) */
  for (i=0, rr=w35, cs=w54; i<3; ++i) (*rr++) += (*cs++);
  /* #237: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #238: (@34[11:14] += @35) */
  for (rr=w34+11, ss=w35; rr!=w34+14; rr+=1) *rr += *ss++;
  /* #239: @1 = @1' */
  /* #240: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #241: @33 = @33' */
  /* #242: @58 = @36' */
  for (i=0, rr=w58, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: @35 = mac(@33,@58,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w58+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #244: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #245: @35 = @35' */
  /* #246: @1 = (@1+@35) */
  for (i=0, rr=w1, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #247: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #248: (@34[:3] += @1) */
  for (rr=w34+0, ss=w1; rr!=w34+3; rr+=1) *rr += *ss++;
  /* #249: {@19, @20, @21, @23, @24, @25, @26, @27, @28, @29, @30, @59, @60, @61, @62, @63, @64, @65, @66, @67, @68} = vertsplit(@34) */
  w19 = w34[0];
  w20 = w34[1];
  w21 = w34[2];
  w23 = w34[3];
  w24 = w34[4];
  w25 = w34[5];
  w26 = w34[6];
  w27 = w34[7];
  w28 = w34[8];
  w29 = w34[9];
  w30 = w34[10];
  w59 = w34[11];
  w60 = w34[12];
  w61 = w34[13];
  w62 = w34[14];
  w63 = w34[15];
  w64 = w34[16];
  w65 = w34[17];
  w66 = w34[18];
  w67 = w34[19];
  w68 = w34[20];
  /* #250: output[1][0] = @19 */
  if (res[1]) res[1][0] = w19;
  /* #251: output[1][1] = @20 */
  if (res[1]) res[1][1] = w20;
  /* #252: output[1][2] = @21 */
  if (res[1]) res[1][2] = w21;
  /* #253: output[1][3] = @23 */
  if (res[1]) res[1][3] = w23;
  /* #254: @56 = (@49/@11) */
  for (i=0, rr=w56, cr=w49; i<4; ++i) (*rr++)  = ((*cr++)/w11);
  /* #255: {@23, @21, @20, @19} = vertsplit(@56) */
  w23 = w56[0];
  w21 = w56[1];
  w20 = w56[2];
  w19 = w56[3];
  /* #256: @23 = (@23+@24) */
  w23 += w24;
  /* #257: output[1][4] = @23 */
  if (res[1]) res[1][4] = w23;
  /* #258: @25 = (@25-@21) */
  w25 -= w21;
  /* #259: output[1][5] = @25 */
  if (res[1]) res[1][5] = w25;
  /* #260: @26 = (@26-@20) */
  w26 -= w20;
  /* #261: output[1][6] = @26 */
  if (res[1]) res[1][6] = w26;
  /* #262: @27 = (@27-@19) */
  w27 -= w19;
  /* #263: output[1][7] = @27 */
  if (res[1]) res[1][7] = w27;
  /* #264: output[1][8] = @28 */
  if (res[1]) res[1][8] = w28;
  /* #265: output[1][9] = @29 */
  if (res[1]) res[1][9] = w29;
  /* #266: output[1][10] = @30 */
  if (res[1]) res[1][10] = w30;
  /* #267: output[1][11] = @59 */
  if (res[1]) res[1][11] = w59;
  /* #268: output[1][12] = @60 */
  if (res[1]) res[1][12] = w60;
  /* #269: output[1][13] = @61 */
  if (res[1]) res[1][13] = w61;
  /* #270: output[1][14] = @62 */
  if (res[1]) res[1][14] = w62;
  /* #271: output[1][15] = @63 */
  if (res[1]) res[1][15] = w63;
  /* #272: output[1][16] = @64 */
  if (res[1]) res[1][16] = w64;
  /* #273: output[1][17] = @65 */
  if (res[1]) res[1][17] = w65;
  /* #274: output[1][18] = @66 */
  if (res[1]) res[1][18] = w66;
  /* #275: output[1][19] = @67 */
  if (res[1]) res[1][19] = w67;
  /* #276: output[1][20] = @68 */
  if (res[1]) res[1][20] = w68;
  /* #277: @69 = zeros(21x21,34nz) */
  casadi_clear(w69, 34);
  /* #278: @34 = zeros(21x1) */
  casadi_clear(w34, 21);
  /* #279: @50 = zeros(4x1) */
  casadi_clear(w50, 4);
  /* #280: @70 = zeros(4x1) */
  casadi_clear(w70, 4);
  /* #281: @68 = 1 */
  w68 = 1.;
  /* #282: @13 = (@13?@68:0) */
  w13  = (w13?w68:0);
  /* #283: @71 = ones(21x1,14nz) */
  casadi_fill(w71, 14, 1.);
  /* #284: {@68, NULL, NULL, NULL, @67, NULL, NULL, NULL, NULL, NULL, NULL, @66, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@71) */
  w68 = w71[0];
  w67 = w71[2];
  w66 = w71[6];
  /* #285: @72 = 00 */
  /* #286: @73 = 00 */
  /* #287: @74 = 00 */
  /* #288: @65 = vertcat(@67, @72, @73, @74) */
  rr=(&w65);
  *rr++ = w67;
  /* #289: @65 = (@65/@11) */
  w65 /= w11;
  /* #290: @75 = dense(@65) */
  casadi_densify((&w65), casadi_s0, w75, 0);
  /* #291: @40 = (@40/@11) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w11;
  /* #292: @65 = project(@41) */
  casadi_sparsify(w41, (&w65), casadi_s0, 0);
  /* #293: @64 = @67[0] */
  for (rr=(&w64), ss=(&w67)+0; ss!=(&w67)+1; ss+=1) *rr++ = *ss;
  /* #294: @67 = dot(@65, @64) */
  w67 = casadi_dot(1, (&w65), (&w64));
  /* #295: @67 = (@67/@11) */
  w67 /= w11;
  /* #296: @76 = (@40*@67) */
  for (i=0, rr=w76, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w67);
  /* #297: @75 = (@75-@76) */
  for (i=0, rr=w75, cs=w76; i<4; ++i) (*rr++) -= (*cs++);
  /* #298: @65 = @75[0] */
  for (rr=(&w65), ss=w75+0; ss!=w75+1; ss+=1) *rr++ = *ss;
  /* #299: @63 = (@7*@65) */
  w63  = (w7*w65);
  /* #300: @62 = @75[1] */
  for (rr=(&w62), ss=w75+1; ss!=w75+2; ss+=1) *rr++ = *ss;
  /* #301: @61 = (@8*@62) */
  w61  = (w8*w62);
  /* #302: @63 = (@63-@61) */
  w63 -= w61;
  /* #303: @61 = @75[2] */
  for (rr=(&w61), ss=w75+2; ss!=w75+3; ss+=1) *rr++ = *ss;
  /* #304: @60 = (@9*@61) */
  w60  = (w9*w61);
  /* #305: @63 = (@63-@60) */
  w63 -= w60;
  /* #306: @60 = @75[3] */
  for (rr=(&w60), ss=w75+3; ss!=w75+4; ss+=1) *rr++ = *ss;
  /* #307: @59 = (@10*@60) */
  w59  = (w10*w60);
  /* #308: @63 = (@63-@59) */
  w63 -= w59;
  /* #309: @59 = (@8*@65) */
  w59  = (w8*w65);
  /* #310: @30 = (@7*@62) */
  w30  = (w7*w62);
  /* #311: @59 = (@59+@30) */
  w59 += w30;
  /* #312: @30 = (@10*@61) */
  w30  = (w10*w61);
  /* #313: @59 = (@59+@30) */
  w59 += w30;
  /* #314: @30 = (@9*@60) */
  w30  = (w9*w60);
  /* #315: @59 = (@59-@30) */
  w59 -= w30;
  /* #316: @30 = (@9*@65) */
  w30  = (w9*w65);
  /* #317: @29 = (@10*@62) */
  w29  = (w10*w62);
  /* #318: @30 = (@30-@29) */
  w30 -= w29;
  /* #319: @29 = (@7*@61) */
  w29  = (w7*w61);
  /* #320: @30 = (@30+@29) */
  w30 += w29;
  /* #321: @29 = (@8*@60) */
  w29  = (w8*w60);
  /* #322: @30 = (@30+@29) */
  w30 += w29;
  /* #323: @65 = (@10*@65) */
  w65  = (w10*w65);
  /* #324: @62 = (@9*@62) */
  w62  = (w9*w62);
  /* #325: @65 = (@65+@62) */
  w65 += w62;
  /* #326: @61 = (@8*@61) */
  w61  = (w8*w61);
  /* #327: @65 = (@65-@61) */
  w65 -= w61;
  /* #328: @60 = (@7*@60) */
  w60  = (w7*w60);
  /* #329: @65 = (@65+@60) */
  w65 += w60;
  /* #330: @76 = vertcat(@63, @59, @30, @65) */
  rr=w76;
  *rr++ = w63;
  *rr++ = w59;
  *rr++ = w30;
  *rr++ = w65;
  /* #331: @77 = (@13*@76) */
  for (i=0, rr=w77, cs=w76; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #332: @63 = 1 */
  w63 = 1.;
  /* #333: @6 = (@6?@63:0) */
  w6  = (w6?w63:0);
  /* #334: @76 = (@6*@76) */
  for (i=0, rr=w76, cs=w76; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #335: @77 = (@77-@76) */
  for (i=0, rr=w77, cs=w76; i<4; ++i) (*rr++) -= (*cs++);
  /* #336: @1 = @77[1:4] */
  for (rr=w1, ss=w77+1; ss!=w77+4; ss+=1) *rr++ = *ss;
  /* #337: @63 = dot(@44, @1) */
  w63 = casadi_dot(3, w44, w1);
  /* #338: @63 = (@63/@15) */
  w63 /= w15;
  /* #339: @59 = (@63/@3) */
  w59  = (w63/w3);
  /* #340: @30 = (@5/@3) */
  w30  = (w5/w3);
  /* #341: @65 = (2.*@15) */
  w65 = (2.* w15 );
  /* #342: @60 = (@65*@63) */
  w60  = (w65*w63);
  /* #343: @61 = (2.*@16) */
  w61 = (2.* w16 );
  /* #344: @62 = @77[0] */
  for (rr=(&w62), ss=w77+0; ss!=w77+1; ss+=1) *rr++ = *ss;
  /* #345: @29 = (@61*@62) */
  w29  = (w61*w62);
  /* #346: @60 = (@60+@29) */
  w60 += w29;
  /* #347: @29 = (@30*@60) */
  w29  = (w30*w60);
  /* #348: @59 = (@59-@29) */
  w59 -= w29;
  /* #349: @59 = (@4*@59) */
  w59  = (w4*w59);
  /* #350: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #351: @33 = (2.*@1) */
  for (i=0, rr=w33, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #352: @54 = (@12*@33) */
  for (i=0, rr=w54, cs=w33; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #353: @29 = sq(@15) */
  w29 = casadi_sq( w15 );
  /* #354: @28 = sq(@16) */
  w28 = casadi_sq( w16 );
  /* #355: @29 = (@29+@28) */
  w29 += w28;
  /* #356: @16 = (@16/@29) */
  w16 /= w29;
  /* #357: @28 = (@16*@63) */
  w28  = (w16*w63);
  /* #358: @29 = (@15/@29) */
  w29  = (w15/w29);
  /* #359: @27 = (@29*@62) */
  w27  = (w29*w62);
  /* #360: @28 = (@28-@27) */
  w28 -= w27;
  /* #361: @37 = (@45*@28) */
  for (i=0, rr=w37, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #362: @54 = (@54+@37) */
  for (i=0, rr=w54, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #363: @54 = (@54/@15) */
  for (i=0, rr=w54; i<3; ++i) (*rr++) /= w15;
  /* #364: @46 = (@46/@15) */
  for (i=0, rr=w46; i<3; ++i) (*rr++) /= w15;
  /* #365: @37 = (@46*@63) */
  for (i=0, rr=w37, cr=w46; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #366: @54 = (@54-@37) */
  for (i=0, rr=w54, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #367: @37 = @54' */
  casadi_copy(w54, 3, w37);
  /* #368: @35 = mac(@37,@48,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #369: @35 = @35' */
  /* #370: @37 = zeros(1x3) */
  casadi_clear(w37, 3);
  /* #371: @55 = @54' */
  casadi_copy(w54, 3, w55);
  /* #372: @37 = mac(@55,@52,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w55+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #373: @37 = @37' */
  /* #374: @35 = (@35+@37) */
  for (i=0, rr=w35, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #375: @37 = (@35/@15) */
  for (i=0, rr=w37, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #376: @55 = (@47/@15) */
  for (i=0, rr=w55, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #377: @78 = (@55*@63) */
  for (i=0, rr=w78, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #378: @37 = (@37-@78) */
  for (i=0, rr=w37, cs=w78; i<3; ++i) (*rr++) -= (*cs++);
  /* #379: @27 = dot(@45, @37) */
  w27 = casadi_dot(3, w45, w37);
  /* #380: @19 = dot(@33, @47) */
  w19 = casadi_dot(3, w33, w47);
  /* #381: @27 = (@27+@19) */
  w27 += w19;
  /* #382: @19 = (@5*@27) */
  w19  = (w5*w27);
  /* #383: @59 = (@59+@19) */
  w59 += w19;
  /* #384: @59 = (-@59) */
  w59 = (- w59 );
  /* #385: (@70[0] += @59) */
  for (rr=w70+0, ss=(&w59); rr!=w70+1; rr+=1) *rr += *ss++;
  /* #386: @59 = dot(@53, @35) */
  w59 = casadi_dot(3, w53, w35);
  /* #387: @54 = (@54/@15) */
  for (i=0, rr=w54; i<3; ++i) (*rr++) /= w15;
  /* #388: @51 = (@51/@15) */
  for (i=0, rr=w51; i<3; ++i) (*rr++) /= w15;
  /* #389: @35 = (@51*@63) */
  for (i=0, rr=w35, cr=w51; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #390: @54 = (@54-@35) */
  for (i=0, rr=w54, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #391: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) *rr++ = (- *cs++ );
  /* #392: @19 = dot(@54, @38) */
  w19 = casadi_dot(3, w54, w38);
  /* #393: @59 = (@59+@19) */
  w59 += w19;
  /* #394: @62 = (@62/@3) */
  w62 /= w3;
  /* #395: @19 = (@17/@3) */
  w19  = (w17/w3);
  /* #396: @60 = (@19*@60) */
  w60  = (w19*w60);
  /* #397: @62 = (@62-@60) */
  w62 -= w60;
  /* #398: @62 = (@4*@62) */
  w62  = (w4*w62);
  /* #399: @27 = (@17*@27) */
  w27  = (w17*w27);
  /* #400: @62 = (@62+@27) */
  w62 += w27;
  /* #401: @59 = (@59+@62) */
  w59 += w62;
  /* #402: @59 = (@59/@15) */
  w59 /= w15;
  /* #403: @62 = (@14/@15) */
  w62  = (w14/w15);
  /* #404: @63 = (@62*@63) */
  w63  = (w62*w63);
  /* #405: @59 = (@59-@63) */
  w59 -= w63;
  /* #406: @54 = (@44*@59) */
  for (i=0, rr=w54, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w59);
  /* #407: @1 = (@14*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #408: @54 = (@54+@1) */
  for (i=0, rr=w54, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #409: @1 = (@47*@28) */
  for (i=0, rr=w1, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w28);
  /* #410: @37 = (@12*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #411: @1 = (@1+@37) */
  for (i=0, rr=w1, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #412: @1 = (2.*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #413: @54 = (@54+@1) */
  for (i=0, rr=w54, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #414: (@70[1:4] += @54) */
  for (rr=w70+1, ss=w54; rr!=w70+4; rr+=1) *rr += *ss++;
  /* #415: @77 = (@0*@70) */
  for (i=0, rr=w77, cs=w70; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #416: @70 = (@18*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #417: @77 = (@77-@70) */
  for (i=0, rr=w77, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #418: {@28, @59, @63, @27} = vertsplit(@77) */
  w28 = w77[0];
  w59 = w77[1];
  w63 = w77[2];
  w27 = w77[3];
  /* #419: @60 = (@7*@27) */
  w60  = (w7*w27);
  /* #420: @26 = (@8*@63) */
  w26  = (w8*w63);
  /* #421: @60 = (@60+@26) */
  w60 += w26;
  /* #422: @26 = (@9*@59) */
  w26  = (w9*w59);
  /* #423: @60 = (@60-@26) */
  w60 -= w26;
  /* #424: @26 = (@10*@28) */
  w26  = (w10*w28);
  /* #425: @60 = (@60-@26) */
  w60 -= w26;
  /* #426: (@50[3] += @60) */
  for (rr=w50+3, ss=(&w60); rr!=w50+4; rr+=1) *rr += *ss++;
  /* #427: @60 = (@7*@63) */
  w60  = (w7*w63);
  /* #428: @26 = (@8*@27) */
  w26  = (w8*w27);
  /* #429: @60 = (@60-@26) */
  w60 -= w26;
  /* #430: @26 = (@10*@59) */
  w26  = (w10*w59);
  /* #431: @60 = (@60+@26) */
  w60 += w26;
  /* #432: @26 = (@9*@28) */
  w26  = (w9*w28);
  /* #433: @60 = (@60-@26) */
  w60 -= w26;
  /* #434: (@50[2] += @60) */
  for (rr=w50+2, ss=(&w60); rr!=w50+3; rr+=1) *rr += *ss++;
  /* #435: @60 = (@9*@27) */
  w60  = (w9*w27);
  /* #436: @26 = (@10*@63) */
  w26  = (w10*w63);
  /* #437: @60 = (@60-@26) */
  w60 -= w26;
  /* #438: @26 = (@7*@59) */
  w26  = (w7*w59);
  /* #439: @60 = (@60+@26) */
  w60 += w26;
  /* #440: @26 = (@8*@28) */
  w26  = (w8*w28);
  /* #441: @60 = (@60-@26) */
  w60 -= w26;
  /* #442: (@50[1] += @60) */
  for (rr=w50+1, ss=(&w60); rr!=w50+2; rr+=1) *rr += *ss++;
  /* #443: @27 = (@10*@27) */
  w27  = (w10*w27);
  /* #444: @63 = (@9*@63) */
  w63  = (w9*w63);
  /* #445: @27 = (@27+@63) */
  w27 += w63;
  /* #446: @59 = (@8*@59) */
  w59  = (w8*w59);
  /* #447: @27 = (@27+@59) */
  w27 += w59;
  /* #448: @28 = (@7*@28) */
  w28  = (w7*w28);
  /* #449: @27 = (@27+@28) */
  w27 += w28;
  /* #450: (@50[0] += @27) */
  for (rr=w50+0, ss=(&w27); rr!=w50+1; rr+=1) *rr += *ss++;
  /* #451: @27 = dot(@42, @50) */
  w27 = casadi_dot(4, w42, w50);
  /* #452: @75 = (@75/@11) */
  for (i=0, rr=w75; i<4; ++i) (*rr++) /= w11;
  /* #453: @43 = (@43/@11) */
  for (i=0, rr=w43; i<4; ++i) (*rr++) /= w11;
  /* #454: @77 = (@43*@67) */
  for (i=0, rr=w77, cr=w43; i<4; ++i) (*rr++)  = ((*cr++)*w67);
  /* #455: @75 = (@75-@77) */
  for (i=0, rr=w75, cs=w77; i<4; ++i) (*rr++) -= (*cs++);
  /* #456: @75 = (-@75) */
  for (i=0, rr=w75, cs=w75; i<4; ++i) *rr++ = (- *cs++ );
  /* #457: @28 = dot(@75, @49) */
  w28 = casadi_dot(4, w75, w49);
  /* #458: @27 = (@27+@28) */
  w27 += w28;
  /* #459: @27 = (@27/@11) */
  w27 /= w11;
  /* #460: @28 = (@22/@11) */
  w28  = (w22/w11);
  /* #461: @59 = (@28*@67) */
  w59  = (w28*w67);
  /* #462: @27 = (@27-@59) */
  w27 -= w59;
  /* #463: @75 = (@41*@27) */
  for (i=0, rr=w75, cr=w41; i<4; ++i) (*rr++)  = ((*cr++)*w27);
  /* #464: @64 = (@22*@64) */
  w64  = (w22*w64);
  /* #465: @77 = dense(@64) */
  casadi_densify((&w64), casadi_s0, w77, 0);
  /* #466: @75 = (@75+@77) */
  for (i=0, rr=w75, cs=w77; i<4; ++i) (*rr++) += (*cs++);
  /* #467: (@34[4:8] += @75) */
  for (rr=w34+4, ss=w75; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #468: @54 = zeros(1x3) */
  casadi_clear(w54, 3);
  /* #469: @64 = @66[0] */
  for (rr=(&w64), ss=(&w66)+0; ss!=(&w66)+1; ss+=1) *rr++ = *ss;
  /* #470: @64 = (-@64) */
  w64 = (- w64 );
  /* #471: @66 = @64' */
  casadi_copy((&w64), 1, (&w66));
  /* #472: @66 = (@31*@66) */
  w66  = (w31*w66);
  /* #473: @54 = mac(@66,@39,@54) */
  casadi_mtimes((&w66), casadi_s3, w39, casadi_s2, w54, casadi_s1, w, 0);
  /* #474: @54 = @54' */
  /* #475: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #476: @64 = @64' */
  /* #477: @1 = mac(@64,@57,@1) */
  casadi_mtimes((&w64), casadi_s3, w57, casadi_s2, w1, casadi_s1, w, 0);
  /* #478: @1 = (@31*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #479: @1 = @1' */
  /* #480: @54 = (@54+@1) */
  for (i=0, rr=w54, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #481: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) *rr++ = (- *cs++ );
  /* #482: (@34[11:14] += @54) */
  for (rr=w34+11, ss=w54; rr!=w34+14; rr+=1) *rr += *ss++;
  /* #483: @54 = zeros(1x3) */
  casadi_clear(w54, 3);
  /* #484: @64 = @68[0] */
  for (rr=(&w64), ss=(&w68)+0; ss!=(&w68)+1; ss+=1) *rr++ = *ss;
  /* #485: @64 = (-@64) */
  w64 = (- w64 );
  /* #486: @68 = @64' */
  casadi_copy((&w64), 1, (&w68));
  /* #487: @68 = (@2*@68) */
  w68  = (w2*w68);
  /* #488: @54 = mac(@68,@36,@54) */
  casadi_mtimes((&w68), casadi_s3, w36, casadi_s2, w54, casadi_s1, w, 0);
  /* #489: @54 = @54' */
  /* #490: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #491: @64 = @64' */
  /* #492: @1 = mac(@64,@58,@1) */
  casadi_mtimes((&w64), casadi_s3, w58, casadi_s2, w1, casadi_s1, w, 0);
  /* #493: @1 = (@2*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #494: @1 = @1' */
  /* #495: @54 = (@54+@1) */
  for (i=0, rr=w54, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #496: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) *rr++ = (- *cs++ );
  /* #497: (@34[:3] += @54) */
  for (rr=w34+0, ss=w54; rr!=w34+3; rr+=1) *rr += *ss++;
  /* #498: {@64, @68, @66, @27, @59, @63, @60, @26, @20, @25, @21, @23, @24, @79, @80, @81, @82, @83, @84, @85, @86} = vertsplit(@34) */
  w64 = w34[0];
  w68 = w34[1];
  w66 = w34[2];
  w27 = w34[3];
  w59 = w34[4];
  w63 = w34[5];
  w60 = w34[6];
  w26 = w34[7];
  w20 = w34[8];
  w25 = w34[9];
  w21 = w34[10];
  w23 = w34[11];
  w24 = w34[12];
  w79 = w34[13];
  w80 = w34[14];
  w81 = w34[15];
  w82 = w34[16];
  w83 = w34[17];
  w84 = w34[18];
  w85 = w34[19];
  w86 = w34[20];
  /* #499: @50 = (@50/@11) */
  for (i=0, rr=w50; i<4; ++i) (*rr++) /= w11;
  /* #500: @56 = (@56/@11) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) /= w11;
  /* #501: @75 = (@56*@67) */
  for (i=0, rr=w75, cr=w56; i<4; ++i) (*rr++)  = ((*cr++)*w67);
  /* #502: @50 = (@50-@75) */
  for (i=0, rr=w50, cs=w75; i<4; ++i) (*rr++) -= (*cs++);
  /* #503: {@67, @87, @88, @89} = vertsplit(@50) */
  w67 = w50[0];
  w87 = w50[1];
  w88 = w50[2];
  w89 = w50[3];
  /* #504: @67 = (@67+@59) */
  w67 += w59;
  /* #505: @63 = (@63-@87) */
  w63 -= w87;
  /* #506: @60 = (@60-@88) */
  w60 -= w88;
  /* #507: @26 = (@26-@89) */
  w26 -= w89;
  /* #508: @34 = vertcat(@64, @68, @66, @27, @67, @63, @60, @26, @20, @25, @21, @23, @24, @79, @80, @81, @82, @83, @84, @85, @86) */
  rr=w34;
  *rr++ = w64;
  *rr++ = w68;
  *rr++ = w66;
  *rr++ = w27;
  *rr++ = w67;
  *rr++ = w63;
  *rr++ = w60;
  *rr++ = w26;
  *rr++ = w20;
  *rr++ = w25;
  *rr++ = w21;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w79;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w85;
  *rr++ = w86;
  /* #509: @90 = @34[0, 1, 2, 4, 5, 6, 7, 11, 12, 13] */
  for (cii=casadi_s4, rr=w90, ss=w34; cii!=casadi_s4+10; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #510: (@69[0, 1, 2, 9, 10, 11, 12, 25, 26, 27] = @90) */
  for (cii=casadi_s5, rr=w69, ss=w90; cii!=casadi_s5+10; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #511: @90 = @34[0, 1, 2, 4, 5, 6, 7, 11, 12, 13] */
  for (cii=casadi_s4, rr=w90, ss=w34; cii!=casadi_s4+10; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #512: (@69[0, 3, 6, 9, 13, 17, 21, 25, 28, 31] = @90) */
  for (cii=casadi_s6, rr=w69, ss=w90; cii!=casadi_s6+10; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #513: @34 = zeros(21x1) */
  casadi_clear(w34, 21);
  /* #514: @50 = zeros(4x1) */
  casadi_clear(w50, 4);
  /* #515: @75 = zeros(4x1) */
  casadi_clear(w75, 4);
  /* #516: @72 = 00 */
  /* #517: @54 = ones(21x1,3nz) */
  casadi_fill(w54, 3, 1.);
  /* #518: {NULL, @64, NULL, NULL, NULL, @68, NULL, NULL, NULL, NULL, NULL, NULL, @66, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@54) */
  w64 = w54[0];
  w68 = w54[1];
  w66 = w54[2];
  /* #519: @27 = (-@68) */
  w27 = (- w68 );
  /* #520: @73 = 00 */
  /* #521: @74 = 00 */
  /* #522: @67 = vertcat(@72, @27, @73, @74) */
  rr=(&w67);
  *rr++ = w27;
  /* #523: @67 = (@67/@11) */
  w67 /= w11;
  /* #524: @77 = dense(@67) */
  casadi_densify((&w67), casadi_s7, w77, 0);
  /* #525: @67 = project(@41) */
  casadi_sparsify(w41, (&w67), casadi_s7, 0);
  /* #526: @27 = @68[0] */
  for (rr=(&w27), ss=(&w68)+0; ss!=(&w68)+1; ss+=1) *rr++ = *ss;
  /* #527: @68 = dot(@67, @27) */
  w68 = casadi_dot(1, (&w67), (&w27));
  /* #528: @68 = (@68/@11) */
  w68 /= w11;
  /* #529: @70 = (@40*@68) */
  for (i=0, rr=w70, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w68);
  /* #530: @77 = (@77-@70) */
  for (i=0, rr=w77, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #531: @67 = @77[0] */
  for (rr=(&w67), ss=w77+0; ss!=w77+1; ss+=1) *rr++ = *ss;
  /* #532: @63 = (@7*@67) */
  w63  = (w7*w67);
  /* #533: @60 = @77[1] */
  for (rr=(&w60), ss=w77+1; ss!=w77+2; ss+=1) *rr++ = *ss;
  /* #534: @26 = (@8*@60) */
  w26  = (w8*w60);
  /* #535: @63 = (@63-@26) */
  w63 -= w26;
  /* #536: @26 = @77[2] */
  for (rr=(&w26), ss=w77+2; ss!=w77+3; ss+=1) *rr++ = *ss;
  /* #537: @20 = (@9*@26) */
  w20  = (w9*w26);
  /* #538: @63 = (@63-@20) */
  w63 -= w20;
  /* #539: @20 = @77[3] */
  for (rr=(&w20), ss=w77+3; ss!=w77+4; ss+=1) *rr++ = *ss;
  /* #540: @25 = (@10*@20) */
  w25  = (w10*w20);
  /* #541: @63 = (@63-@25) */
  w63 -= w25;
  /* #542: @25 = (@8*@67) */
  w25  = (w8*w67);
  /* #543: @21 = (@7*@60) */
  w21  = (w7*w60);
  /* #544: @25 = (@25+@21) */
  w25 += w21;
  /* #545: @21 = (@10*@26) */
  w21  = (w10*w26);
  /* #546: @25 = (@25+@21) */
  w25 += w21;
  /* #547: @21 = (@9*@20) */
  w21  = (w9*w20);
  /* #548: @25 = (@25-@21) */
  w25 -= w21;
  /* #549: @21 = (@9*@67) */
  w21  = (w9*w67);
  /* #550: @23 = (@10*@60) */
  w23  = (w10*w60);
  /* #551: @21 = (@21-@23) */
  w21 -= w23;
  /* #552: @23 = (@7*@26) */
  w23  = (w7*w26);
  /* #553: @21 = (@21+@23) */
  w21 += w23;
  /* #554: @23 = (@8*@20) */
  w23  = (w8*w20);
  /* #555: @21 = (@21+@23) */
  w21 += w23;
  /* #556: @67 = (@10*@67) */
  w67  = (w10*w67);
  /* #557: @60 = (@9*@60) */
  w60  = (w9*w60);
  /* #558: @67 = (@67+@60) */
  w67 += w60;
  /* #559: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #560: @67 = (@67-@26) */
  w67 -= w26;
  /* #561: @20 = (@7*@20) */
  w20  = (w7*w20);
  /* #562: @67 = (@67+@20) */
  w67 += w20;
  /* #563: @70 = vertcat(@63, @25, @21, @67) */
  rr=w70;
  *rr++ = w63;
  *rr++ = w25;
  *rr++ = w21;
  *rr++ = w67;
  /* #564: @76 = (@13*@70) */
  for (i=0, rr=w76, cs=w70; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #565: @70 = (@6*@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #566: @76 = (@76-@70) */
  for (i=0, rr=w76, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #567: @54 = @76[1:4] */
  for (rr=w54, ss=w76+1; ss!=w76+4; ss+=1) *rr++ = *ss;
  /* #568: @63 = dot(@44, @54) */
  w63 = casadi_dot(3, w44, w54);
  /* #569: @63 = (@63/@15) */
  w63 /= w15;
  /* #570: @25 = (@63/@3) */
  w25  = (w63/w3);
  /* #571: @21 = (@65*@63) */
  w21  = (w65*w63);
  /* #572: @67 = @76[0] */
  for (rr=(&w67), ss=w76+0; ss!=w76+1; ss+=1) *rr++ = *ss;
  /* #573: @20 = (@61*@67) */
  w20  = (w61*w67);
  /* #574: @21 = (@21+@20) */
  w21 += w20;
  /* #575: @20 = (@30*@21) */
  w20  = (w30*w21);
  /* #576: @25 = (@25-@20) */
  w25 -= w20;
  /* #577: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #578: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #579: @37 = (2.*@54) */
  for (i=0, rr=w37, cs=w54; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #580: @35 = (@12*@37) */
  for (i=0, rr=w35, cs=w37; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #581: @20 = (@16*@63) */
  w20  = (w16*w63);
  /* #582: @26 = (@29*@67) */
  w26  = (w29*w67);
  /* #583: @20 = (@20-@26) */
  w20 -= w26;
  /* #584: @33 = (@45*@20) */
  for (i=0, rr=w33, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #585: @35 = (@35+@33) */
  for (i=0, rr=w35, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #586: @35 = (@35/@15) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w15;
  /* #587: @33 = (@46*@63) */
  for (i=0, rr=w33, cr=w46; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #588: @35 = (@35-@33) */
  for (i=0, rr=w35, cs=w33; i<3; ++i) (*rr++) -= (*cs++);
  /* #589: @33 = @35' */
  casadi_copy(w35, 3, w33);
  /* #590: @1 = mac(@33,@48,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #591: @1 = @1' */
  /* #592: @33 = zeros(1x3) */
  casadi_clear(w33, 3);
  /* #593: @78 = @35' */
  casadi_copy(w35, 3, w78);
  /* #594: @33 = mac(@78,@52,@33) */
  for (i=0, rr=w33; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w78+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #595: @33 = @33' */
  /* #596: @1 = (@1+@33) */
  for (i=0, rr=w1, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #597: @33 = (@1/@15) */
  for (i=0, rr=w33, cr=w1; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #598: @78 = (@55*@63) */
  for (i=0, rr=w78, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #599: @33 = (@33-@78) */
  for (i=0, rr=w33, cs=w78; i<3; ++i) (*rr++) -= (*cs++);
  /* #600: @26 = dot(@45, @33) */
  w26 = casadi_dot(3, w45, w33);
  /* #601: @60 = dot(@37, @47) */
  w60 = casadi_dot(3, w37, w47);
  /* #602: @26 = (@26+@60) */
  w26 += w60;
  /* #603: @60 = (@5*@26) */
  w60  = (w5*w26);
  /* #604: @25 = (@25+@60) */
  w25 += w60;
  /* #605: @25 = (-@25) */
  w25 = (- w25 );
  /* #606: (@75[0] += @25) */
  for (rr=w75+0, ss=(&w25); rr!=w75+1; rr+=1) *rr += *ss++;
  /* #607: @25 = dot(@53, @1) */
  w25 = casadi_dot(3, w53, w1);
  /* #608: @35 = (@35/@15) */
  for (i=0, rr=w35; i<3; ++i) (*rr++) /= w15;
  /* #609: @1 = (@51*@63) */
  for (i=0, rr=w1, cr=w51; i<3; ++i) (*rr++)  = ((*cr++)*w63);
  /* #610: @35 = (@35-@1) */
  for (i=0, rr=w35, cs=w1; i<3; ++i) (*rr++) -= (*cs++);
  /* #611: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #612: @60 = dot(@35, @38) */
  w60 = casadi_dot(3, w35, w38);
  /* #613: @25 = (@25+@60) */
  w25 += w60;
  /* #614: @67 = (@67/@3) */
  w67 /= w3;
  /* #615: @21 = (@19*@21) */
  w21  = (w19*w21);
  /* #616: @67 = (@67-@21) */
  w67 -= w21;
  /* #617: @67 = (@4*@67) */
  w67  = (w4*w67);
  /* #618: @26 = (@17*@26) */
  w26  = (w17*w26);
  /* #619: @67 = (@67+@26) */
  w67 += w26;
  /* #620: @25 = (@25+@67) */
  w25 += w67;
  /* #621: @25 = (@25/@15) */
  w25 /= w15;
  /* #622: @63 = (@62*@63) */
  w63  = (w62*w63);
  /* #623: @25 = (@25-@63) */
  w25 -= w63;
  /* #624: @35 = (@44*@25) */
  for (i=0, rr=w35, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #625: @54 = (@14*@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #626: @35 = (@35+@54) */
  for (i=0, rr=w35, cs=w54; i<3; ++i) (*rr++) += (*cs++);
  /* #627: @54 = (@47*@20) */
  for (i=0, rr=w54, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w20);
  /* #628: @33 = (@12*@33) */
  for (i=0, rr=w33, cs=w33; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #629: @54 = (@54+@33) */
  for (i=0, rr=w54, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #630: @54 = (2.*@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #631: @35 = (@35+@54) */
  for (i=0, rr=w35, cs=w54; i<3; ++i) (*rr++) += (*cs++);
  /* #632: (@75[1:4] += @35) */
  for (rr=w75+1, ss=w35; rr!=w75+4; rr+=1) *rr += *ss++;
  /* #633: @76 = (@0*@75) */
  for (i=0, rr=w76, cs=w75; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #634: @75 = (@18*@75) */
  for (i=0, rr=w75, cs=w75; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #635: @76 = (@76-@75) */
  for (i=0, rr=w76, cs=w75; i<4; ++i) (*rr++) -= (*cs++);
  /* #636: {@20, @25, @63, @67} = vertsplit(@76) */
  w20 = w76[0];
  w25 = w76[1];
  w63 = w76[2];
  w67 = w76[3];
  /* #637: @26 = (@7*@67) */
  w26  = (w7*w67);
  /* #638: @21 = (@8*@63) */
  w21  = (w8*w63);
  /* #639: @26 = (@26+@21) */
  w26 += w21;
  /* #640: @21 = (@9*@25) */
  w21  = (w9*w25);
  /* #641: @26 = (@26-@21) */
  w26 -= w21;
  /* #642: @21 = (@10*@20) */
  w21  = (w10*w20);
  /* #643: @26 = (@26-@21) */
  w26 -= w21;
  /* #644: (@50[3] += @26) */
  for (rr=w50+3, ss=(&w26); rr!=w50+4; rr+=1) *rr += *ss++;
  /* #645: @26 = (@7*@63) */
  w26  = (w7*w63);
  /* #646: @21 = (@8*@67) */
  w21  = (w8*w67);
  /* #647: @26 = (@26-@21) */
  w26 -= w21;
  /* #648: @21 = (@10*@25) */
  w21  = (w10*w25);
  /* #649: @26 = (@26+@21) */
  w26 += w21;
  /* #650: @21 = (@9*@20) */
  w21  = (w9*w20);
  /* #651: @26 = (@26-@21) */
  w26 -= w21;
  /* #652: (@50[2] += @26) */
  for (rr=w50+2, ss=(&w26); rr!=w50+3; rr+=1) *rr += *ss++;
  /* #653: @26 = (@9*@67) */
  w26  = (w9*w67);
  /* #654: @21 = (@10*@63) */
  w21  = (w10*w63);
  /* #655: @26 = (@26-@21) */
  w26 -= w21;
  /* #656: @21 = (@7*@25) */
  w21  = (w7*w25);
  /* #657: @26 = (@26+@21) */
  w26 += w21;
  /* #658: @21 = (@8*@20) */
  w21  = (w8*w20);
  /* #659: @26 = (@26-@21) */
  w26 -= w21;
  /* #660: (@50[1] += @26) */
  for (rr=w50+1, ss=(&w26); rr!=w50+2; rr+=1) *rr += *ss++;
  /* #661: @67 = (@10*@67) */
  w67  = (w10*w67);
  /* #662: @63 = (@9*@63) */
  w63  = (w9*w63);
  /* #663: @67 = (@67+@63) */
  w67 += w63;
  /* #664: @25 = (@8*@25) */
  w25  = (w8*w25);
  /* #665: @67 = (@67+@25) */
  w67 += w25;
  /* #666: @20 = (@7*@20) */
  w20  = (w7*w20);
  /* #667: @67 = (@67+@20) */
  w67 += w20;
  /* #668: (@50[0] += @67) */
  for (rr=w50+0, ss=(&w67); rr!=w50+1; rr+=1) *rr += *ss++;
  /* #669: @67 = dot(@42, @50) */
  w67 = casadi_dot(4, w42, w50);
  /* #670: @77 = (@77/@11) */
  for (i=0, rr=w77; i<4; ++i) (*rr++) /= w11;
  /* #671: @76 = (@43*@68) */
  for (i=0, rr=w76, cr=w43; i<4; ++i) (*rr++)  = ((*cr++)*w68);
  /* #672: @77 = (@77-@76) */
  for (i=0, rr=w77, cs=w76; i<4; ++i) (*rr++) -= (*cs++);
  /* #673: @77 = (-@77) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) *rr++ = (- *cs++ );
  /* #674: @20 = dot(@77, @49) */
  w20 = casadi_dot(4, w77, w49);
  /* #675: @67 = (@67+@20) */
  w67 += w20;
  /* #676: @67 = (@67/@11) */
  w67 /= w11;
  /* #677: @20 = (@28*@68) */
  w20  = (w28*w68);
  /* #678: @67 = (@67-@20) */
  w67 -= w20;
  /* #679: @77 = (@41*@67) */
  for (i=0, rr=w77, cr=w41; i<4; ++i) (*rr++)  = ((*cr++)*w67);
  /* #680: @27 = (@22*@27) */
  w27  = (w22*w27);
  /* #681: @76 = dense(@27) */
  casadi_densify((&w27), casadi_s7, w76, 0);
  /* #682: @77 = (@77+@76) */
  for (i=0, rr=w77, cs=w76; i<4; ++i) (*rr++) += (*cs++);
  /* #683: (@34[4:8] += @77) */
  for (rr=w34+4, ss=w77; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #684: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #685: @27 = @66[0] */
  for (rr=(&w27), ss=(&w66)+0; ss!=(&w66)+1; ss+=1) *rr++ = *ss;
  /* #686: @27 = (-@27) */
  w27 = (- w27 );
  /* #687: @66 = @27' */
  casadi_copy((&w27), 1, (&w66));
  /* #688: @66 = (@31*@66) */
  w66  = (w31*w66);
  /* #689: @35 = mac(@66,@39,@35) */
  casadi_mtimes((&w66), casadi_s8, w39, casadi_s2, w35, casadi_s1, w, 0);
  /* #690: @35 = @35' */
  /* #691: @54 = zeros(1x3) */
  casadi_clear(w54, 3);
  /* #692: @27 = @27' */
  /* #693: @54 = mac(@27,@57,@54) */
  casadi_mtimes((&w27), casadi_s8, w57, casadi_s2, w54, casadi_s1, w, 0);
  /* #694: @54 = (@31*@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #695: @54 = @54' */
  /* #696: @35 = (@35+@54) */
  for (i=0, rr=w35, cs=w54; i<3; ++i) (*rr++) += (*cs++);
  /* #697: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #698: (@34[11:14] += @35) */
  for (rr=w34+11, ss=w35; rr!=w34+14; rr+=1) *rr += *ss++;
  /* #699: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #700: @27 = @64[0] */
  for (rr=(&w27), ss=(&w64)+0; ss!=(&w64)+1; ss+=1) *rr++ = *ss;
  /* #701: @27 = (-@27) */
  w27 = (- w27 );
  /* #702: @64 = @27' */
  casadi_copy((&w27), 1, (&w64));
  /* #703: @64 = (@2*@64) */
  w64  = (w2*w64);
  /* #704: @35 = mac(@64,@36,@35) */
  casadi_mtimes((&w64), casadi_s8, w36, casadi_s2, w35, casadi_s1, w, 0);
  /* #705: @35 = @35' */
  /* #706: @54 = zeros(1x3) */
  casadi_clear(w54, 3);
  /* #707: @27 = @27' */
  /* #708: @54 = mac(@27,@58,@54) */
  casadi_mtimes((&w27), casadi_s8, w58, casadi_s2, w54, casadi_s1, w, 0);
  /* #709: @54 = (@2*@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #710: @54 = @54' */
  /* #711: @35 = (@35+@54) */
  for (i=0, rr=w35, cs=w54; i<3; ++i) (*rr++) += (*cs++);
  /* #712: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #713: (@34[:3] += @35) */
  for (rr=w34+0, ss=w35; rr!=w34+3; rr+=1) *rr += *ss++;
  /* #714: {@27, @64, @66, @67, @20, @25, @63, @26, @21, @60, @23, @24, @79, @80, @81, @82, @83, @84, @85, @86, @89} = vertsplit(@34) */
  w27 = w34[0];
  w64 = w34[1];
  w66 = w34[2];
  w67 = w34[3];
  w20 = w34[4];
  w25 = w34[5];
  w63 = w34[6];
  w26 = w34[7];
  w21 = w34[8];
  w60 = w34[9];
  w23 = w34[10];
  w24 = w34[11];
  w79 = w34[12];
  w80 = w34[13];
  w81 = w34[14];
  w82 = w34[15];
  w83 = w34[16];
  w84 = w34[17];
  w85 = w34[18];
  w86 = w34[19];
  w89 = w34[20];
  /* #715: @50 = (@50/@11) */
  for (i=0, rr=w50; i<4; ++i) (*rr++) /= w11;
  /* #716: @77 = (@56*@68) */
  for (i=0, rr=w77, cr=w56; i<4; ++i) (*rr++)  = ((*cr++)*w68);
  /* #717: @50 = (@50-@77) */
  for (i=0, rr=w50, cs=w77; i<4; ++i) (*rr++) -= (*cs++);
  /* #718: {@68, @88, @87, @59} = vertsplit(@50) */
  w68 = w50[0];
  w88 = w50[1];
  w87 = w50[2];
  w59 = w50[3];
  /* #719: @68 = (@68+@20) */
  w68 += w20;
  /* #720: @25 = (@25-@88) */
  w25 -= w88;
  /* #721: @63 = (@63-@87) */
  w63 -= w87;
  /* #722: @26 = (@26-@59) */
  w26 -= w59;
  /* #723: @34 = vertcat(@27, @64, @66, @67, @68, @25, @63, @26, @21, @60, @23, @24, @79, @80, @81, @82, @83, @84, @85, @86, @89) */
  rr=w34;
  *rr++ = w27;
  *rr++ = w64;
  *rr++ = w66;
  *rr++ = w67;
  *rr++ = w68;
  *rr++ = w25;
  *rr++ = w63;
  *rr++ = w26;
  *rr++ = w21;
  *rr++ = w60;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w79;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w85;
  *rr++ = w86;
  *rr++ = w89;
  /* #724: @90 = @34[0, 1, 2, 4, 5, 6, 7, 11, 12, 13] */
  for (cii=casadi_s4, rr=w90, ss=w34; cii!=casadi_s4+10; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #725: (@69[3, 4, 5, 13, 14, 15, 16, 28, 29, 30] = @90) */
  for (cii=casadi_s9, rr=w69, ss=w90; cii!=casadi_s9+10; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #726: @90 = @34[0, 1, 2, 4, 5, 6, 7, 11, 12, 13] */
  for (cii=casadi_s4, rr=w90, ss=w34; cii!=casadi_s4+10; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #727: (@69[1, 4, 7, 10, 14, 18, 22, 26, 29, 32] = @90) */
  for (cii=casadi_s10, rr=w69, ss=w90; cii!=casadi_s10+10; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #728: @34 = zeros(21x1) */
  casadi_clear(w34, 21);
  /* #729: @50 = zeros(4x1) */
  casadi_clear(w50, 4);
  /* #730: @77 = zeros(4x1) */
  casadi_clear(w77, 4);
  /* #731: @72 = 00 */
  /* #732: @73 = 00 */
  /* #733: @35 = ones(21x1,3nz) */
  casadi_fill(w35, 3, 1.);
  /* #734: {NULL, NULL, @27, NULL, NULL, NULL, @64, NULL, NULL, NULL, NULL, NULL, NULL, @66, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@35) */
  w27 = w35[0];
  w64 = w35[1];
  w66 = w35[2];
  /* #735: @67 = (-@64) */
  w67 = (- w64 );
  /* #736: @74 = 00 */
  /* #737: @68 = vertcat(@72, @73, @67, @74) */
  rr=(&w68);
  *rr++ = w67;
  /* #738: @68 = (@68/@11) */
  w68 /= w11;
  /* #739: @76 = dense(@68) */
  casadi_densify((&w68), casadi_s11, w76, 0);
  /* #740: @68 = project(@41) */
  casadi_sparsify(w41, (&w68), casadi_s11, 0);
  /* #741: @67 = @64[0] */
  for (rr=(&w67), ss=(&w64)+0; ss!=(&w64)+1; ss+=1) *rr++ = *ss;
  /* #742: @64 = dot(@68, @67) */
  w64 = casadi_dot(1, (&w68), (&w67));
  /* #743: @64 = (@64/@11) */
  w64 /= w11;
  /* #744: @75 = (@40*@64) */
  for (i=0, rr=w75, cr=w40; i<4; ++i) (*rr++)  = ((*cr++)*w64);
  /* #745: @76 = (@76-@75) */
  for (i=0, rr=w76, cs=w75; i<4; ++i) (*rr++) -= (*cs++);
  /* #746: @68 = @76[0] */
  for (rr=(&w68), ss=w76+0; ss!=w76+1; ss+=1) *rr++ = *ss;
  /* #747: @25 = (@7*@68) */
  w25  = (w7*w68);
  /* #748: @63 = @76[1] */
  for (rr=(&w63), ss=w76+1; ss!=w76+2; ss+=1) *rr++ = *ss;
  /* #749: @26 = (@8*@63) */
  w26  = (w8*w63);
  /* #750: @25 = (@25-@26) */
  w25 -= w26;
  /* #751: @26 = @76[2] */
  for (rr=(&w26), ss=w76+2; ss!=w76+3; ss+=1) *rr++ = *ss;
  /* #752: @21 = (@9*@26) */
  w21  = (w9*w26);
  /* #753: @25 = (@25-@21) */
  w25 -= w21;
  /* #754: @21 = @76[3] */
  for (rr=(&w21), ss=w76+3; ss!=w76+4; ss+=1) *rr++ = *ss;
  /* #755: @60 = (@10*@21) */
  w60  = (w10*w21);
  /* #756: @25 = (@25-@60) */
  w25 -= w60;
  /* #757: @60 = (@8*@68) */
  w60  = (w8*w68);
  /* #758: @23 = (@7*@63) */
  w23  = (w7*w63);
  /* #759: @60 = (@60+@23) */
  w60 += w23;
  /* #760: @23 = (@10*@26) */
  w23  = (w10*w26);
  /* #761: @60 = (@60+@23) */
  w60 += w23;
  /* #762: @23 = (@9*@21) */
  w23  = (w9*w21);
  /* #763: @60 = (@60-@23) */
  w60 -= w23;
  /* #764: @23 = (@9*@68) */
  w23  = (w9*w68);
  /* #765: @24 = (@10*@63) */
  w24  = (w10*w63);
  /* #766: @23 = (@23-@24) */
  w23 -= w24;
  /* #767: @24 = (@7*@26) */
  w24  = (w7*w26);
  /* #768: @23 = (@23+@24) */
  w23 += w24;
  /* #769: @24 = (@8*@21) */
  w24  = (w8*w21);
  /* #770: @23 = (@23+@24) */
  w23 += w24;
  /* #771: @68 = (@10*@68) */
  w68  = (w10*w68);
  /* #772: @63 = (@9*@63) */
  w63  = (w9*w63);
  /* #773: @68 = (@68+@63) */
  w68 += w63;
  /* #774: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #775: @68 = (@68-@26) */
  w68 -= w26;
  /* #776: @21 = (@7*@21) */
  w21  = (w7*w21);
  /* #777: @68 = (@68+@21) */
  w68 += w21;
  /* #778: @75 = vertcat(@25, @60, @23, @68) */
  rr=w75;
  *rr++ = w25;
  *rr++ = w60;
  *rr++ = w23;
  *rr++ = w68;
  /* #779: @70 = (@13*@75) */
  for (i=0, rr=w70, cs=w75; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #780: @75 = (@6*@75) */
  for (i=0, rr=w75, cs=w75; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #781: @70 = (@70-@75) */
  for (i=0, rr=w70, cs=w75; i<4; ++i) (*rr++) -= (*cs++);
  /* #782: @35 = @70[1:4] */
  for (rr=w35, ss=w70+1; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #783: @25 = dot(@44, @35) */
  w25 = casadi_dot(3, w44, w35);
  /* #784: @25 = (@25/@15) */
  w25 /= w15;
  /* #785: @60 = (@25/@3) */
  w60  = (w25/w3);
  /* #786: @23 = (@65*@25) */
  w23  = (w65*w25);
  /* #787: @68 = @70[0] */
  for (rr=(&w68), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #788: @21 = (@61*@68) */
  w21  = (w61*w68);
  /* #789: @23 = (@23+@21) */
  w23 += w21;
  /* #790: @21 = (@30*@23) */
  w21  = (w30*w23);
  /* #791: @60 = (@60-@21) */
  w60 -= w21;
  /* #792: @60 = (@4*@60) */
  w60  = (w4*w60);
  /* #793: @54 = zeros(1x3) */
  casadi_clear(w54, 3);
  /* #794: @33 = (2.*@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #795: @1 = (@12*@33) */
  for (i=0, rr=w1, cs=w33; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #796: @21 = (@16*@25) */
  w21  = (w16*w25);
  /* #797: @26 = (@29*@68) */
  w26  = (w29*w68);
  /* #798: @21 = (@21-@26) */
  w21 -= w26;
  /* #799: @37 = (@45*@21) */
  for (i=0, rr=w37, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #800: @1 = (@1+@37) */
  for (i=0, rr=w1, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #801: @1 = (@1/@15) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w15;
  /* #802: @37 = (@46*@25) */
  for (i=0, rr=w37, cr=w46; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #803: @1 = (@1-@37) */
  for (i=0, rr=w1, cs=w37; i<3; ++i) (*rr++) -= (*cs++);
  /* #804: @37 = @1' */
  casadi_copy(w1, 3, w37);
  /* #805: @54 = mac(@37,@48,@54) */
  for (i=0, rr=w54; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #806: @54 = @54' */
  /* #807: @37 = zeros(1x3) */
  casadi_clear(w37, 3);
  /* #808: @78 = @1' */
  casadi_copy(w1, 3, w78);
  /* #809: @37 = mac(@78,@52,@37) */
  for (i=0, rr=w37; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w78+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #810: @37 = @37' */
  /* #811: @54 = (@54+@37) */
  for (i=0, rr=w54, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #812: @37 = (@54/@15) */
  for (i=0, rr=w37, cr=w54; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #813: @78 = (@55*@25) */
  for (i=0, rr=w78, cr=w55; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #814: @37 = (@37-@78) */
  for (i=0, rr=w37, cs=w78; i<3; ++i) (*rr++) -= (*cs++);
  /* #815: @26 = dot(@45, @37) */
  w26 = casadi_dot(3, w45, w37);
  /* #816: @63 = dot(@33, @47) */
  w63 = casadi_dot(3, w33, w47);
  /* #817: @26 = (@26+@63) */
  w26 += w63;
  /* #818: @63 = (@5*@26) */
  w63  = (w5*w26);
  /* #819: @60 = (@60+@63) */
  w60 += w63;
  /* #820: @60 = (-@60) */
  w60 = (- w60 );
  /* #821: (@77[0] += @60) */
  for (rr=w77+0, ss=(&w60); rr!=w77+1; rr+=1) *rr += *ss++;
  /* #822: @60 = dot(@53, @54) */
  w60 = casadi_dot(3, w53, w54);
  /* #823: @1 = (@1/@15) */
  for (i=0, rr=w1; i<3; ++i) (*rr++) /= w15;
  /* #824: @54 = (@51*@25) */
  for (i=0, rr=w54, cr=w51; i<3; ++i) (*rr++)  = ((*cr++)*w25);
  /* #825: @1 = (@1-@54) */
  for (i=0, rr=w1, cs=w54; i<3; ++i) (*rr++) -= (*cs++);
  /* #826: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #827: @63 = dot(@1, @38) */
  w63 = casadi_dot(3, w1, w38);
  /* #828: @60 = (@60+@63) */
  w60 += w63;
  /* #829: @68 = (@68/@3) */
  w68 /= w3;
  /* #830: @23 = (@19*@23) */
  w23  = (w19*w23);
  /* #831: @68 = (@68-@23) */
  w68 -= w23;
  /* #832: @68 = (@4*@68) */
  w68  = (w4*w68);
  /* #833: @26 = (@17*@26) */
  w26  = (w17*w26);
  /* #834: @68 = (@68+@26) */
  w68 += w26;
  /* #835: @60 = (@60+@68) */
  w60 += w68;
  /* #836: @60 = (@60/@15) */
  w60 /= w15;
  /* #837: @25 = (@62*@25) */
  w25  = (w62*w25);
  /* #838: @60 = (@60-@25) */
  w60 -= w25;
  /* #839: @1 = (@44*@60) */
  for (i=0, rr=w1, cr=w44; i<3; ++i) (*rr++)  = ((*cr++)*w60);
  /* #840: @35 = (@14*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #841: @1 = (@1+@35) */
  for (i=0, rr=w1, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #842: @35 = (@47*@21) */
  for (i=0, rr=w35, cr=w47; i<3; ++i) (*rr++)  = ((*cr++)*w21);
  /* #843: @37 = (@12*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #844: @35 = (@35+@37) */
  for (i=0, rr=w35, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #845: @35 = (2.*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #846: @1 = (@1+@35) */
  for (i=0, rr=w1, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #847: (@77[1:4] += @1) */
  for (rr=w77+1, ss=w1; rr!=w77+4; rr+=1) *rr += *ss++;
  /* #848: @70 = (@0*@77) */
  for (i=0, rr=w70, cs=w77; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #849: @77 = (@18*@77) */
  for (i=0, rr=w77, cs=w77; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #850: @70 = (@70-@77) */
  for (i=0, rr=w70, cs=w77; i<4; ++i) (*rr++) -= (*cs++);
  /* #851: {@21, @60, @25, @68} = vertsplit(@70) */
  w21 = w70[0];
  w60 = w70[1];
  w25 = w70[2];
  w68 = w70[3];
  /* #852: @26 = (@7*@68) */
  w26  = (w7*w68);
  /* #853: @23 = (@8*@25) */
  w23  = (w8*w25);
  /* #854: @26 = (@26+@23) */
  w26 += w23;
  /* #855: @23 = (@9*@60) */
  w23  = (w9*w60);
  /* #856: @26 = (@26-@23) */
  w26 -= w23;
  /* #857: @23 = (@10*@21) */
  w23  = (w10*w21);
  /* #858: @26 = (@26-@23) */
  w26 -= w23;
  /* #859: (@50[3] += @26) */
  for (rr=w50+3, ss=(&w26); rr!=w50+4; rr+=1) *rr += *ss++;
  /* #860: @26 = (@7*@25) */
  w26  = (w7*w25);
  /* #861: @23 = (@8*@68) */
  w23  = (w8*w68);
  /* #862: @26 = (@26-@23) */
  w26 -= w23;
  /* #863: @23 = (@10*@60) */
  w23  = (w10*w60);
  /* #864: @26 = (@26+@23) */
  w26 += w23;
  /* #865: @23 = (@9*@21) */
  w23  = (w9*w21);
  /* #866: @26 = (@26-@23) */
  w26 -= w23;
  /* #867: (@50[2] += @26) */
  for (rr=w50+2, ss=(&w26); rr!=w50+3; rr+=1) *rr += *ss++;
  /* #868: @26 = (@9*@68) */
  w26  = (w9*w68);
  /* #869: @23 = (@10*@25) */
  w23  = (w10*w25);
  /* #870: @26 = (@26-@23) */
  w26 -= w23;
  /* #871: @23 = (@7*@60) */
  w23  = (w7*w60);
  /* #872: @26 = (@26+@23) */
  w26 += w23;
  /* #873: @23 = (@8*@21) */
  w23  = (w8*w21);
  /* #874: @26 = (@26-@23) */
  w26 -= w23;
  /* #875: (@50[1] += @26) */
  for (rr=w50+1, ss=(&w26); rr!=w50+2; rr+=1) *rr += *ss++;
  /* #876: @68 = (@10*@68) */
  w68  = (w10*w68);
  /* #877: @25 = (@9*@25) */
  w25  = (w9*w25);
  /* #878: @68 = (@68+@25) */
  w68 += w25;
  /* #879: @60 = (@8*@60) */
  w60  = (w8*w60);
  /* #880: @68 = (@68+@60) */
  w68 += w60;
  /* #881: @21 = (@7*@21) */
  w21  = (w7*w21);
  /* #882: @68 = (@68+@21) */
  w68 += w21;
  /* #883: (@50[0] += @68) */
  for (rr=w50+0, ss=(&w68); rr!=w50+1; rr+=1) *rr += *ss++;
  /* #884: @68 = dot(@42, @50) */
  w68 = casadi_dot(4, w42, w50);
  /* #885: @76 = (@76/@11) */
  for (i=0, rr=w76; i<4; ++i) (*rr++) /= w11;
  /* #886: @70 = (@43*@64) */
  for (i=0, rr=w70, cr=w43; i<4; ++i) (*rr++)  = ((*cr++)*w64);
  /* #887: @76 = (@76-@70) */
  for (i=0, rr=w76, cs=w70; i<4; ++i) (*rr++) -= (*cs++);
  /* #888: @76 = (-@76) */
  for (i=0, rr=w76, cs=w76; i<4; ++i) *rr++ = (- *cs++ );
  /* #889: @21 = dot(@76, @49) */
  w21 = casadi_dot(4, w76, w49);
  /* #890: @68 = (@68+@21) */
  w68 += w21;
  /* #891: @68 = (@68/@11) */
  w68 /= w11;
  /* #892: @21 = (@28*@64) */
  w21  = (w28*w64);
  /* #893: @68 = (@68-@21) */
  w68 -= w21;
  /* #894: @76 = (@41*@68) */
  for (i=0, rr=w76, cr=w41; i<4; ++i) (*rr++)  = ((*cr++)*w68);
  /* #895: @67 = (@22*@67) */
  w67  = (w22*w67);
  /* #896: @70 = dense(@67) */
  casadi_densify((&w67), casadi_s11, w70, 0);
  /* #897: @76 = (@76+@70) */
  for (i=0, rr=w76, cs=w70; i<4; ++i) (*rr++) += (*cs++);
  /* #898: (@34[4:8] += @76) */
  for (rr=w34+4, ss=w76; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #899: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #900: @67 = @66[0] */
  for (rr=(&w67), ss=(&w66)+0; ss!=(&w66)+1; ss+=1) *rr++ = *ss;
  /* #901: @67 = (-@67) */
  w67 = (- w67 );
  /* #902: @66 = @67' */
  casadi_copy((&w67), 1, (&w66));
  /* #903: @66 = (@31*@66) */
  w66  = (w31*w66);
  /* #904: @1 = mac(@66,@39,@1) */
  casadi_mtimes((&w66), casadi_s12, w39, casadi_s2, w1, casadi_s1, w, 0);
  /* #905: @1 = @1' */
  /* #906: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #907: @67 = @67' */
  /* #908: @35 = mac(@67,@57,@35) */
  casadi_mtimes((&w67), casadi_s12, w57, casadi_s2, w35, casadi_s1, w, 0);
  /* #909: @35 = (@31*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #910: @35 = @35' */
  /* #911: @1 = (@1+@35) */
  for (i=0, rr=w1, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #912: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #913: (@34[11:14] += @1) */
  for (rr=w34+11, ss=w1; rr!=w34+14; rr+=1) *rr += *ss++;
  /* #914: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #915: @31 = @27[0] */
  for (rr=(&w31), ss=(&w27)+0; ss!=(&w27)+1; ss+=1) *rr++ = *ss;
  /* #916: @31 = (-@31) */
  w31 = (- w31 );
  /* #917: @27 = @31' */
  casadi_copy((&w31), 1, (&w27));
  /* #918: @27 = (@2*@27) */
  w27  = (w2*w27);
  /* #919: @1 = mac(@27,@36,@1) */
  casadi_mtimes((&w27), casadi_s12, w36, casadi_s2, w1, casadi_s1, w, 0);
  /* #920: @1 = @1' */
  /* #921: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #922: @31 = @31' */
  /* #923: @35 = mac(@31,@58,@35) */
  casadi_mtimes((&w31), casadi_s12, w58, casadi_s2, w35, casadi_s1, w, 0);
  /* #924: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #925: @35 = @35' */
  /* #926: @1 = (@1+@35) */
  for (i=0, rr=w1, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #927: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #928: (@34[:3] += @1) */
  for (rr=w34+0, ss=w1; rr!=w34+3; rr+=1) *rr += *ss++;
  /* #929: {@2, @31, @27, @67, @66, @68, @21, @60, @25, @26, @23, @63, @24, @79, @80, @81, @82, @83, @84, @85, @86} = vertsplit(@34) */
  w2 = w34[0];
  w31 = w34[1];
  w27 = w34[2];
  w67 = w34[3];
  w66 = w34[4];
  w68 = w34[5];
  w21 = w34[6];
  w60 = w34[7];
  w25 = w34[8];
  w26 = w34[9];
  w23 = w34[10];
  w63 = w34[11];
  w24 = w34[12];
  w79 = w34[13];
  w80 = w34[14];
  w81 = w34[15];
  w82 = w34[16];
  w83 = w34[17];
  w84 = w34[18];
  w85 = w34[19];
  w86 = w34[20];
  /* #930: @50 = (@50/@11) */
  for (i=0, rr=w50; i<4; ++i) (*rr++) /= w11;
  /* #931: @76 = (@56*@64) */
  for (i=0, rr=w76, cr=w56; i<4; ++i) (*rr++)  = ((*cr++)*w64);
  /* #932: @50 = (@50-@76) */
  for (i=0, rr=w50, cs=w76; i<4; ++i) (*rr++) -= (*cs++);
  /* #933: {@64, @89, @59, @87} = vertsplit(@50) */
  w64 = w50[0];
  w89 = w50[1];
  w59 = w50[2];
  w87 = w50[3];
  /* #934: @64 = (@64+@66) */
  w64 += w66;
  /* #935: @68 = (@68-@89) */
  w68 -= w89;
  /* #936: @21 = (@21-@59) */
  w21 -= w59;
  /* #937: @60 = (@60-@87) */
  w60 -= w87;
  /* #938: @34 = vertcat(@2, @31, @27, @67, @64, @68, @21, @60, @25, @26, @23, @63, @24, @79, @80, @81, @82, @83, @84, @85, @86) */
  rr=w34;
  *rr++ = w2;
  *rr++ = w31;
  *rr++ = w27;
  *rr++ = w67;
  *rr++ = w64;
  *rr++ = w68;
  *rr++ = w21;
  *rr++ = w60;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w23;
  *rr++ = w63;
  *rr++ = w24;
  *rr++ = w79;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w84;
  *rr++ = w85;
  *rr++ = w86;
  /* #939: @90 = @34[0, 1, 2, 4, 5, 6, 7, 11, 12, 13] */
  for (cii=casadi_s4, rr=w90, ss=w34; cii!=casadi_s4+10; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #940: (@69[6, 7, 8, 17, 18, 19, 20, 31, 32, 33] = @90) */
  for (cii=casadi_s13, rr=w69, ss=w90; cii!=casadi_s13+10; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #941: @90 = @34[0, 1, 2, 4, 5, 6, 7, 11, 12, 13] */
  for (cii=casadi_s4, rr=w90, ss=w34; cii!=casadi_s4+10; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #942: (@69[2, 5, 8, 11, 15, 19, 23, 27, 30, 33] = @90) */
  for (cii=casadi_s14, rr=w69, ss=w90; cii!=casadi_s14+10; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #943: @34 = zeros(21x1) */
  casadi_clear(w34, 21);
  /* #944: @50 = zeros(4x1) */
  casadi_clear(w50, 4);
  /* #945: @76 = zeros(4x1) */
  casadi_clear(w76, 4);
  /* #946: @72 = 00 */
  /* #947: @73 = 00 */
  /* #948: @74 = 00 */
  /* #949: @2 = ones(21x1,1nz) */
  w2 = 1.;
  /* #950: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @31, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@2) */
  w31 = w2;
  /* #951: @2 = (-@31) */
  w2 = (- w31 );
  /* #952: @27 = vertcat(@72, @73, @74, @2) */
  rr=(&w27);
  *rr++ = w2;
  /* #953: @27 = (@27/@11) */
  w27 /= w11;
  /* #954: @70 = dense(@27) */
  casadi_densify((&w27), casadi_s15, w70, 0);
  /* #955: @27 = project(@41) */
  casadi_sparsify(w41, (&w27), casadi_s15, 0);
  /* #956: @2 = @31[0] */
  for (rr=(&w2), ss=(&w31)+0; ss!=(&w31)+1; ss+=1) *rr++ = *ss;
  /* #957: @31 = dot(@27, @2) */
  w31 = casadi_dot(1, (&w27), (&w2));
  /* #958: @31 = (@31/@11) */
  w31 /= w11;
  /* #959: @40 = (@40*@31) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) *= w31;
  /* #960: @70 = (@70-@40) */
  for (i=0, rr=w70, cs=w40; i<4; ++i) (*rr++) -= (*cs++);
  /* #961: @27 = @70[0] */
  for (rr=(&w27), ss=w70+0; ss!=w70+1; ss+=1) *rr++ = *ss;
  /* #962: @67 = (@7*@27) */
  w67  = (w7*w27);
  /* #963: @64 = @70[1] */
  for (rr=(&w64), ss=w70+1; ss!=w70+2; ss+=1) *rr++ = *ss;
  /* #964: @68 = (@8*@64) */
  w68  = (w8*w64);
  /* #965: @67 = (@67-@68) */
  w67 -= w68;
  /* #966: @68 = @70[2] */
  for (rr=(&w68), ss=w70+2; ss!=w70+3; ss+=1) *rr++ = *ss;
  /* #967: @21 = (@9*@68) */
  w21  = (w9*w68);
  /* #968: @67 = (@67-@21) */
  w67 -= w21;
  /* #969: @21 = @70[3] */
  for (rr=(&w21), ss=w70+3; ss!=w70+4; ss+=1) *rr++ = *ss;
  /* #970: @60 = (@10*@21) */
  w60  = (w10*w21);
  /* #971: @67 = (@67-@60) */
  w67 -= w60;
  /* #972: @60 = (@8*@27) */
  w60  = (w8*w27);
  /* #973: @25 = (@7*@64) */
  w25  = (w7*w64);
  /* #974: @60 = (@60+@25) */
  w60 += w25;
  /* #975: @25 = (@10*@68) */
  w25  = (w10*w68);
  /* #976: @60 = (@60+@25) */
  w60 += w25;
  /* #977: @25 = (@9*@21) */
  w25  = (w9*w21);
  /* #978: @60 = (@60-@25) */
  w60 -= w25;
  /* #979: @25 = (@9*@27) */
  w25  = (w9*w27);
  /* #980: @26 = (@10*@64) */
  w26  = (w10*w64);
  /* #981: @25 = (@25-@26) */
  w25 -= w26;
  /* #982: @26 = (@7*@68) */
  w26  = (w7*w68);
  /* #983: @25 = (@25+@26) */
  w25 += w26;
  /* #984: @26 = (@8*@21) */
  w26  = (w8*w21);
  /* #985: @25 = (@25+@26) */
  w25 += w26;
  /* #986: @27 = (@10*@27) */
  w27  = (w10*w27);
  /* #987: @64 = (@9*@64) */
  w64  = (w9*w64);
  /* #988: @27 = (@27+@64) */
  w27 += w64;
  /* #989: @68 = (@8*@68) */
  w68  = (w8*w68);
  /* #990: @27 = (@27-@68) */
  w27 -= w68;
  /* #991: @21 = (@7*@21) */
  w21  = (w7*w21);
  /* #992: @27 = (@27+@21) */
  w27 += w21;
  /* #993: @40 = vertcat(@67, @60, @25, @27) */
  rr=w40;
  *rr++ = w67;
  *rr++ = w60;
  *rr++ = w25;
  *rr++ = w27;
  /* #994: @77 = (@13*@40) */
  for (i=0, rr=w77, cs=w40; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #995: @40 = (@6*@40) */
  for (i=0, rr=w40, cs=w40; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #996: @77 = (@77-@40) */
  for (i=0, rr=w77, cs=w40; i<4; ++i) (*rr++) -= (*cs++);
  /* #997: @1 = @77[1:4] */
  for (rr=w1, ss=w77+1; ss!=w77+4; ss+=1) *rr++ = *ss;
  /* #998: @6 = dot(@44, @1) */
  w6 = casadi_dot(3, w44, w1);
  /* #999: @6 = (@6/@15) */
  w6 /= w15;
  /* #1000: @13 = (@6/@3) */
  w13  = (w6/w3);
  /* #1001: @65 = (@65*@6) */
  w65 *= w6;
  /* #1002: @67 = @77[0] */
  for (rr=(&w67), ss=w77+0; ss!=w77+1; ss+=1) *rr++ = *ss;
  /* #1003: @61 = (@61*@67) */
  w61 *= w67;
  /* #1004: @65 = (@65+@61) */
  w65 += w61;
  /* #1005: @30 = (@30*@65) */
  w30 *= w65;
  /* #1006: @13 = (@13-@30) */
  w13 -= w30;
  /* #1007: @13 = (@4*@13) */
  w13  = (w4*w13);
  /* #1008: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #1009: @37 = (2.*@1) */
  for (i=0, rr=w37, cs=w1; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1010: @54 = (@12*@37) */
  for (i=0, rr=w54, cs=w37; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #1011: @16 = (@16*@6) */
  w16 *= w6;
  /* #1012: @29 = (@29*@67) */
  w29 *= w67;
  /* #1013: @16 = (@16-@29) */
  w16 -= w29;
  /* #1014: @33 = (@45*@16) */
  for (i=0, rr=w33, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w16);
  /* #1015: @54 = (@54+@33) */
  for (i=0, rr=w54, cs=w33; i<3; ++i) (*rr++) += (*cs++);
  /* #1016: @54 = (@54/@15) */
  for (i=0, rr=w54; i<3; ++i) (*rr++) /= w15;
  /* #1017: @46 = (@46*@6) */
  for (i=0, rr=w46; i<3; ++i) (*rr++) *= w6;
  /* #1018: @54 = (@54-@46) */
  for (i=0, rr=w54, cs=w46; i<3; ++i) (*rr++) -= (*cs++);
  /* #1019: @46 = @54' */
  casadi_copy(w54, 3, w46);
  /* #1020: @35 = mac(@46,@48,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w46+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1021: @35 = @35' */
  /* #1022: @46 = zeros(1x3) */
  casadi_clear(w46, 3);
  /* #1023: @33 = @54' */
  casadi_copy(w54, 3, w33);
  /* #1024: @46 = mac(@33,@52,@46) */
  for (i=0, rr=w46; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w52+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #1025: @46 = @46' */
  /* #1026: @35 = (@35+@46) */
  for (i=0, rr=w35, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #1027: @46 = (@35/@15) */
  for (i=0, rr=w46, cr=w35; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #1028: @55 = (@55*@6) */
  for (i=0, rr=w55; i<3; ++i) (*rr++) *= w6;
  /* #1029: @46 = (@46-@55) */
  for (i=0, rr=w46, cs=w55; i<3; ++i) (*rr++) -= (*cs++);
  /* #1030: @29 = dot(@45, @46) */
  w29 = casadi_dot(3, w45, w46);
  /* #1031: @30 = dot(@37, @47) */
  w30 = casadi_dot(3, w37, w47);
  /* #1032: @29 = (@29+@30) */
  w29 += w30;
  /* #1033: @5 = (@5*@29) */
  w5 *= w29;
  /* #1034: @13 = (@13+@5) */
  w13 += w5;
  /* #1035: @13 = (-@13) */
  w13 = (- w13 );
  /* #1036: (@76[0] += @13) */
  for (rr=w76+0, ss=(&w13); rr!=w76+1; rr+=1) *rr += *ss++;
  /* #1037: @13 = dot(@53, @35) */
  w13 = casadi_dot(3, w53, w35);
  /* #1038: @54 = (@54/@15) */
  for (i=0, rr=w54; i<3; ++i) (*rr++) /= w15;
  /* #1039: @51 = (@51*@6) */
  for (i=0, rr=w51; i<3; ++i) (*rr++) *= w6;
  /* #1040: @54 = (@54-@51) */
  for (i=0, rr=w54, cs=w51; i<3; ++i) (*rr++) -= (*cs++);
  /* #1041: @54 = (-@54) */
  for (i=0, rr=w54, cs=w54; i<3; ++i) *rr++ = (- *cs++ );
  /* #1042: @5 = dot(@54, @38) */
  w5 = casadi_dot(3, w54, w38);
  /* #1043: @13 = (@13+@5) */
  w13 += w5;
  /* #1044: @67 = (@67/@3) */
  w67 /= w3;
  /* #1045: @19 = (@19*@65) */
  w19 *= w65;
  /* #1046: @67 = (@67-@19) */
  w67 -= w19;
  /* #1047: @4 = (@4*@67) */
  w4 *= w67;
  /* #1048: @17 = (@17*@29) */
  w17 *= w29;
  /* #1049: @4 = (@4+@17) */
  w4 += w17;
  /* #1050: @13 = (@13+@4) */
  w13 += w4;
  /* #1051: @13 = (@13/@15) */
  w13 /= w15;
  /* #1052: @62 = (@62*@6) */
  w62 *= w6;
  /* #1053: @13 = (@13-@62) */
  w13 -= w62;
  /* #1054: @44 = (@44*@13) */
  for (i=0, rr=w44; i<3; ++i) (*rr++) *= w13;
  /* #1055: @1 = (@14*@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) (*rr++)  = (w14*(*cs++));
  /* #1056: @44 = (@44+@1) */
  for (i=0, rr=w44, cs=w1; i<3; ++i) (*rr++) += (*cs++);
  /* #1057: @47 = (@47*@16) */
  for (i=0, rr=w47; i<3; ++i) (*rr++) *= w16;
  /* #1058: @46 = (@12*@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #1059: @47 = (@47+@46) */
  for (i=0, rr=w47, cs=w46; i<3; ++i) (*rr++) += (*cs++);
  /* #1060: @47 = (2.*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #1061: @44 = (@44+@47) */
  for (i=0, rr=w44, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #1062: (@76[1:4] += @44) */
  for (rr=w76+1, ss=w44; rr!=w76+4; rr+=1) *rr += *ss++;
  /* #1063: @77 = (@0*@76) */
  for (i=0, rr=w77, cs=w76; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #1064: @76 = (@18*@76) */
  for (i=0, rr=w76, cs=w76; i<4; ++i) (*rr++)  = (w18*(*cs++));
  /* #1065: @77 = (@77-@76) */
  for (i=0, rr=w77, cs=w76; i<4; ++i) (*rr++) -= (*cs++);
  /* #1066: {@18, @0, @12, @16} = vertsplit(@77) */
  w18 = w77[0];
  w0 = w77[1];
  w12 = w77[2];
  w16 = w77[3];
  /* #1067: @14 = (@7*@16) */
  w14  = (w7*w16);
  /* #1068: @13 = (@8*@12) */
  w13  = (w8*w12);
  /* #1069: @14 = (@14+@13) */
  w14 += w13;
  /* #1070: @13 = (@9*@0) */
  w13  = (w9*w0);
  /* #1071: @14 = (@14-@13) */
  w14 -= w13;
  /* #1072: @13 = (@10*@18) */
  w13  = (w10*w18);
  /* #1073: @14 = (@14-@13) */
  w14 -= w13;
  /* #1074: (@50[3] += @14) */
  for (rr=w50+3, ss=(&w14); rr!=w50+4; rr+=1) *rr += *ss++;
  /* #1075: @14 = (@7*@12) */
  w14  = (w7*w12);
  /* #1076: @13 = (@8*@16) */
  w13  = (w8*w16);
  /* #1077: @14 = (@14-@13) */
  w14 -= w13;
  /* #1078: @13 = (@10*@0) */
  w13  = (w10*w0);
  /* #1079: @14 = (@14+@13) */
  w14 += w13;
  /* #1080: @13 = (@9*@18) */
  w13  = (w9*w18);
  /* #1081: @14 = (@14-@13) */
  w14 -= w13;
  /* #1082: (@50[2] += @14) */
  for (rr=w50+2, ss=(&w14); rr!=w50+3; rr+=1) *rr += *ss++;
  /* #1083: @14 = (@9*@16) */
  w14  = (w9*w16);
  /* #1084: @13 = (@10*@12) */
  w13  = (w10*w12);
  /* #1085: @14 = (@14-@13) */
  w14 -= w13;
  /* #1086: @13 = (@7*@0) */
  w13  = (w7*w0);
  /* #1087: @14 = (@14+@13) */
  w14 += w13;
  /* #1088: @13 = (@8*@18) */
  w13  = (w8*w18);
  /* #1089: @14 = (@14-@13) */
  w14 -= w13;
  /* #1090: (@50[1] += @14) */
  for (rr=w50+1, ss=(&w14); rr!=w50+2; rr+=1) *rr += *ss++;
  /* #1091: @10 = (@10*@16) */
  w10 *= w16;
  /* #1092: @9 = (@9*@12) */
  w9 *= w12;
  /* #1093: @10 = (@10+@9) */
  w10 += w9;
  /* #1094: @8 = (@8*@0) */
  w8 *= w0;
  /* #1095: @10 = (@10+@8) */
  w10 += w8;
  /* #1096: @7 = (@7*@18) */
  w7 *= w18;
  /* #1097: @10 = (@10+@7) */
  w10 += w7;
  /* #1098: (@50[0] += @10) */
  for (rr=w50+0, ss=(&w10); rr!=w50+1; rr+=1) *rr += *ss++;
  /* #1099: @10 = dot(@42, @50) */
  w10 = casadi_dot(4, w42, w50);
  /* #1100: @70 = (@70/@11) */
  for (i=0, rr=w70; i<4; ++i) (*rr++) /= w11;
  /* #1101: @43 = (@43*@31) */
  for (i=0, rr=w43; i<4; ++i) (*rr++) *= w31;
  /* #1102: @70 = (@70-@43) */
  for (i=0, rr=w70, cs=w43; i<4; ++i) (*rr++) -= (*cs++);
  /* #1103: @70 = (-@70) */
  for (i=0, rr=w70, cs=w70; i<4; ++i) *rr++ = (- *cs++ );
  /* #1104: @7 = dot(@70, @49) */
  w7 = casadi_dot(4, w70, w49);
  /* #1105: @10 = (@10+@7) */
  w10 += w7;
  /* #1106: @10 = (@10/@11) */
  w10 /= w11;
  /* #1107: @28 = (@28*@31) */
  w28 *= w31;
  /* #1108: @10 = (@10-@28) */
  w10 -= w28;
  /* #1109: @41 = (@41*@10) */
  for (i=0, rr=w41; i<4; ++i) (*rr++) *= w10;
  /* #1110: @22 = (@22*@2) */
  w22 *= w2;
  /* #1111: @70 = dense(@22) */
  casadi_densify((&w22), casadi_s15, w70, 0);
  /* #1112: @41 = (@41+@70) */
  for (i=0, rr=w41, cs=w70; i<4; ++i) (*rr++) += (*cs++);
  /* #1113: (@34[4:8] += @41) */
  for (rr=w34+4, ss=w41; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #1114: {@22, @2, @10, @28, @7, @18, @8, @0, @9, @12, @16, @14, @13, @62, @6, @15, @4, @17, @29, @67, @19} = vertsplit(@34) */
  w22 = w34[0];
  w2 = w34[1];
  w10 = w34[2];
  w28 = w34[3];
  w7 = w34[4];
  w18 = w34[5];
  w8 = w34[6];
  w0 = w34[7];
  w9 = w34[8];
  w12 = w34[9];
  w16 = w34[10];
  w14 = w34[11];
  w13 = w34[12];
  w62 = w34[13];
  w6 = w34[14];
  w15 = w34[15];
  w4 = w34[16];
  w17 = w34[17];
  w29 = w34[18];
  w67 = w34[19];
  w19 = w34[20];
  /* #1115: @50 = (@50/@11) */
  for (i=0, rr=w50; i<4; ++i) (*rr++) /= w11;
  /* #1116: @56 = (@56*@31) */
  for (i=0, rr=w56; i<4; ++i) (*rr++) *= w31;
  /* #1117: @50 = (@50-@56) */
  for (i=0, rr=w50, cs=w56; i<4; ++i) (*rr++) -= (*cs++);
  /* #1118: {@31, @11, @65, @3} = vertsplit(@50) */
  w31 = w50[0];
  w11 = w50[1];
  w65 = w50[2];
  w3 = w50[3];
  /* #1119: @31 = (@31+@7) */
  w31 += w7;
  /* #1120: @18 = (@18-@11) */
  w18 -= w11;
  /* #1121: @8 = (@8-@65) */
  w8 -= w65;
  /* #1122: @0 = (@0-@3) */
  w0 -= w3;
  /* #1123: @34 = vertcat(@22, @2, @10, @28, @31, @18, @8, @0, @9, @12, @16, @14, @13, @62, @6, @15, @4, @17, @29, @67, @19) */
  rr=w34;
  *rr++ = w22;
  *rr++ = w2;
  *rr++ = w10;
  *rr++ = w28;
  *rr++ = w31;
  *rr++ = w18;
  *rr++ = w8;
  *rr++ = w0;
  *rr++ = w9;
  *rr++ = w12;
  *rr++ = w16;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w62;
  *rr++ = w6;
  *rr++ = w15;
  *rr++ = w4;
  *rr++ = w17;
  *rr++ = w29;
  *rr++ = w67;
  *rr++ = w19;
  /* #1124: @50 = @34[4:8] */
  for (rr=w50, ss=w34+4; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #1125: (@69[21:25] = @50) */
  for (rr=w69+21, ss=w50; rr!=w69+25; rr+=1) *rr = *ss++;
  /* #1126: @50 = @34[4:8] */
  for (rr=w50, ss=w34+4; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #1127: (@69[12:28:4] = @50) */
  for (rr=w69+12, ss=w50; rr!=w69+28; rr+=4) *rr = *ss++;
  /* #1128: @91 = @69' */
  casadi_trans(w69,casadi_s16, w91, casadi_s16, iw);
  /* #1129: output[2][0] = @91 */
  casadi_copy(w91, 34, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s17;
    case 1: return casadi_s18;
    case 2: return casadi_s18;
    case 3: return casadi_s19;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s20;
    case 1: return casadi_s17;
    case 2: return casadi_s16;
    case 3: return casadi_s18;
    case 4: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34;
  if (sz_res) *sz_res = 26;
  if (sz_iw) *sz_iw = 22;
  if (sz_w) *sz_w = 336;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
