/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_cost_ext_cost_e_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};

/* Drone_ode_cost_ext_cost_e_fun_jac:(i0[21],i1[],i2[],i3[30])->(o0,o1[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, *w32=w+35, *w33=w+65, *w34=w+68, *w35=w+89, *w36=w+92, *w37=w+101, *w38=w+104, *w39=w+107, *w40=w+116, *w41=w+120, *w42=w+124, *w43=w+128, *w44=w+132, *w45=w+135, *w46=w+138, *w47=w+141, *w48=w+144, *w49=w+153, *w50=w+156, *w51=w+165;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x3) */
  casadi_clear(w1, 3);
  /* #2: @2 = input[3][28] */
  w2 = arg[3] ? arg[3][28] : 0;
  /* #3: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #4: @4 = input[3][1] */
  w4 = arg[3] ? arg[3][1] : 0;
  /* #5: @5 = input[3][2] */
  w5 = arg[3] ? arg[3][2] : 0;
  /* #6: @6 = input[3][3] */
  w6 = arg[3] ? arg[3][3] : 0;
  /* #7: @7 = input[3][4] */
  w7 = arg[3] ? arg[3][4] : 0;
  /* #8: @8 = input[3][5] */
  w8 = arg[3] ? arg[3][5] : 0;
  /* #9: @9 = input[3][6] */
  w9 = arg[3] ? arg[3][6] : 0;
  /* #10: @10 = input[3][7] */
  w10 = arg[3] ? arg[3][7] : 0;
  /* #11: @11 = input[3][8] */
  w11 = arg[3] ? arg[3][8] : 0;
  /* #12: @12 = input[3][9] */
  w12 = arg[3] ? arg[3][9] : 0;
  /* #13: @13 = input[3][10] */
  w13 = arg[3] ? arg[3][10] : 0;
  /* #14: @14 = input[3][11] */
  w14 = arg[3] ? arg[3][11] : 0;
  /* #15: @15 = input[3][12] */
  w15 = arg[3] ? arg[3][12] : 0;
  /* #16: @16 = input[3][13] */
  w16 = arg[3] ? arg[3][13] : 0;
  /* #17: @17 = input[3][14] */
  w17 = arg[3] ? arg[3][14] : 0;
  /* #18: @18 = input[3][15] */
  w18 = arg[3] ? arg[3][15] : 0;
  /* #19: @19 = input[3][16] */
  w19 = arg[3] ? arg[3][16] : 0;
  /* #20: @20 = input[3][17] */
  w20 = arg[3] ? arg[3][17] : 0;
  /* #21: @21 = input[3][18] */
  w21 = arg[3] ? arg[3][18] : 0;
  /* #22: @22 = input[3][19] */
  w22 = arg[3] ? arg[3][19] : 0;
  /* #23: @23 = input[3][20] */
  w23 = arg[3] ? arg[3][20] : 0;
  /* #24: @24 = input[3][21] */
  w24 = arg[3] ? arg[3][21] : 0;
  /* #25: @25 = input[3][22] */
  w25 = arg[3] ? arg[3][22] : 0;
  /* #26: @26 = input[3][23] */
  w26 = arg[3] ? arg[3][23] : 0;
  /* #27: @27 = input[3][24] */
  w27 = arg[3] ? arg[3][24] : 0;
  /* #28: @28 = input[3][25] */
  w28 = arg[3] ? arg[3][25] : 0;
  /* #29: @29 = input[3][26] */
  w29 = arg[3] ? arg[3][26] : 0;
  /* #30: @30 = input[3][27] */
  w30 = arg[3] ? arg[3][27] : 0;
  /* #31: @31 = input[3][29] */
  w31 = arg[3] ? arg[3][29] : 0;
  /* #32: @32 = vertcat(@3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @2, @31) */
  rr=w32;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w2;
  *rr++ = w31;
  /* #33: @33 = @32[:3] */
  for (rr=w33, ss=w32+0; ss!=w32+3; ss+=1) *rr++ = *ss;
  /* #34: @3 = input[0][0] */
  w3 = arg[0] ? arg[0][0] : 0;
  /* #35: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #36: @5 = input[0][2] */
  w5 = arg[0] ? arg[0][2] : 0;
  /* #37: @6 = input[0][3] */
  w6 = arg[0] ? arg[0][3] : 0;
  /* #38: @11 = input[0][4] */
  w11 = arg[0] ? arg[0][4] : 0;
  /* #39: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #40: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #41: @14 = input[0][7] */
  w14 = arg[0] ? arg[0][7] : 0;
  /* #42: @15 = input[0][8] */
  w15 = arg[0] ? arg[0][8] : 0;
  /* #43: @16 = input[0][9] */
  w16 = arg[0] ? arg[0][9] : 0;
  /* #44: @17 = input[0][10] */
  w17 = arg[0] ? arg[0][10] : 0;
  /* #45: @18 = input[0][11] */
  w18 = arg[0] ? arg[0][11] : 0;
  /* #46: @19 = input[0][12] */
  w19 = arg[0] ? arg[0][12] : 0;
  /* #47: @20 = input[0][13] */
  w20 = arg[0] ? arg[0][13] : 0;
  /* #48: @21 = input[0][14] */
  w21 = arg[0] ? arg[0][14] : 0;
  /* #49: @22 = input[0][15] */
  w22 = arg[0] ? arg[0][15] : 0;
  /* #50: @23 = input[0][16] */
  w23 = arg[0] ? arg[0][16] : 0;
  /* #51: @24 = input[0][17] */
  w24 = arg[0] ? arg[0][17] : 0;
  /* #52: @25 = input[0][18] */
  w25 = arg[0] ? arg[0][18] : 0;
  /* #53: @26 = input[0][19] */
  w26 = arg[0] ? arg[0][19] : 0;
  /* #54: @27 = input[0][20] */
  w27 = arg[0] ? arg[0][20] : 0;
  /* #55: @34 = vertcat(@3, @4, @5, @6, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27) */
  rr=w34;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  *rr++ = w26;
  *rr++ = w27;
  /* #56: @35 = @34[:3] */
  for (rr=w35, ss=w34+0; ss!=w34+3; ss+=1) *rr++ = *ss;
  /* #57: @33 = (@33-@35) */
  for (i=0, rr=w33, cs=w35; i<3; ++i) (*rr++) -= (*cs++);
  /* #58: @35 = @33' */
  casadi_copy(w33, 3, w35);
  /* #59: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #60: @36 = zeros(3x3) */
  casadi_clear(w36, 9);
  /* #61: @3 = 1 */
  w3 = 1.;
  /* #62: (@36[0] = @3) */
  for (rr=w36+0, ss=(&w3); rr!=w36+1; rr+=1) *rr = *ss++;
  /* #63: @3 = 1 */
  w3 = 1.;
  /* #64: (@36[4] = @3) */
  for (rr=w36+4, ss=(&w3); rr!=w36+5; rr+=1) *rr = *ss++;
  /* #65: @3 = 1 */
  w3 = 1.;
  /* #66: (@36[8] = @3) */
  for (rr=w36+8, ss=(&w3); rr!=w36+9; rr+=1) *rr = *ss++;
  /* #67: @1 = mac(@35,@36,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w36+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = mac(@1,@33,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w33+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #69: @3 = 0 */
  w3 = 0.;
  /* #70: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #71: @37 = @32[11:14] */
  for (rr=w37, ss=w32+11; ss!=w32+14; ss+=1) *rr++ = *ss;
  /* #72: @38 = @34[11:14] */
  for (rr=w38, ss=w34+11; ss!=w34+14; ss+=1) *rr++ = *ss;
  /* #73: @37 = (@37-@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #74: @38 = @37' */
  casadi_copy(w37, 3, w38);
  /* #75: @38 = (@31*@38) */
  for (i=0, rr=w38, cs=w38; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #76: @39 = zeros(3x3) */
  casadi_clear(w39, 9);
  /* #77: @4 = 1 */
  w4 = 1.;
  /* #78: (@39[4] = @4) */
  for (rr=w39+4, ss=(&w4); rr!=w39+5; rr+=1) *rr = *ss++;
  /* #79: @4 = 1 */
  w4 = 1.;
  /* #80: (@39[8] = @4) */
  for (rr=w39+8, ss=(&w4); rr!=w39+9; rr+=1) *rr = *ss++;
  /* #81: @35 = mac(@38,@39,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w39+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #82: @3 = mac(@35,@37,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w37+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #83: @0 = (@0+@3) */
  w0 += w3;
  /* #84: @3 = 0 */
  w3 = 0.;
  /* #85: @38 = zeros(1x3) */
  casadi_clear(w38, 3);
  /* #86: @12 = (-@12) */
  w12 = (- w12 );
  /* #87: @13 = (-@13) */
  w13 = (- w13 );
  /* #88: @14 = (-@14) */
  w14 = (- w14 );
  /* #89: @40 = vertcat(@11, @12, @13, @14) */
  rr=w40;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  /* #90: @41 = @34[4:8] */
  for (rr=w41, ss=w34+4; ss!=w34+8; ss+=1) *rr++ = *ss;
  /* #91: @11 = ||@41||_F */
  w11 = sqrt(casadi_dot(4, w41, w41));
  /* #92: @40 = (@40/@11) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w11;
  /* #93: @12 = @40[0] */
  for (rr=(&w12), ss=w40+0; ss!=w40+1; ss+=1) *rr++ = *ss;
  /* #94: @13 = (@12*@7) */
  w13  = (w12*w7);
  /* #95: @14 = @40[1] */
  for (rr=(&w14), ss=w40+1; ss!=w40+2; ss+=1) *rr++ = *ss;
  /* #96: @4 = (@14*@8) */
  w4  = (w14*w8);
  /* #97: @13 = (@13-@4) */
  w13 -= w4;
  /* #98: @4 = @40[2] */
  for (rr=(&w4), ss=w40+2; ss!=w40+3; ss+=1) *rr++ = *ss;
  /* #99: @5 = (@4*@9) */
  w5  = (w4*w9);
  /* #100: @13 = (@13-@5) */
  w13 -= w5;
  /* #101: @5 = @40[3] */
  for (rr=(&w5), ss=w40+3; ss!=w40+4; ss+=1) *rr++ = *ss;
  /* #102: @6 = (@5*@10) */
  w6  = (w5*w10);
  /* #103: @13 = (@13-@6) */
  w13 -= w6;
  /* #104: @6 = 0 */
  w6 = 0.;
  /* #105: @6 = (@13<@6) */
  w6  = (w13<w6);
  /* #106: @15 = (@12*@8) */
  w15  = (w12*w8);
  /* #107: @16 = (@14*@7) */
  w16  = (w14*w7);
  /* #108: @15 = (@15+@16) */
  w15 += w16;
  /* #109: @16 = (@4*@10) */
  w16  = (w4*w10);
  /* #110: @15 = (@15+@16) */
  w15 += w16;
  /* #111: @16 = (@5*@9) */
  w16  = (w5*w9);
  /* #112: @15 = (@15-@16) */
  w15 -= w16;
  /* #113: @16 = (@12*@9) */
  w16  = (w12*w9);
  /* #114: @17 = (@14*@10) */
  w17  = (w14*w10);
  /* #115: @16 = (@16-@17) */
  w16 -= w17;
  /* #116: @17 = (@4*@7) */
  w17  = (w4*w7);
  /* #117: @16 = (@16+@17) */
  w16 += w17;
  /* #118: @17 = (@5*@8) */
  w17  = (w5*w8);
  /* #119: @16 = (@16+@17) */
  w16 += w17;
  /* #120: @12 = (@12*@10) */
  w12 *= w10;
  /* #121: @14 = (@14*@9) */
  w14 *= w9;
  /* #122: @12 = (@12+@14) */
  w12 += w14;
  /* #123: @4 = (@4*@8) */
  w4 *= w8;
  /* #124: @12 = (@12-@4) */
  w12 -= w4;
  /* #125: @5 = (@5*@7) */
  w5 *= w7;
  /* #126: @12 = (@12+@5) */
  w12 += w5;
  /* #127: @42 = vertcat(@13, @15, @16, @12) */
  rr=w42;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w12;
  /* #128: @43 = (-@42) */
  for (i=0, rr=w43, cs=w42; i<4; ++i) *rr++ = (- *cs++ );
  /* #129: @43 = (@6?@43:0) */
  for (i=0, rr=w43, cs=w43; i<4; ++i) (*rr++)  = (w6?(*cs++):0);
  /* #130: @13 = (!@6) */
  w13 = (! w6 );
  /* #131: @42 = (@13?@42:0) */
  for (i=0, rr=w42, cs=w42; i<4; ++i) (*rr++)  = (w13?(*cs++):0);
  /* #132: @43 = (@43+@42) */
  for (i=0, rr=w43, cs=w42; i<4; ++i) (*rr++) += (*cs++);
  /* #133: @44 = @43[1:4] */
  for (rr=w44, ss=w43+1; ss!=w43+4; ss+=1) *rr++ = *ss;
  /* #134: @45 = (2.*@44) */
  for (i=0, rr=w45, cs=w44; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #135: @15 = ||@44||_F */
  w15 = sqrt(casadi_dot(3, w44, w44));
  /* #136: @16 = @43[0] */
  for (rr=(&w16), ss=w43+0; ss!=w43+1; ss+=1) *rr++ = *ss;
  /* #137: @12 = atan2(@15,@16) */
  w12  = atan2(w15,w16);
  /* #138: @46 = (@45*@12) */
  for (i=0, rr=w46, cr=w45; i<3; ++i) (*rr++)  = ((*cr++)*w12);
  /* #139: @46 = (@46/@15) */
  for (i=0, rr=w46; i<3; ++i) (*rr++) /= w15;
  /* #140: @47 = @46' */
  casadi_copy(w46, 3, w47);
  /* #141: @48 = zeros(3x3) */
  casadi_clear(w48, 9);
  /* #142: @5 = 1 */
  w5 = 1.;
  /* #143: (@48[0] = @5) */
  for (rr=w48+0, ss=(&w5); rr!=w48+1; rr+=1) *rr = *ss++;
  /* #144: @5 = 1 */
  w5 = 1.;
  /* #145: (@48[4] = @5) */
  for (rr=w48+4, ss=(&w5); rr!=w48+5; rr+=1) *rr = *ss++;
  /* #146: @5 = 1 */
  w5 = 1.;
  /* #147: (@48[8] = @5) */
  for (rr=w48+8, ss=(&w5); rr!=w48+9; rr+=1) *rr = *ss++;
  /* #148: @38 = mac(@47,@48,@38) */
  for (i=0, rr=w38; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w48+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #149: @3 = mac(@38,@46,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w46+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #150: @0 = (@0+@3) */
  w0 += w3;
  /* #151: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #152: @34 = zeros(21x1) */
  casadi_clear(w34, 21);
  /* #153: @40 = (@40/@11) */
  for (i=0, rr=w40; i<4; ++i) (*rr++) /= w11;
  /* #154: @40 = (-@40) */
  for (i=0, rr=w40, cs=w40; i<4; ++i) *rr++ = (- *cs++ );
  /* #155: @43 = zeros(4x1) */
  casadi_clear(w43, 4);
  /* #156: @0 = 1 */
  w0 = 1.;
  /* #157: @13 = (@13?@0:0) */
  w13  = (w13?w0:0);
  /* #158: @42 = zeros(4x1) */
  casadi_clear(w42, 4);
  /* #159: @0 = sq(@15) */
  w0 = casadi_sq( w15 );
  /* #160: @3 = sq(@16) */
  w3 = casadi_sq( w16 );
  /* #161: @0 = (@0+@3) */
  w0 += w3;
  /* #162: @3 = (@15/@0) */
  w3  = (w15/w0);
  /* #163: @38 = @38' */
  /* #164: @47 = zeros(1x3) */
  casadi_clear(w47, 3);
  /* #165: @49 = @46' */
  casadi_copy(w46, 3, w49);
  /* #166: @50 = @48' */
  for (i=0, rr=w50, cs=w48; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #167: @47 = mac(@49,@50,@47) */
  for (i=0, rr=w47; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #168: @47 = @47' */
  /* #169: @38 = (@38+@47) */
  for (i=0, rr=w38, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #170: @47 = (@38/@15) */
  for (i=0, rr=w47, cr=w38; i<3; ++i) (*rr++)  = ((*cr++)/w15);
  /* #171: @5 = dot(@45, @47) */
  w5 = casadi_dot(3, w45, w47);
  /* #172: @3 = (@3*@5) */
  w3 *= w5;
  /* #173: @3 = (-@3) */
  w3 = (- w3 );
  /* #174: (@42[0] += @3) */
  for (rr=w42+0, ss=(&w3); rr!=w42+1; rr+=1) *rr += *ss++;
  /* #175: @46 = (@46/@15) */
  for (i=0, rr=w46; i<3; ++i) (*rr++) /= w15;
  /* #176: @46 = (-@46) */
  for (i=0, rr=w46, cs=w46; i<3; ++i) *rr++ = (- *cs++ );
  /* #177: @3 = dot(@46, @38) */
  w3 = casadi_dot(3, w46, w38);
  /* #178: @16 = (@16/@0) */
  w16 /= w0;
  /* #179: @16 = (@16*@5) */
  w16 *= w5;
  /* #180: @3 = (@3+@16) */
  w3 += w16;
  /* #181: @3 = (@3/@15) */
  w3 /= w15;
  /* #182: @44 = (@3*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) (*rr++)  = (w3*(*cs++));
  /* #183: @47 = (@12*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #184: @47 = (2.*@47) */
  for (i=0, rr=w47, cs=w47; i<3; ++i) *rr++ = (2.* *cs++ );
  /* #185: @44 = (@44+@47) */
  for (i=0, rr=w44, cs=w47; i<3; ++i) (*rr++) += (*cs++);
  /* #186: (@42[1:4] += @44) */
  for (rr=w42+1, ss=w44; rr!=w42+4; rr+=1) *rr += *ss++;
  /* #187: @51 = (@13*@42) */
  for (i=0, rr=w51, cs=w42; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #188: @13 = 1 */
  w13 = 1.;
  /* #189: @6 = (@6?@13:0) */
  w6  = (w6?w13:0);
  /* #190: @42 = (@6*@42) */
  for (i=0, rr=w42, cs=w42; i<4; ++i) (*rr++)  = (w6*(*cs++));
  /* #191: @51 = (@51-@42) */
  for (i=0, rr=w51, cs=w42; i<4; ++i) (*rr++) -= (*cs++);
  /* #192: {@6, @13, @12, @3} = vertsplit(@51) */
  w6 = w51[0];
  w13 = w51[1];
  w12 = w51[2];
  w3 = w51[3];
  /* #193: @15 = (@7*@3) */
  w15  = (w7*w3);
  /* #194: @16 = (@8*@12) */
  w16  = (w8*w12);
  /* #195: @15 = (@15+@16) */
  w15 += w16;
  /* #196: @16 = (@9*@13) */
  w16  = (w9*w13);
  /* #197: @15 = (@15-@16) */
  w15 -= w16;
  /* #198: @16 = (@10*@6) */
  w16  = (w10*w6);
  /* #199: @15 = (@15-@16) */
  w15 -= w16;
  /* #200: (@43[3] += @15) */
  for (rr=w43+3, ss=(&w15); rr!=w43+4; rr+=1) *rr += *ss++;
  /* #201: @15 = (@7*@12) */
  w15  = (w7*w12);
  /* #202: @16 = (@8*@3) */
  w16  = (w8*w3);
  /* #203: @15 = (@15-@16) */
  w15 -= w16;
  /* #204: @16 = (@10*@13) */
  w16  = (w10*w13);
  /* #205: @15 = (@15+@16) */
  w15 += w16;
  /* #206: @16 = (@9*@6) */
  w16  = (w9*w6);
  /* #207: @15 = (@15-@16) */
  w15 -= w16;
  /* #208: (@43[2] += @15) */
  for (rr=w43+2, ss=(&w15); rr!=w43+3; rr+=1) *rr += *ss++;
  /* #209: @15 = (@9*@3) */
  w15  = (w9*w3);
  /* #210: @16 = (@10*@12) */
  w16  = (w10*w12);
  /* #211: @15 = (@15-@16) */
  w15 -= w16;
  /* #212: @16 = (@7*@13) */
  w16  = (w7*w13);
  /* #213: @15 = (@15+@16) */
  w15 += w16;
  /* #214: @16 = (@8*@6) */
  w16  = (w8*w6);
  /* #215: @15 = (@15-@16) */
  w15 -= w16;
  /* #216: (@43[1] += @15) */
  for (rr=w43+1, ss=(&w15); rr!=w43+2; rr+=1) *rr += *ss++;
  /* #217: @10 = (@10*@3) */
  w10 *= w3;
  /* #218: @9 = (@9*@12) */
  w9 *= w12;
  /* #219: @10 = (@10+@9) */
  w10 += w9;
  /* #220: @8 = (@8*@13) */
  w8 *= w13;
  /* #221: @10 = (@10+@8) */
  w10 += w8;
  /* #222: @7 = (@7*@6) */
  w7 *= w6;
  /* #223: @10 = (@10+@7) */
  w10 += w7;
  /* #224: (@43[0] += @10) */
  for (rr=w43+0, ss=(&w10); rr!=w43+1; rr+=1) *rr += *ss++;
  /* #225: @10 = dot(@40, @43) */
  w10 = casadi_dot(4, w40, w43);
  /* #226: @10 = (@10/@11) */
  w10 /= w11;
  /* #227: @41 = (@10*@41) */
  for (i=0, rr=w41, cs=w41; i<4; ++i) (*rr++)  = (w10*(*cs++));
  /* #228: (@34[4:8] += @41) */
  for (rr=w34+4, ss=w41; rr!=w34+8; rr+=1) *rr += *ss++;
  /* #229: @35 = @35' */
  /* #230: @44 = zeros(1x3) */
  casadi_clear(w44, 3);
  /* #231: @37 = @37' */
  /* #232: @50 = @39' */
  for (i=0, rr=w50, cs=w39; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #233: @44 = mac(@37,@50,@44) */
  for (i=0, rr=w44; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #234: @44 = (@31*@44) */
  for (i=0, rr=w44, cs=w44; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #235: @44 = @44' */
  /* #236: @35 = (@35+@44) */
  for (i=0, rr=w35, cs=w44; i<3; ++i) (*rr++) += (*cs++);
  /* #237: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #238: (@34[11:14] += @35) */
  for (rr=w34+11, ss=w35; rr!=w34+14; rr+=1) *rr += *ss++;
  /* #239: @1 = @1' */
  /* #240: @35 = zeros(1x3) */
  casadi_clear(w35, 3);
  /* #241: @33 = @33' */
  /* #242: @50 = @36' */
  for (i=0, rr=w50, cs=w36; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #243: @35 = mac(@33,@50,@35) */
  for (i=0, rr=w35; i<3; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w33+j, tt=w50+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #244: @35 = (@2*@35) */
  for (i=0, rr=w35, cs=w35; i<3; ++i) (*rr++)  = (w2*(*cs++));
  /* #245: @35 = @35' */
  /* #246: @1 = (@1+@35) */
  for (i=0, rr=w1, cs=w35; i<3; ++i) (*rr++) += (*cs++);
  /* #247: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<3; ++i) *rr++ = (- *cs++ );
  /* #248: (@34[:3] += @1) */
  for (rr=w34+0, ss=w1; rr!=w34+3; rr+=1) *rr += *ss++;
  /* #249: {@2, @31, @10, @7, @6, @8, @13, @9, @12, @3, @15, @16, @5, @0, @4, @14, @17, @18, @19, @20, @21} = vertsplit(@34) */
  w2 = w34[0];
  w31 = w34[1];
  w10 = w34[2];
  w7 = w34[3];
  w6 = w34[4];
  w8 = w34[5];
  w13 = w34[6];
  w9 = w34[7];
  w12 = w34[8];
  w3 = w34[9];
  w15 = w34[10];
  w16 = w34[11];
  w5 = w34[12];
  w0 = w34[13];
  w4 = w34[14];
  w14 = w34[15];
  w17 = w34[16];
  w18 = w34[17];
  w19 = w34[18];
  w20 = w34[19];
  w21 = w34[20];
  /* #250: output[1][0] = @2 */
  if (res[1]) res[1][0] = w2;
  /* #251: output[1][1] = @31 */
  if (res[1]) res[1][1] = w31;
  /* #252: output[1][2] = @10 */
  if (res[1]) res[1][2] = w10;
  /* #253: output[1][3] = @7 */
  if (res[1]) res[1][3] = w7;
  /* #254: @43 = (@43/@11) */
  for (i=0, rr=w43; i<4; ++i) (*rr++) /= w11;
  /* #255: {@11, @7, @10, @31} = vertsplit(@43) */
  w11 = w43[0];
  w7 = w43[1];
  w10 = w43[2];
  w31 = w43[3];
  /* #256: @11 = (@11+@6) */
  w11 += w6;
  /* #257: output[1][4] = @11 */
  if (res[1]) res[1][4] = w11;
  /* #258: @8 = (@8-@7) */
  w8 -= w7;
  /* #259: output[1][5] = @8 */
  if (res[1]) res[1][5] = w8;
  /* #260: @13 = (@13-@10) */
  w13 -= w10;
  /* #261: output[1][6] = @13 */
  if (res[1]) res[1][6] = w13;
  /* #262: @9 = (@9-@31) */
  w9 -= w31;
  /* #263: output[1][7] = @9 */
  if (res[1]) res[1][7] = w9;
  /* #264: output[1][8] = @12 */
  if (res[1]) res[1][8] = w12;
  /* #265: output[1][9] = @3 */
  if (res[1]) res[1][9] = w3;
  /* #266: output[1][10] = @15 */
  if (res[1]) res[1][10] = w15;
  /* #267: output[1][11] = @16 */
  if (res[1]) res[1][11] = w16;
  /* #268: output[1][12] = @5 */
  if (res[1]) res[1][12] = w5;
  /* #269: output[1][13] = @0 */
  if (res[1]) res[1][13] = w0;
  /* #270: output[1][14] = @4 */
  if (res[1]) res[1][14] = w4;
  /* #271: output[1][15] = @14 */
  if (res[1]) res[1][15] = w14;
  /* #272: output[1][16] = @17 */
  if (res[1]) res[1][16] = w17;
  /* #273: output[1][17] = @18 */
  if (res[1]) res[1][17] = w18;
  /* #274: output[1][18] = @19 */
  if (res[1]) res[1][18] = w19;
  /* #275: output[1][19] = @20 */
  if (res[1]) res[1][19] = w20;
  /* #276: output[1][20] = @21 */
  if (res[1]) res[1][20] = w21;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_cost_ext_cost_e_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_cost_ext_cost_e_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_cost_ext_cost_e_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_cost_ext_cost_e_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_cost_ext_cost_e_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_cost_ext_cost_e_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 34;
  if (sz_res) *sz_res = 23;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 169;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
