/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[3] = {1, 0, 0};

/* Drone_ode_constr_h_e_fun_jac_uxt_zt:(i0[8],i1[],i2[],i3[12])->(o0,o1[8],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+5, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+21, *w15=w+33, *w16=w+37, *w17=w+45, *w18=w+49, *w19=w+65, *w20=w+81, *w21=w+85, *w22=w+89, *w23=w+93, *w24=w+101;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = input[3][4] */
  w6 = arg[3] ? arg[3][4] : 0;
  /* #7: @7 = input[3][5] */
  w7 = arg[3] ? arg[3][5] : 0;
  /* #8: @8 = input[3][6] */
  w8 = arg[3] ? arg[3][6] : 0;
  /* #9: @9 = input[3][7] */
  w9 = arg[3] ? arg[3][7] : 0;
  /* #10: @10 = input[3][8] */
  w10 = arg[3] ? arg[3][8] : 0;
  /* #11: @11 = input[3][9] */
  w11 = arg[3] ? arg[3][9] : 0;
  /* #12: @12 = input[3][10] */
  w12 = arg[3] ? arg[3][10] : 0;
  /* #13: @13 = input[3][11] */
  w13 = arg[3] ? arg[3][11] : 0;
  /* #14: @14 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13) */
  rr=w14;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #15: @15 = @14[:4] */
  for (rr=w15, ss=w14+0; ss!=w14+4; ss+=1) *rr++ = *ss;
  /* #16: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #17: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #18: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #19: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #20: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #21: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #22: @8 = input[0][6] */
  w8 = arg[0] ? arg[0][6] : 0;
  /* #23: @9 = input[0][7] */
  w9 = arg[0] ? arg[0][7] : 0;
  /* #24: @16 = vertcat(@2, @3, @4, @5, @6, @7, @8, @9) */
  rr=w16;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w8;
  *rr++ = w9;
  /* #25: @17 = @16[:4] */
  for (rr=w17, ss=w16+0; ss!=w16+4; ss+=1) *rr++ = *ss;
  /* #26: @15 = (@15-@17) */
  for (i=0, rr=w15, cs=w17; i<4; ++i) (*rr++) -= (*cs++);
  /* #27: @17 = @15' */
  casadi_copy(w15, 4, w17);
  /* #28: @17 = (-@17) */
  for (i=0, rr=w17, cs=w17; i<4; ++i) *rr++ = (- *cs++ );
  /* #29: @18 = zeros(4x4) */
  casadi_clear(w18, 16);
  /* #30: @2 = 2 */
  w2 = 2.;
  /* #31: (@18[0] = @2) */
  for (rr=w18+0, ss=(&w2); rr!=w18+1; rr+=1) *rr = *ss++;
  /* #32: @2 = 2 */
  w2 = 2.;
  /* #33: (@18[5] = @2) */
  for (rr=w18+5, ss=(&w2); rr!=w18+6; rr+=1) *rr = *ss++;
  /* #34: @2 = 2 */
  w2 = 2.;
  /* #35: (@18[10] = @2) */
  for (rr=w18+10, ss=(&w2); rr!=w18+11; rr+=1) *rr = *ss++;
  /* #36: @2 = 2 */
  w2 = 2.;
  /* #37: (@18[15] = @2) */
  for (rr=w18+15, ss=(&w2); rr!=w18+16; rr+=1) *rr = *ss++;
  /* #38: @1 = mac(@17,@18,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #39: @17 = zeros(4x1) */
  casadi_clear(w17, 4);
  /* #40: @19 = zeros(4x4) */
  casadi_clear(w19, 16);
  /* #41: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #42: (@19[0] = @2) */
  for (rr=w19+0, ss=(&w2); rr!=w19+1; rr+=1) *rr = *ss++;
  /* #43: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #44: @2 = (-@2) */
  w2 = (- w2 );
  /* #45: (@19[4] = @2) */
  for (rr=w19+4, ss=(&w2); rr!=w19+5; rr+=1) *rr = *ss++;
  /* #46: @2 = 0 */
  w2 = 0.;
  /* #47: (@19[8] = @2) */
  for (rr=w19+8, ss=(&w2); rr!=w19+9; rr+=1) *rr = *ss++;
  /* #48: @2 = 0 */
  w2 = 0.;
  /* #49: (@19[12] = @2) */
  for (rr=w19+12, ss=(&w2); rr!=w19+13; rr+=1) *rr = *ss++;
  /* #50: @2 = sin(@5) */
  w2 = sin( w5 );
  /* #51: (@19[1] = @2) */
  for (rr=w19+1, ss=(&w2); rr!=w19+2; rr+=1) *rr = *ss++;
  /* #52: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #53: (@19[5] = @2) */
  for (rr=w19+5, ss=(&w2); rr!=w19+6; rr+=1) *rr = *ss++;
  /* #54: @2 = 0 */
  w2 = 0.;
  /* #55: (@19[9] = @2) */
  for (rr=w19+9, ss=(&w2); rr!=w19+10; rr+=1) *rr = *ss++;
  /* #56: @2 = 0 */
  w2 = 0.;
  /* #57: (@19[13] = @2) */
  for (rr=w19+13, ss=(&w2); rr!=w19+14; rr+=1) *rr = *ss++;
  /* #58: @2 = 0 */
  w2 = 0.;
  /* #59: (@19[2] = @2) */
  for (rr=w19+2, ss=(&w2); rr!=w19+3; rr+=1) *rr = *ss++;
  /* #60: @2 = 0 */
  w2 = 0.;
  /* #61: (@19[6] = @2) */
  for (rr=w19+6, ss=(&w2); rr!=w19+7; rr+=1) *rr = *ss++;
  /* #62: @2 = 1 */
  w2 = 1.;
  /* #63: (@19[10] = @2) */
  for (rr=w19+10, ss=(&w2); rr!=w19+11; rr+=1) *rr = *ss++;
  /* #64: @2 = 0 */
  w2 = 0.;
  /* #65: (@19[14] = @2) */
  for (rr=w19+14, ss=(&w2); rr!=w19+15; rr+=1) *rr = *ss++;
  /* #66: @2 = 0 */
  w2 = 0.;
  /* #67: (@19[3] = @2) */
  for (rr=w19+3, ss=(&w2); rr!=w19+4; rr+=1) *rr = *ss++;
  /* #68: @2 = 0 */
  w2 = 0.;
  /* #69: (@19[7] = @2) */
  for (rr=w19+7, ss=(&w2); rr!=w19+8; rr+=1) *rr = *ss++;
  /* #70: @2 = 0 */
  w2 = 0.;
  /* #71: (@19[11] = @2) */
  for (rr=w19+11, ss=(&w2); rr!=w19+12; rr+=1) *rr = *ss++;
  /* #72: @2 = 1 */
  w2 = 1.;
  /* #73: (@19[15] = @2) */
  for (rr=w19+15, ss=(&w2); rr!=w19+16; rr+=1) *rr = *ss++;
  /* #74: @20 = @16[4:8] */
  for (rr=w20, ss=w16+4; ss!=w16+8; ss+=1) *rr++ = *ss;
  /* #75: @17 = mac(@19,@20,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w19+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #76: @0 = mac(@1,@17,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w17+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #77: @2 = 0.1 */
  w2 = 1.0000000000000001e-01;
  /* #78: @3 = 0 */
  w3 = 0.;
  /* #79: @21 = zeros(1x4) */
  casadi_clear(w21, 4);
  /* #80: @4 = 0.5 */
  w4 = 5.0000000000000000e-01;
  /* #81: @22 = @15' */
  casadi_copy(w15, 4, w22);
  /* #82: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #83: @21 = mac(@22,@18,@21) */
  for (i=0, rr=w21; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #84: @3 = mac(@21,@15,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w21+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #85: @2 = (@2*@3) */
  w2 *= w3;
  /* #86: @0 = (@0+@2) */
  w0 += w2;
  /* #87: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #88: @16 = zeros(8x1) */
  casadi_clear(w16, 8);
  /* #89: @23 = zeros(8x1) */
  casadi_clear(w23, 8);
  /* #90: @22 = zeros(4x1) */
  casadi_clear(w22, 4);
  /* #91: @24 = @19' */
  for (i=0, rr=w24, cs=w19; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #92: @1 = @1' */
  /* #93: @22 = mac(@24,@1,@22) */
  for (i=0, rr=w22; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w24+j, tt=w1+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #94: (@23[4:8] += @22) */
  for (rr=w23+4, ss=w22; rr!=w23+8; rr+=1) *rr += *ss++;
  /* #95: @0 = 0.1 */
  w0 = 1.0000000000000001e-01;
  /* #96: @21 = @21' */
  /* #97: @21 = (@0*@21) */
  for (i=0, rr=w21, cs=w21; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #98: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #99: @15 = @15' */
  /* #100: @15 = (@0*@15) */
  for (i=0, rr=w15, cs=w15; i<4; ++i) (*rr++)  = (w0*(*cs++));
  /* #101: @24 = @18' */
  for (i=0, rr=w24, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #102: @22 = mac(@15,@24,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #103: @22 = (@4*@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) (*rr++)  = (w4*(*cs++));
  /* #104: @22 = @22' */
  /* #105: @21 = (@21+@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #106: @22 = zeros(1x4) */
  casadi_clear(w22, 4);
  /* #107: @17 = @17' */
  /* #108: @24 = @18' */
  for (i=0, rr=w24, cs=w18; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #109: @22 = mac(@17,@24,@22) */
  for (i=0, rr=w22; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w17+j, tt=w24+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #110: @22 = (-@22) */
  for (i=0, rr=w22, cs=w22; i<4; ++i) *rr++ = (- *cs++ );
  /* #111: @22 = @22' */
  /* #112: @21 = (@21+@22) */
  for (i=0, rr=w21, cs=w22; i<4; ++i) (*rr++) += (*cs++);
  /* #113: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<4; ++i) *rr++ = (- *cs++ );
  /* #114: (@23[:4] += @21) */
  for (rr=w23+0, ss=w21; rr!=w23+4; rr+=1) *rr += *ss++;
  /* #115: {@4, @0, @2, @3, @6, @7, @8, @9} = vertsplit(@23) */
  w4 = w23[0];
  w0 = w23[1];
  w2 = w23[2];
  w3 = w23[3];
  w6 = w23[4];
  w7 = w23[5];
  w8 = w23[6];
  w9 = w23[7];
  /* #116: (@16[0] = @4) */
  for (rr=w16+0, ss=(&w4); rr!=w16+1; rr+=1) *rr = *ss++;
  /* #117: (@16[1] = @0) */
  for (rr=w16+1, ss=(&w0); rr!=w16+2; rr+=1) *rr = *ss++;
  /* #118: (@16[2] = @2) */
  for (rr=w16+2, ss=(&w2); rr!=w16+3; rr+=1) *rr = *ss++;
  /* #119: @2 = cos(@5) */
  w2 = cos( w5 );
  /* #120: @24 = zeros(4x4) */
  casadi_clear(w24, 16);
  /* #121: @20 = @20' */
  /* #122: @24 = mac(@1,@20,@24) */
  for (i=0, rr=w24; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w1+j, tt=w20+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #123: @0 = 0 */
  w0 = 0.;
  /* #124: (@24[15] = @0) */
  for (rr=w24+15, ss=(&w0); rr!=w24+16; rr+=1) *rr = *ss++;
  /* #125: @0 = 0 */
  w0 = 0.;
  /* #126: (@24[11] = @0) */
  for (rr=w24+11, ss=(&w0); rr!=w24+12; rr+=1) *rr = *ss++;
  /* #127: @0 = 0 */
  w0 = 0.;
  /* #128: (@24[7] = @0) */
  for (rr=w24+7, ss=(&w0); rr!=w24+8; rr+=1) *rr = *ss++;
  /* #129: @0 = 0 */
  w0 = 0.;
  /* #130: (@24[3] = @0) */
  for (rr=w24+3, ss=(&w0); rr!=w24+4; rr+=1) *rr = *ss++;
  /* #131: @0 = 0 */
  w0 = 0.;
  /* #132: (@24[14] = @0) */
  for (rr=w24+14, ss=(&w0); rr!=w24+15; rr+=1) *rr = *ss++;
  /* #133: @0 = 0 */
  w0 = 0.;
  /* #134: (@24[10] = @0) */
  for (rr=w24+10, ss=(&w0); rr!=w24+11; rr+=1) *rr = *ss++;
  /* #135: @0 = 0 */
  w0 = 0.;
  /* #136: (@24[6] = @0) */
  for (rr=w24+6, ss=(&w0); rr!=w24+7; rr+=1) *rr = *ss++;
  /* #137: @0 = 0 */
  w0 = 0.;
  /* #138: (@24[2] = @0) */
  for (rr=w24+2, ss=(&w0); rr!=w24+3; rr+=1) *rr = *ss++;
  /* #139: @0 = 0 */
  w0 = 0.;
  /* #140: (@24[13] = @0) */
  for (rr=w24+13, ss=(&w0); rr!=w24+14; rr+=1) *rr = *ss++;
  /* #141: @0 = 0 */
  w0 = 0.;
  /* #142: (@24[9] = @0) */
  for (rr=w24+9, ss=(&w0); rr!=w24+10; rr+=1) *rr = *ss++;
  /* #143: @0 = 0 */
  w0 = 0.;
  /* #144: @18 = @24; (@18[5] = @0) */
  casadi_copy(w24, 16, w18);
  for (rr=w18+5, ss=(&w0); rr!=w18+6; rr+=1) *rr = *ss++;
  /* #145: @0 = @18[1] */
  for (rr=(&w0), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #146: @2 = (@2*@0) */
  w2 *= w0;
  /* #147: @0 = sin(@5) */
  w0 = sin( w5 );
  /* #148: @4 = @24[5] */
  for (rr=(&w4), ss=w24+5; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #149: @0 = (@0*@4) */
  w0 *= w4;
  /* #150: @2 = (@2-@0) */
  w2 -= w0;
  /* #151: @0 = cos(@5) */
  w0 = cos( w5 );
  /* #152: @4 = 0 */
  w4 = 0.;
  /* #153: (@18[1] = @4) */
  for (rr=w18+1, ss=(&w4); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #154: @4 = 0 */
  w4 = 0.;
  /* #155: (@18[12] = @4) */
  for (rr=w18+12, ss=(&w4); rr!=w18+13; rr+=1) *rr = *ss++;
  /* #156: @4 = 0 */
  w4 = 0.;
  /* #157: (@18[8] = @4) */
  for (rr=w18+8, ss=(&w4); rr!=w18+9; rr+=1) *rr = *ss++;
  /* #158: @4 = @18[4] */
  for (rr=(&w4), ss=w18+4; ss!=w18+5; ss+=1) *rr++ = *ss;
  /* #159: @0 = (@0*@4) */
  w0 *= w4;
  /* #160: @2 = (@2-@0) */
  w2 -= w0;
  /* #161: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #162: @0 = 0 */
  w0 = 0.;
  /* #163: (@18[4] = @0) */
  for (rr=w18+4, ss=(&w0); rr!=w18+5; rr+=1) *rr = *ss++;
  /* #164: @0 = @18[0] */
  for (rr=(&w0), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #165: @5 = (@5*@0) */
  w5 *= w0;
  /* #166: @2 = (@2-@5) */
  w2 -= w5;
  /* #167: @2 = (@2+@3) */
  w2 += w3;
  /* #168: (@16[3] = @2) */
  for (rr=w16+3, ss=(&w2); rr!=w16+4; rr+=1) *rr = *ss++;
  /* #169: (@16[4] = @6) */
  for (rr=w16+4, ss=(&w6); rr!=w16+5; rr+=1) *rr = *ss++;
  /* #170: (@16[5] = @7) */
  for (rr=w16+5, ss=(&w7); rr!=w16+6; rr+=1) *rr = *ss++;
  /* #171: (@16[6] = @8) */
  for (rr=w16+6, ss=(&w8); rr!=w16+7; rr+=1) *rr = *ss++;
  /* #172: (@16[7] = @9) */
  for (rr=w16+7, ss=(&w9); rr!=w16+8; rr+=1) *rr = *ss++;
  /* #173: output[1][0] = @16 */
  casadi_copy(w16, 8, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 117;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
