/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[4] = {0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[17] = {4, 4, 0, 4, 7, 9, 10, 0, 1, 2, 3, 1, 2, 3, 2, 3, 3};
static const casadi_int casadi_s3[17] = {4, 4, 0, 1, 3, 6, 10, 0, 0, 1, 0, 1, 2, 0, 1, 2, 3};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s6[16] = {1, 11, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0};
static const casadi_int casadi_s7[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s8[51] = {11, 4, 0, 11, 22, 33, 44, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s9[6] = {11, 1, 0, 2, 0, 1};
static const casadi_int casadi_s10[58] = {4, 11, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s11[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s12[3] = {0, 0, 0};
static const casadi_int casadi_s13[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s14[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s15[3] = {1, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* Drone_ode_constr_h_fun_jac_uxt_zt:(i0[11],i1[4],i2[],i3[17])->(o0,o1[15],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+12, w2, w3, w4, *w5=w+17, w6, w7, w8, w9, w10, w11, w12, w13, *w14=w+35, *w15=w+37, *w16=w+48, *w17=w+69, *w18=w+78, *w19=w+87, w20, w21, w22, *w23=w+99, w24, *w25=w+104, w26, *w27=w+109, *w28=w+118, *w29=w+121, *w30=w+154, *w31=w+187, w32, w33, w34, w35, w36, w37, *w38=w+205, *w39=w+209, *w40=w+213, *w41=w+217, *w42=w+221, *w43=w+237, *w44=w+253, *w45=w+297, *w46=w+341, *w47=w+369, *w48=w+385, *w49=w+401, *w50=w+445, *w51=w+566, w52, w53, *w54=w+689, *w55=w+700, *w56=w+715, *w57=w+726, w58, w59, *w60=w+739, *w61=w+748;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(11x1,2nz) */
  casadi_clear(w1, 2);
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[3][15] */
  w3 = arg[3] ? arg[3][15] : 0;
  /* #4: @3 = (@2-@3) */
  w3  = (w2-w3);
  /* #5: @4 = (2.*@3) */
  w4 = (2.* w3 );
  /* #6: @5 = ones(11x1,10nz) */
  casadi_fill(w5, 10, 1.);
  /* #7: {@6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@5) */
  w6 = w5[0];
  /* #8: @4 = (@4*@6) */
  w4 *= w6;
  /* #9: @7 = sq(@3) */
  w7 = casadi_sq( w3 );
  /* #10: @8 = input[0][1] */
  w8 = arg[0] ? arg[0][1] : 0;
  /* #11: @9 = input[3][16] */
  w9 = arg[3] ? arg[3][16] : 0;
  /* #12: @9 = (@8-@9) */
  w9  = (w8-w9);
  /* #13: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #14: @7 = (@7+@10) */
  w7 += w10;
  /* #15: @7 = sqrt(@7) */
  w7 = sqrt( w7 );
  /* #16: @10 = (2.*@7) */
  w10 = (2.* w7 );
  /* #17: @4 = (@4/@10) */
  w4 /= w10;
  /* #18: @11 = (-@4) */
  w11 = (- w4 );
  /* #19: (@1[0] = @11) */
  for (rr=w1+0, ss=(&w11); rr!=w1+1; rr+=1) *rr = *ss++;
  /* #20: @11 = (2.*@9) */
  w11 = (2.* w9 );
  /* #21: @12 = ones(11x1,1nz) */
  w12 = 1.;
  /* #22: {NULL, @13, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL} = vertsplit(@12) */
  w13 = w12;
  /* #23: @11 = (@11*@13) */
  w11 *= w13;
  /* #24: @11 = (@11/@10) */
  w11 /= w10;
  /* #25: @12 = (-@11) */
  w12 = (- w11 );
  /* #26: (@1[1] = @12) */
  for (rr=w1+1, ss=(&w12); rr!=w1+2; rr+=1) *rr = *ss++;
  /* #27: @14 = @1' */
  casadi_copy(w1, 2, w14);
  /* #28: @15 = zeros(11x1) */
  casadi_clear(w15, 11);
  /* #29: @16 = zeros(3x7) */
  casadi_clear(w16, 21);
  /* #30: @17 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w17);
  /* #31: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #32: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #33: @12 = input[0][3] */
  w12 = arg[0] ? arg[0][3] : 0;
  /* #34: @20 = input[0][4] */
  w20 = arg[0] ? arg[0][4] : 0;
  /* #35: @21 = input[0][5] */
  w21 = arg[0] ? arg[0][5] : 0;
  /* #36: @22 = input[0][6] */
  w22 = arg[0] ? arg[0][6] : 0;
  /* #37: @23 = vertcat(@12, @20, @21, @22) */
  rr=w23;
  *rr++ = w12;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  /* #38: @24 = ||@23||_F */
  w24 = sqrt(casadi_dot(4, w23, w23));
  /* #39: @25 = (@23/@24) */
  for (i=0, rr=w25, cr=w23; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #40: @26 = @25[3] */
  for (rr=(&w26), ss=w25+3; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #41: @26 = (-@26) */
  w26 = (- w26 );
  /* #42: (@19[3] = @26) */
  for (rr=w19+3, ss=(&w26); rr!=w19+4; rr+=1) *rr = *ss++;
  /* #43: @26 = @25[2] */
  for (rr=(&w26), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #44: (@19[6] = @26) */
  for (rr=w19+6, ss=(&w26); rr!=w19+7; rr+=1) *rr = *ss++;
  /* #45: @26 = @25[1] */
  for (rr=(&w26), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #46: @26 = (-@26) */
  w26 = (- w26 );
  /* #47: (@19[7] = @26) */
  for (rr=w19+7, ss=(&w26); rr!=w19+8; rr+=1) *rr = *ss++;
  /* #48: @26 = @25[3] */
  for (rr=(&w26), ss=w25+3; ss!=w25+4; ss+=1) *rr++ = *ss;
  /* #49: (@19[1] = @26) */
  for (rr=w19+1, ss=(&w26); rr!=w19+2; rr+=1) *rr = *ss++;
  /* #50: @26 = @25[2] */
  for (rr=(&w26), ss=w25+2; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #51: @26 = (-@26) */
  w26 = (- w26 );
  /* #52: (@19[2] = @26) */
  for (rr=w19+2, ss=(&w26); rr!=w19+3; rr+=1) *rr = *ss++;
  /* #53: @26 = @25[1] */
  for (rr=(&w26), ss=w25+1; ss!=w25+2; ss+=1) *rr++ = *ss;
  /* #54: (@19[5] = @26) */
  for (rr=w19+5, ss=(&w26); rr!=w19+6; rr+=1) *rr = *ss++;
  /* #55: @27 = (2.*@19) */
  for (i=0, rr=w27, cs=w19; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #56: @18 = mac(@27,@19,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w27+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #57: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #58: @26 = @25[0] */
  for (rr=(&w26), ss=w25+0; ss!=w25+1; ss+=1) *rr++ = *ss;
  /* #59: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #60: @18 = (@26*@19) */
  for (i=0, rr=w18, cs=w19; i<9; ++i) (*rr++)  = (w26*(*cs++));
  /* #61: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #62: @28 = zeros(3x1) */
  casadi_clear(w28, 3);
  /* #63: @29 = horzcat(@16, @17, @28) */
  rr=w29;
  for (i=0, cs=w16; i<21; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #64: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<11; ++i) for (j=0; j<3; ++j) rr[i+j*11] = *cs++;
  /* #65: @31 = zeros(4x3) */
  casadi_clear(w31, 12);
  /* #66: @32 = 0.5 */
  w32 = 5.0000000000000000e-01;
  /* #67: @33 = 0 */
  w33 = 0.;
  /* #68: @34 = 0 */
  w34 = 0.;
  /* #69: @35 = 0 */
  w35 = 0.;
  /* #70: @36 = input[0][10] */
  w36 = arg[0] ? arg[0][10] : 0;
  /* #71: @37 = (-@36) */
  w37 = (- w36 );
  /* #72: @38 = horzcat(@33, @34, @35, @37) */
  rr=w38;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w37;
  /* #73: @38 = @38' */
  /* #74: @33 = 0 */
  w33 = 0.;
  /* #75: @34 = 0 */
  w34 = 0.;
  /* #76: @35 = 0 */
  w35 = 0.;
  /* #77: @39 = horzcat(@33, @34, @36, @35) */
  rr=w39;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w36;
  *rr++ = w35;
  /* #78: @39 = @39' */
  /* #79: @33 = 0 */
  w33 = 0.;
  /* #80: @34 = (-@36) */
  w34 = (- w36 );
  /* #81: @35 = 0 */
  w35 = 0.;
  /* #82: @37 = 0 */
  w37 = 0.;
  /* #83: @40 = horzcat(@33, @34, @35, @37) */
  rr=w40;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  *rr++ = w37;
  /* #84: @40 = @40' */
  /* #85: @33 = 0 */
  w33 = 0.;
  /* #86: @34 = 0 */
  w34 = 0.;
  /* #87: @35 = 0 */
  w35 = 0.;
  /* #88: @41 = horzcat(@36, @33, @34, @35) */
  rr=w41;
  *rr++ = w36;
  *rr++ = w33;
  *rr++ = w34;
  *rr++ = w35;
  /* #89: @41 = @41' */
  /* #90: @42 = horzcat(@38, @39, @40, @41) */
  rr=w42;
  for (i=0, cs=w38; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<4; ++i) *rr++ = *cs++;
  /* #91: @43 = @42' */
  for (i=0, rr=w43, cs=w42; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #92: @43 = (@32*@43) */
  for (i=0, rr=w43, cs=w43; i<16; ++i) (*rr++)  = (w32*(*cs++));
  /* #93: @42 = zeros(4x4) */
  casadi_clear(w42, 16);
  /* #94: @44 = horzcat(@31, @43, @42) */
  rr=w44;
  for (i=0, cs=w31; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<16; ++i) *rr++ = *cs++;
  /* #95: @45 = @44' */
  for (i=0, rr=w45, cs=w44; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #96: @46 = zeros(4x7) */
  casadi_clear(w46, 28);
  /* #97: @43 = zeros(4x4) */
  casadi_clear(w43, 16);
  /* #98: @42 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w42);
  /* #99: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #100: @33 = 0.6756 */
  w33 = 6.7559999999999998e-01;
  /* #101: (@47[0] = @33) */
  for (rr=w47+0, ss=(&w33); rr!=w47+1; rr+=1) *rr = *ss++;
  /* #102: @33 = 0 */
  w33 = 0.;
  /* #103: (@47[4] = @33) */
  for (rr=w47+4, ss=(&w33); rr!=w47+5; rr+=1) *rr = *ss++;
  /* #104: @33 = 0 */
  w33 = 0.;
  /* #105: (@47[8] = @33) */
  for (rr=w47+8, ss=(&w33); rr!=w47+9; rr+=1) *rr = *ss++;
  /* #106: @33 = 0 */
  w33 = 0.;
  /* #107: (@47[12] = @33) */
  for (rr=w47+12, ss=(&w33); rr!=w47+13; rr+=1) *rr = *ss++;
  /* #108: @33 = 0 */
  w33 = 0.;
  /* #109: (@47[1] = @33) */
  for (rr=w47+1, ss=(&w33); rr!=w47+2; rr+=1) *rr = *ss++;
  /* #110: @33 = 0.6344 */
  w33 = 6.3439999999999996e-01;
  /* #111: (@47[5] = @33) */
  for (rr=w47+5, ss=(&w33); rr!=w47+6; rr+=1) *rr = *ss++;
  /* #112: @33 = 0 */
  w33 = 0.;
  /* #113: (@47[9] = @33) */
  for (rr=w47+9, ss=(&w33); rr!=w47+10; rr+=1) *rr = *ss++;
  /* #114: @33 = 0 */
  w33 = 0.;
  /* #115: (@47[13] = @33) */
  for (rr=w47+13, ss=(&w33); rr!=w47+14; rr+=1) *rr = *ss++;
  /* #116: @33 = 0 */
  w33 = 0.;
  /* #117: (@47[2] = @33) */
  for (rr=w47+2, ss=(&w33); rr!=w47+3; rr+=1) *rr = *ss++;
  /* #118: @33 = 0 */
  w33 = 0.;
  /* #119: (@47[6] = @33) */
  for (rr=w47+6, ss=(&w33); rr!=w47+7; rr+=1) *rr = *ss++;
  /* #120: @33 = 0.408 */
  w33 = 4.0799999999999997e-01;
  /* #121: (@47[10] = @33) */
  for (rr=w47+10, ss=(&w33); rr!=w47+11; rr+=1) *rr = *ss++;
  /* #122: @33 = 0 */
  w33 = 0.;
  /* #123: (@47[14] = @33) */
  for (rr=w47+14, ss=(&w33); rr!=w47+15; rr+=1) *rr = *ss++;
  /* #124: @33 = 0 */
  w33 = 0.;
  /* #125: (@47[3] = @33) */
  for (rr=w47+3, ss=(&w33); rr!=w47+4; rr+=1) *rr = *ss++;
  /* #126: @33 = 0 */
  w33 = 0.;
  /* #127: (@47[7] = @33) */
  for (rr=w47+7, ss=(&w33); rr!=w47+8; rr+=1) *rr = *ss++;
  /* #128: @33 = 0 */
  w33 = 0.;
  /* #129: (@47[11] = @33) */
  for (rr=w47+11, ss=(&w33); rr!=w47+12; rr+=1) *rr = *ss++;
  /* #130: @33 = 0.2953 */
  w33 = 2.9530000000000001e-01;
  /* #131: (@47[15] = @33) */
  for (rr=w47+15, ss=(&w33); rr!=w47+16; rr+=1) *rr = *ss++;
  /* #132: @42 = (@47\@42) */
  rr = w42;
  ss = w47;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #133: @48 = zeros(4x4) */
  casadi_clear(w48, 16);
  /* #134: @33 = 0.5941 */
  w33 = 5.9409999999999996e-01;
  /* #135: (@48[0] = @33) */
  for (rr=w48+0, ss=(&w33); rr!=w48+1; rr+=1) *rr = *ss++;
  /* #136: @33 = -0.8109 */
  w33 = -8.1089999999999995e-01;
  /* #137: @34 = (@33*@36) */
  w34  = (w33*w36);
  /* #138: (@48[4] = @34) */
  for (rr=w48+4, ss=(&w34); rr!=w48+5; rr+=1) *rr = *ss++;
  /* #139: @34 = 0 */
  w34 = 0.;
  /* #140: (@48[8] = @34) */
  for (rr=w48+8, ss=(&w34); rr!=w48+9; rr+=1) *rr = *ss++;
  /* #141: @34 = 0 */
  w34 = 0.;
  /* #142: (@48[12] = @34) */
  for (rr=w48+12, ss=(&w34); rr!=w48+13; rr+=1) *rr = *ss++;
  /* #143: @34 = 0.3984 */
  w34 = 3.9839999999999998e-01;
  /* #144: @35 = (@34*@36) */
  w35  = (w34*w36);
  /* #145: (@48[1] = @35) */
  for (rr=w48+1, ss=(&w35); rr!=w48+2; rr+=1) *rr = *ss++;
  /* #146: @35 = 0.704 */
  w35 = 7.0399999999999996e-01;
  /* #147: (@48[5] = @35) */
  for (rr=w48+5, ss=(&w35); rr!=w48+6; rr+=1) *rr = *ss++;
  /* #148: @35 = 0 */
  w35 = 0.;
  /* #149: (@48[9] = @35) */
  for (rr=w48+9, ss=(&w35); rr!=w48+10; rr+=1) *rr = *ss++;
  /* #150: @35 = 0 */
  w35 = 0.;
  /* #151: (@48[13] = @35) */
  for (rr=w48+13, ss=(&w35); rr!=w48+14; rr+=1) *rr = *ss++;
  /* #152: @35 = 0 */
  w35 = 0.;
  /* #153: (@48[2] = @35) */
  for (rr=w48+2, ss=(&w35); rr!=w48+3; rr+=1) *rr = *ss++;
  /* #154: @35 = 0 */
  w35 = 0.;
  /* #155: (@48[6] = @35) */
  for (rr=w48+6, ss=(&w35); rr!=w48+7; rr+=1) *rr = *ss++;
  /* #156: @35 = 0.9365 */
  w35 = 9.3650000000000000e-01;
  /* #157: (@48[10] = @35) */
  for (rr=w48+10, ss=(&w35); rr!=w48+11; rr+=1) *rr = *ss++;
  /* #158: @35 = 0 */
  w35 = 0.;
  /* #159: (@48[14] = @35) */
  for (rr=w48+14, ss=(&w35); rr!=w48+15; rr+=1) *rr = *ss++;
  /* #160: @35 = 0 */
  w35 = 0.;
  /* #161: (@48[3] = @35) */
  for (rr=w48+3, ss=(&w35); rr!=w48+4; rr+=1) *rr = *ss++;
  /* #162: @35 = 0 */
  w35 = 0.;
  /* #163: (@48[7] = @35) */
  for (rr=w48+7, ss=(&w35); rr!=w48+8; rr+=1) *rr = *ss++;
  /* #164: @35 = 0 */
  w35 = 0.;
  /* #165: (@48[11] = @35) */
  for (rr=w48+11, ss=(&w35); rr!=w48+12; rr+=1) *rr = *ss++;
  /* #166: @35 = 0.9752 */
  w35 = 9.7519999999999996e-01;
  /* #167: (@48[15] = @35) */
  for (rr=w48+15, ss=(&w35); rr!=w48+16; rr+=1) *rr = *ss++;
  /* #168: @43 = mac(@42,@48,@43) */
  for (i=0, rr=w43; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w42+j, tt=w48+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #169: @43 = (-@43) */
  for (i=0, rr=w43, cs=w43; i<16; ++i) *rr++ = (- *cs++ );
  /* #170: @44 = horzcat(@46, @43) */
  rr=w44;
  for (i=0, cs=w46; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<16; ++i) *rr++ = *cs++;
  /* #171: @49 = @44' */
  for (i=0, rr=w49, cs=w44; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #172: @50 = horzcat(@30, @45, @49) */
  rr=w50;
  for (i=0, cs=w30; i<33; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<44; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<44; ++i) *rr++ = *cs++;
  /* #173: @51 = @50' */
  for (i=0, rr=w51, cs=w50; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #174: @35 = input[0][2] */
  w35 = arg[0] ? arg[0][2] : 0;
  /* #175: @37 = input[0][7] */
  w37 = arg[0] ? arg[0][7] : 0;
  /* #176: @52 = input[0][8] */
  w52 = arg[0] ? arg[0][8] : 0;
  /* #177: @53 = input[0][9] */
  w53 = arg[0] ? arg[0][9] : 0;
  /* #178: @54 = vertcat(@2, @8, @35, @12, @20, @21, @22, @37, @52, @53, @36) */
  rr=w54;
  *rr++ = w2;
  *rr++ = w8;
  *rr++ = w35;
  *rr++ = w12;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w37;
  *rr++ = w52;
  *rr++ = w53;
  *rr++ = w36;
  /* #179: @15 = mac(@51,@54,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w51+j, tt=w54+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #180: @0 = mac(@14,@15,@0) */
  casadi_mtimes(w14, casadi_s6, w15, casadi_s5, (&w0), casadi_s4, w, 0);
  /* #181: @2 = 0 */
  w2 = 0.;
  /* #182: @38 = zeros(1x4) */
  casadi_clear(w38, 4);
  /* #183: @46 = zeros(4x7) */
  casadi_clear(w46, 28);
  /* #184: @43 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 16, w43);
  /* #185: @43 = (@47\@43) */
  rr = w43;
  ss = w47;
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[10], r[10], beta[4], w[8];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 4, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #186: @47 = @43' */
  for (i=0, rr=w47, cs=w43; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #187: @45 = horzcat(@46, @47) */
  rr=w45;
  for (i=0, cs=w46; i<28; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<16; ++i) *rr++ = *cs++;
  /* #188: @49 = @45' */
  for (i=0, rr=w49, cs=w45; i<11; ++i) for (j=0; j<4; ++j) rr[i+j*11] = *cs++;
  /* #189: @38 = mac(@14,@49,@38) */
  casadi_mtimes(w14, casadi_s6, w49, casadi_s8, w38, casadi_s7, w, 0);
  /* #190: @8 = input[1][0] */
  w8 = arg[1] ? arg[1][0] : 0;
  /* #191: @35 = input[1][1] */
  w35 = arg[1] ? arg[1][1] : 0;
  /* #192: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #193: @20 = input[1][3] */
  w20 = arg[1] ? arg[1][3] : 0;
  /* #194: @39 = vertcat(@8, @35, @12, @20) */
  rr=w39;
  *rr++ = w8;
  *rr++ = w35;
  *rr++ = w12;
  *rr++ = w20;
  /* #195: @2 = mac(@38,@39,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w39+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #196: @0 = (@0+@2) */
  w0 += w2;
  /* #197: @2 = 0.8 */
  w2 = 8.0000000000000004e-01;
  /* #198: @2 = (@2-@7) */
  w2 -= w7;
  /* #199: @0 = (@0+@2) */
  w0 += w2;
  /* #200: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #201: @55 = zeros(15x1) */
  casadi_clear(w55, 15);
  /* #202: @38 = @38' */
  /* #203: {@0, @2, @8, @35} = vertsplit(@38) */
  w0 = w38[0];
  w2 = w38[1];
  w8 = w38[2];
  w35 = w38[3];
  /* #204: (@55[0] = @0) */
  for (rr=w55+0, ss=(&w0); rr!=w55+1; rr+=1) *rr = *ss++;
  /* #205: (@55[1] = @2) */
  for (rr=w55+1, ss=(&w2); rr!=w55+2; rr+=1) *rr = *ss++;
  /* #206: (@55[2] = @8) */
  for (rr=w55+2, ss=(&w8); rr!=w55+3; rr+=1) *rr = *ss++;
  /* #207: (@55[3] = @35) */
  for (rr=w55+3, ss=(&w35); rr!=w55+4; rr+=1) *rr = *ss++;
  /* #208: @56 = zeros(11x1) */
  casadi_clear(w56, 11);
  /* #209: @57 = dense(@1) */
  casadi_densify(w1, casadi_s9, w57, 0);
  /* #210: @56 = mac(@50,@57,@56) */
  for (i=0, rr=w56; i<1; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w50+j, tt=w57+i*11; k<11; ++k) *rr += ss[k*11]**tt++;
  /* #211: {@35, @8, @2, @0, @12, @20, @21, @22, @37, @52, @53} = vertsplit(@56) */
  w35 = w56[0];
  w8 = w56[1];
  w2 = w56[2];
  w0 = w56[3];
  w12 = w56[4];
  w20 = w56[5];
  w21 = w56[6];
  w22 = w56[7];
  w37 = w56[8];
  w52 = w56[9];
  w53 = w56[10];
  /* #212: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #213: @36 = -1 */
  w36 = -1.;
  /* #214: @11 = (@11/@10) */
  w11 /= w10;
  /* #215: @1 = zeros(1x11,2nz) */
  casadi_clear(w1, 2);
  /* #216: @39 = @39' */
  /* #217: @1 = mac(@39,@45,@1) */
  casadi_mtimes(w39, casadi_s7, w45, casadi_s10, w1, casadi_s6, w, 0);
  /* #218: @56 = dense(@1) */
  casadi_densify(w1, casadi_s6, w56, 0);
  /* #219: @15 = @15' */
  /* #220: @56 = (@56+@15) */
  for (i=0, rr=w56, cs=w15; i<11; ++i) (*rr++) += (*cs++);
  /* #221: @56 = @56' */
  /* #222: @58 = @56[1] */
  for (rr=(&w58), ss=w56+1; ss!=w56+2; ss+=1) *rr++ = *ss;
  /* #223: @11 = (@11*@58) */
  w11 *= w58;
  /* #224: @4 = (@4/@10) */
  w4 /= w10;
  /* #225: @59 = 0 */
  w59 = 0.;
  /* #226: (@56[1] = @59) */
  for (rr=w56+1, ss=(&w59); rr!=w56+2; rr+=1) *rr = *ss++;
  /* #227: @59 = @56[0] */
  for (rr=(&w59), ss=w56+0; ss!=w56+1; ss+=1) *rr++ = *ss;
  /* #228: @4 = (@4*@59) */
  w4 *= w59;
  /* #229: @11 = (@11+@4) */
  w11 += w4;
  /* #230: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #231: @36 = (@36+@11) */
  w36 += w11;
  /* #232: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #233: @36 = (@36/@7) */
  w36 /= w7;
  /* #234: @3 = (@3*@36) */
  w3 *= w36;
  /* #235: @59 = (@59/@10) */
  w59 /= w10;
  /* #236: @6 = (@6*@59) */
  w6 *= w59;
  /* #237: @6 = (-@6) */
  w6 = (- w6 );
  /* #238: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #239: @3 = (@3+@6) */
  w3 += w6;
  /* #240: @35 = (@35+@3) */
  w35 += w3;
  /* #241: (@55[4] = @35) */
  for (rr=w55+4, ss=(&w35); rr!=w55+5; rr+=1) *rr = *ss++;
  /* #242: @58 = (@58/@10) */
  w58 /= w10;
  /* #243: @13 = (@13*@58) */
  w13 *= w58;
  /* #244: @13 = (-@13) */
  w13 = (- w13 );
  /* #245: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #246: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #247: @9 = (@9*@36) */
  w9 *= w36;
  /* #248: @13 = (@13+@9) */
  w13 += w9;
  /* #249: @8 = (@8+@13) */
  w8 += w13;
  /* #250: (@55[5] = @8) */
  for (rr=w55+5, ss=(&w8); rr!=w55+6; rr+=1) *rr = *ss++;
  /* #251: (@55[6] = @2) */
  for (rr=w55+6, ss=(&w2); rr!=w55+7; rr+=1) *rr = *ss++;
  /* #252: @39 = zeros(4x1) */
  casadi_clear(w39, 4);
  /* #253: @50 = zeros(11x11) */
  casadi_clear(w50, 121);
  /* #254: @54 = @54' */
  /* #255: @50 = mac(@57,@54,@50) */
  for (i=0, rr=w50; i<11; ++i) for (j=0; j<11; ++j, ++rr) for (k=0, ss=w57+j, tt=w54+i*1; k<1; ++k) *rr += ss[k*11]**tt++;
  /* #256: @51 = @50' */
  for (i=0, rr=w51, cs=w50; i<11; ++i) for (j=0; j<11; ++j) rr[i+j*11] = *cs++;
  /* #257: {@30, @45, @49} = horzsplit(@51) */
  casadi_copy(w51, 33, w30);
  casadi_copy(w51+33, 44, w45);
  casadi_copy(w51+77, 44, w49);
  /* #258: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<3; ++i) for (j=0; j<11; ++j) rr[i+j*3] = *cs++;
  /* #259: {NULL, @17, NULL} = horzsplit(@29) */
  casadi_copy(w29+21, 9, w17);
  /* #260: @2 = dot(@19, @17) */
  w2 = casadi_dot(9, w19, w17);
  /* #261: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #262: (@39[0] += @2) */
  for (rr=w39+0, ss=(&w2); rr!=w39+1; rr+=1) *rr += *ss++;
  /* #263: @18 = (@26*@17) */
  for (i=0, rr=w18, cs=w17; i<9; ++i) (*rr++)  = (w26*(*cs++));
  /* #264: @60 = zeros(3x3) */
  casadi_clear(w60, 9);
  /* #265: @61 = @27' */
  for (i=0, rr=w61, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #266: @60 = mac(@61,@17,@60) */
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w61+j, tt=w17+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #267: @18 = (@18+@60) */
  for (i=0, rr=w18, cs=w60; i<9; ++i) (*rr++) += (*cs++);
  /* #268: @60 = zeros(3x3) */
  casadi_clear(w60, 9);
  /* #269: @61 = @19' */
  for (i=0, rr=w61, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #270: @60 = mac(@17,@61,@60) */
  for (i=0, rr=w60; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w61+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #271: @60 = (2.*@60) */
  for (i=0, rr=w60, cs=w60; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #272: @18 = (@18+@60) */
  for (i=0, rr=w18, cs=w60; i<9; ++i) (*rr++) += (*cs++);
  /* #273: @26 = @18[5] */
  for (rr=(&w26), ss=w18+5; ss!=w18+6; ss+=1) *rr++ = *ss;
  /* #274: (@39[1] += @26) */
  for (rr=w39+1, ss=(&w26); rr!=w39+2; rr+=1) *rr += *ss++;
  /* #275: @26 = 0 */
  w26 = 0.;
  /* #276: (@18[5] = @26) */
  for (rr=w18+5, ss=(&w26); rr!=w18+6; rr+=1) *rr = *ss++;
  /* #277: @26 = @18[2] */
  for (rr=(&w26), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #278: @26 = (-@26) */
  w26 = (- w26 );
  /* #279: (@39[2] += @26) */
  for (rr=w39+2, ss=(&w26); rr!=w39+3; rr+=1) *rr += *ss++;
  /* #280: @26 = 0 */
  w26 = 0.;
  /* #281: (@18[2] = @26) */
  for (rr=w18+2, ss=(&w26); rr!=w18+3; rr+=1) *rr = *ss++;
  /* #282: @26 = @18[1] */
  for (rr=(&w26), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #283: (@39[3] += @26) */
  for (rr=w39+3, ss=(&w26); rr!=w39+4; rr+=1) *rr += *ss++;
  /* #284: @26 = 0 */
  w26 = 0.;
  /* #285: (@18[1] = @26) */
  for (rr=w18+1, ss=(&w26); rr!=w18+2; rr+=1) *rr = *ss++;
  /* #286: @26 = @18[7] */
  for (rr=(&w26), ss=w18+7; ss!=w18+8; ss+=1) *rr++ = *ss;
  /* #287: @26 = (-@26) */
  w26 = (- w26 );
  /* #288: (@39[1] += @26) */
  for (rr=w39+1, ss=(&w26); rr!=w39+2; rr+=1) *rr += *ss++;
  /* #289: @26 = 0 */
  w26 = 0.;
  /* #290: (@18[7] = @26) */
  for (rr=w18+7, ss=(&w26); rr!=w18+8; rr+=1) *rr = *ss++;
  /* #291: @26 = @18[6] */
  for (rr=(&w26), ss=w18+6; ss!=w18+7; ss+=1) *rr++ = *ss;
  /* #292: (@39[2] += @26) */
  for (rr=w39+2, ss=(&w26); rr!=w39+3; rr+=1) *rr += *ss++;
  /* #293: @26 = 0 */
  w26 = 0.;
  /* #294: (@18[6] = @26) */
  for (rr=w18+6, ss=(&w26); rr!=w18+7; rr+=1) *rr = *ss++;
  /* #295: @26 = @18[3] */
  for (rr=(&w26), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #296: @26 = (-@26) */
  w26 = (- w26 );
  /* #297: (@39[3] += @26) */
  for (rr=w39+3, ss=(&w26); rr!=w39+4; rr+=1) *rr += *ss++;
  /* #298: @38 = (@39/@24) */
  for (i=0, rr=w38, cr=w39; i<4; ++i) (*rr++)  = ((*cr++)/w24);
  /* #299: @25 = (@25/@24) */
  for (i=0, rr=w25; i<4; ++i) (*rr++) /= w24;
  /* #300: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<4; ++i) *rr++ = (- *cs++ );
  /* #301: @26 = dot(@25, @39) */
  w26 = casadi_dot(4, w25, w39);
  /* #302: @26 = (@26/@24) */
  w26 /= w24;
  /* #303: @23 = (@26*@23) */
  for (i=0, rr=w23, cs=w23; i<4; ++i) (*rr++)  = (w26*(*cs++));
  /* #304: @38 = (@38+@23) */
  for (i=0, rr=w38, cs=w23; i<4; ++i) (*rr++) += (*cs++);
  /* #305: {@26, @24, @2, @8} = vertsplit(@38) */
  w26 = w38[0];
  w24 = w38[1];
  w2 = w38[2];
  w8 = w38[3];
  /* #306: @0 = (@0+@26) */
  w0 += w26;
  /* #307: (@55[7] = @0) */
  for (rr=w55+7, ss=(&w0); rr!=w55+8; rr+=1) *rr = *ss++;
  /* #308: @12 = (@12+@24) */
  w12 += w24;
  /* #309: (@55[8] = @12) */
  for (rr=w55+8, ss=(&w12); rr!=w55+9; rr+=1) *rr = *ss++;
  /* #310: @20 = (@20+@2) */
  w20 += w2;
  /* #311: (@55[9] = @20) */
  for (rr=w55+9, ss=(&w20); rr!=w55+10; rr+=1) *rr = *ss++;
  /* #312: @21 = (@21+@8) */
  w21 += w8;
  /* #313: (@55[10] = @21) */
  for (rr=w55+10, ss=(&w21); rr!=w55+11; rr+=1) *rr = *ss++;
  /* #314: (@55[11] = @22) */
  for (rr=w55+11, ss=(&w22); rr!=w55+12; rr+=1) *rr = *ss++;
  /* #315: (@55[12] = @37) */
  for (rr=w55+12, ss=(&w37); rr!=w55+13; rr+=1) *rr = *ss++;
  /* #316: (@55[13] = @52) */
  for (rr=w55+13, ss=(&w52); rr!=w55+14; rr+=1) *rr = *ss++;
  /* #317: @47 = zeros(4x4) */
  casadi_clear(w47, 16);
  /* #318: @43 = @42' */
  for (i=0, rr=w43, cs=w42; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #319: @44 = @49' */
  for (i=0, rr=w44, cs=w49; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #320: {NULL, @42} = horzsplit(@44) */
  casadi_copy(w44+28, 16, w42);
  /* #321: @42 = (-@42) */
  for (i=0, rr=w42, cs=w42; i<16; ++i) *rr++ = (- *cs++ );
  /* #322: @47 = mac(@43,@42,@47) */
  for (i=0, rr=w47; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w43+j, tt=w42+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #323: @52 = 0 */
  w52 = 0.;
  /* #324: (@47[15] = @52) */
  for (rr=w47+15, ss=(&w52); rr!=w47+16; rr+=1) *rr = *ss++;
  /* #325: @52 = 0 */
  w52 = 0.;
  /* #326: (@47[11] = @52) */
  for (rr=w47+11, ss=(&w52); rr!=w47+12; rr+=1) *rr = *ss++;
  /* #327: @52 = 0 */
  w52 = 0.;
  /* #328: (@47[7] = @52) */
  for (rr=w47+7, ss=(&w52); rr!=w47+8; rr+=1) *rr = *ss++;
  /* #329: @52 = 0 */
  w52 = 0.;
  /* #330: (@47[3] = @52) */
  for (rr=w47+3, ss=(&w52); rr!=w47+4; rr+=1) *rr = *ss++;
  /* #331: @52 = 0 */
  w52 = 0.;
  /* #332: (@47[14] = @52) */
  for (rr=w47+14, ss=(&w52); rr!=w47+15; rr+=1) *rr = *ss++;
  /* #333: @52 = 0 */
  w52 = 0.;
  /* #334: (@47[10] = @52) */
  for (rr=w47+10, ss=(&w52); rr!=w47+11; rr+=1) *rr = *ss++;
  /* #335: @52 = 0 */
  w52 = 0.;
  /* #336: (@47[6] = @52) */
  for (rr=w47+6, ss=(&w52); rr!=w47+7; rr+=1) *rr = *ss++;
  /* #337: @52 = 0 */
  w52 = 0.;
  /* #338: (@47[2] = @52) */
  for (rr=w47+2, ss=(&w52); rr!=w47+3; rr+=1) *rr = *ss++;
  /* #339: @52 = 0 */
  w52 = 0.;
  /* #340: (@47[13] = @52) */
  for (rr=w47+13, ss=(&w52); rr!=w47+14; rr+=1) *rr = *ss++;
  /* #341: @52 = 0 */
  w52 = 0.;
  /* #342: (@47[9] = @52) */
  for (rr=w47+9, ss=(&w52); rr!=w47+10; rr+=1) *rr = *ss++;
  /* #343: @52 = 0 */
  w52 = 0.;
  /* #344: (@47[5] = @52) */
  for (rr=w47+5, ss=(&w52); rr!=w47+6; rr+=1) *rr = *ss++;
  /* #345: @52 = @47[1] */
  for (rr=(&w52), ss=w47+1; ss!=w47+2; ss+=1) *rr++ = *ss;
  /* #346: @34 = (@34*@52) */
  w34 *= w52;
  /* #347: @53 = (@53+@34) */
  w53 += w34;
  /* #348: @34 = 0 */
  w34 = 0.;
  /* #349: (@47[1] = @34) */
  for (rr=w47+1, ss=(&w34); rr!=w47+2; rr+=1) *rr = *ss++;
  /* #350: @34 = 0 */
  w34 = 0.;
  /* #351: (@47[12] = @34) */
  for (rr=w47+12, ss=(&w34); rr!=w47+13; rr+=1) *rr = *ss++;
  /* #352: @34 = 0 */
  w34 = 0.;
  /* #353: (@47[8] = @34) */
  for (rr=w47+8, ss=(&w34); rr!=w47+9; rr+=1) *rr = *ss++;
  /* #354: @34 = @47[4] */
  for (rr=(&w34), ss=w47+4; ss!=w47+5; ss+=1) *rr++ = *ss;
  /* #355: @33 = (@33*@34) */
  w33 *= w34;
  /* #356: @53 = (@53+@33) */
  w53 += w33;
  /* #357: @44 = @45' */
  for (i=0, rr=w44, cs=w45; i<4; ++i) for (j=0; j<11; ++j) rr[i+j*4] = *cs++;
  /* #358: {NULL, @47, NULL} = horzsplit(@44) */
  casadi_copy(w44+12, 16, w47);
  /* #359: @47 = (@32*@47) */
  for (i=0, rr=w47, cs=w47; i<16; ++i) (*rr++)  = (w32*(*cs++));
  /* #360: @43 = @47' */
  for (i=0, rr=w43, cs=w47; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #361: {@38, @23, @25, @39} = horzsplit(@43) */
  casadi_copy(w43, 4, w38);
  casadi_copy(w43+4, 4, w23);
  casadi_copy(w43+8, 4, w25);
  casadi_copy(w43+12, 4, w39);
  /* #362: @39 = @39' */
  /* #363: {@32, NULL, NULL, NULL} = horzsplit(@39) */
  w32 = w39[0];
  /* #364: @53 = (@53+@32) */
  w53 += w32;
  /* #365: @25 = @25' */
  /* #366: {NULL, @32, NULL, NULL} = horzsplit(@25) */
  w32 = w25[1];
  /* #367: @53 = (@53-@32) */
  w53 -= w32;
  /* #368: @23 = @23' */
  /* #369: {NULL, NULL, @32, NULL} = horzsplit(@23) */
  w32 = w23[2];
  /* #370: @53 = (@53+@32) */
  w53 += w32;
  /* #371: @38 = @38' */
  /* #372: {NULL, NULL, NULL, @32} = horzsplit(@38) */
  w32 = w38[3];
  /* #373: @53 = (@53-@32) */
  w53 -= w32;
  /* #374: (@55[14] = @53) */
  for (rr=w55+14, ss=(&w53); rr!=w55+15; rr+=1) *rr = *ss++;
  /* #375: output[1][0] = @55 */
  casadi_copy(w55, 15, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_constr_h_fun_jac_uxt_zt_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_jac_uxt_zt_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_constr_h_fun_jac_uxt_zt_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s14;
    case 2: return casadi_s15;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 15;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 757;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
